import {useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,ImagePlus,Plus,X} from 'lucide-react';
import type {PostDraft,PostMedia} from '../../services/socialService';

const SPECIALTIES=[['general','Tổng quát YHCT'],['internal','Nội khoa YHCT'],['acupuncture','Châm cứu'],['rehabilitation','Dưỡng sinh · PHCN'],['materia_medica','Dược liệu · Phương tễ'],['medicinal_diet','Dược thiện']] as const;
const POST_TYPES=[['research','Nghiên cứu'],['clinical_case','Ca lâm sàng'],['medicinal_diet','Dược thiện']] as const;
const VISIBILITIES=[['public','Công khai'],['members','Chỉ thành viên']] as const;
const DEFAULT_TAGS=['ChâmCứu','DượcLiệu','PhươngTễ','NộiKhoaYHCT','DưỡngSinh','HuyệtVị','DượcThiện','NghiênCứuYHCT','CaLâmSàng','YHCT'];
const MAX_TAGS=12,MAX_TAG_LENGTH=32,MAX_IMAGES=6,MAX_IMAGE_BYTES=8*1024*1024,MAX_MEDIA_DATA=1_800_000;
const RESEARCH_SOURCE='Dong AD, Bai YY, Xiao Y, et al. Steaming reduces Polygonum multiflorum hepatotoxicity by modulating gut microbiota-bile acid-FXR/NF-κB signaling in the gut-liver axis. Journal of Ethnopharmacology. doi:10.1016/j.jep.2026.122242. PMID:42532227. https://pubmed.ncbi.nlm.nih.gov/42532227/';

function normalizeTag(raw:string){return raw.replace(/^#+/,'').replace(/[^\p{L}\p{N}_-]/gu,'').slice(0,MAX_TAG_LENGTH)}
function meaningfulCitation(value:string){const s=value.trim();if(s.length<12)return false;const compact=s.replace(/[^\p{L}\p{N}]/gu,'');return compact.length>=8&&!/^(test|abc|asdf|khongco|none|null|nguon)$/i.test(compact)}
async function cropImage(file:File):Promise<PostMedia>{if(!file.type.startsWith('image/'))throw new Error(`${file.name}: không phải file ảnh.`);if(file.size>MAX_IMAGE_BYTES)throw new Error(`${file.name}: ảnh vượt 8 MB.`);const source=await createImageBitmap(file),landscape=source.width/source.height>=1.25,ratio=landscape?16/9:1,outW=landscape?1280:960,outH=Math.round(outW/ratio),srcRatio=source.width/source.height;let sx=0,sy=0,sw=source.width,sh=source.height;if(srcRatio>ratio){sw=Math.round(source.height*ratio);sx=Math.round((source.width-sw)/2)}else{sh=Math.round(source.width/ratio);sy=Math.round((source.height-sh)/2)}const canvas=document.createElement('canvas');canvas.width=outW;canvas.height=outH;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Trình duyệt không hỗ trợ xử lý ảnh.');ctx.drawImage(source,sx,sy,sw,sh,0,0,outW,outH);source.close();let quality=.82,dataUrl=canvas.toDataURL('image/webp',quality);while(dataUrl.length>450_000&&quality>.5){quality-=.08;dataUrl=canvas.toDataURL('image/webp',quality)}if(dataUrl.length>600_000)throw new Error(`${file.name}: ảnh vẫn quá lớn sau nén.`);return{id:crypto.randomUUID(),name:file.name.slice(0,120),url:dataUrl,aspect:landscape?'16:9':'1:1',width:outW,height:outH}}

export default function AcademicPostComposer({draft,onChange,onSave,onClose,busy,editing=false}:{draft:PostDraft;onChange:(next:PostDraft)=>void;onSave:()=>void;onClose:()=>void;busy:boolean;editing?:boolean}){
  const [tagInput,setTagInput]=useState(''),[error,setError]=useState(''),fileRef=useRef<HTMLInputElement>(null);
  const suggestions=useMemo(()=>DEFAULT_TAGS.filter(x=>!draft.tags.includes(x)&&x.toLocaleLowerCase('vi-VN').includes(tagInput.toLocaleLowerCase('vi-VN'))).slice(0,6),[draft.tags,tagInput]);
  const citationsOk=draft.citations.length>0&&draft.citations.every(meaningfulCitation),canSave=draft.title.trim().length>=5&&draft.chiefComplaint.trim().length>=8&&citationsOk&&!busy;
  useEffect(()=>()=>{for(const m of draft.media)if(m.url.startsWith('blob:'))URL.revokeObjectURL(m.url)},[]);
  const applyResearchTemplate=()=>onChange({...draft,title:'Hà thủ ô chế và độc tính gan: gợi ý cơ chế qua trục hệ vi sinh – acid mật – FXR/NF-κB',chiefComplaint:'Mẫu thảo luận nghiên cứu tiền lâm sàng: Dong và cộng sự khảo sát Hà thủ ô sống và các phương pháp chế trên mô hình chuột, kết hợp mô bệnh học và multi-omics. Nhóm tác giả báo cáo chế biến, đặc biệt chế với nước đậu đen, làm giảm các dấu hiệu tổn thương gan và điều biến hệ vi sinh/acid mật. Đây là dữ liệu tiền lâm sàng, không chứng minh an toàn tuyệt đối hoặc hiệu quả điều trị ở người.',postType:'research',specialty:'materia_medica',visibility:'public',tags:[...new Set([...draft.tags,'NghiênCứuYHCT','DượcLiệu','AnToànDượcLiệu'])].slice(0,MAX_TAGS),citations:[RESEARCH_SOURCE]});
  const addTag=(raw:string)=>{const value=normalizeTag(raw);if(!value)return;if(draft.tags.length>=MAX_TAGS){setError(`Tối đa ${MAX_TAGS} thẻ.`);return}if(!draft.tags.some(x=>x.toLocaleLowerCase('vi-VN')===value.toLocaleLowerCase('vi-VN')))onChange({...draft,tags:[...draft.tags,value]});setTagInput('');setError('')};
  const tagKey=(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Enter'||e.key===' '||e.key===','){e.preventDefault();addTag(tagInput)}else if(e.key==='Backspace'&&!tagInput&&draft.tags.length)onChange({...draft,tags:draft.tags.slice(0,-1)})};
  const pickImages=async(files:FileList|null)=>{if(!files?.length)return;setError('');try{const incoming=[...files].slice(0,Math.max(0,MAX_IMAGES-draft.media.length)),media:PostMedia[]=[];for(const file of incoming)media.push(await cropImage(file));const total=[...draft.media,...media].reduce((sum,x)=>sum+x.url.length,0);if(total>MAX_MEDIA_DATA)throw new Error('Tổng dữ liệu ảnh sau nén vượt giới hạn 1,8 MB. Hãy giảm số ảnh.');onChange({...draft,media:[...draft.media,...media]})}catch(e){setError((e as Error).message)}finally{if(fileRef.current)fileRef.current.value=''}};
  return <section className="academic-composer composer-editor" aria-label="Soạn bài học thuật"><header className="academic-composer__head"><div><h3>{editing?'Chỉnh sửa bài học thuật':'Bài học thuật mới'}</h3><p>Chỉ cần tiêu đề, tóm tắt và nguồn. Trường chuyên sâu được gom vào phần nâng cao.</p></div><button type="button" className="icon-btn" onClick={onClose} aria-label="Đóng"><X/></button></header>
    {!editing&&<button type="button" className="research-template-button" onClick={applyResearchTemplate}><BookOpen/><span><b>Dùng mẫu nghiên cứu mới có nguồn</b><small>PubMed PMID 42532227 · Hà thủ ô chế · nghiên cứu tiền lâm sàng</small></span></button>}
    <div className="composer-core"><label>Tiêu đề<input maxLength={300} value={draft.title} onChange={e=>onChange({...draft,title:e.target.value})} placeholder="Nêu rõ chủ đề học thuật"/></label><label>Tóm tắt / nội dung chính<textarea maxLength={8000} value={draft.chiefComplaint} onChange={e=>onChange({...draft,chiefComplaint:e.target.value})} placeholder="Điểm chính, mục tiêu hoặc nội dung cần thảo luận…"/></label><label>Nguồn trích dẫn / Tài liệu tham khảo<textarea className={!citationsOk&&draft.citations.length?'invalid-field':''} value={draft.citations.join('\n')} onChange={e=>onChange({...draft,citations:e.target.value.split('\n').map(x=>x.trim()).filter(Boolean)})} placeholder="DOI, PMID, URL PubMed hoặc tài liệu gốc — mỗi nguồn một dòng"/></label><small className={citationsOk?'citation-ok':'citation-help'}>{citationsOk?'Nguồn hợp lệ để gửi kiểm duyệt.':'Bắt buộc ít nhất 1 nguồn có ý nghĩa; không chấp nhận chuỗi test/abc/nguồn.'}</small></div>
    <details className="composer-classification"><summary>Phân loại & hiển thị</summary><div className="composer-select-grid"><label>Chuyên khoa<select value={draft.specialty} onChange={e=>onChange({...draft,specialty:e.target.value})}>{SPECIALTIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Loại bài<select value={draft.postType} onChange={e=>onChange({...draft,postType:e.target.value as PostDraft['postType']})}>{POST_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Hiển thị<select value={draft.visibility} onChange={e=>onChange({...draft,visibility:e.target.value as PostDraft['visibility']})}>{VISIBILITIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><div className="tag-editor"><span className="field-title">#tag</span><div className="tag-pills">{draft.tags.map(t=><span key={t}>#{t}<button type="button" onClick={()=>onChange({...draft,tags:draft.tags.filter(x=>x!==t)})} aria-label={`Xóa ${t}`}><X/></button></span>)}<input value={tagInput} maxLength={MAX_TAG_LENGTH} onChange={e=>setTagInput(e.target.value)} onKeyDown={tagKey} onBlur={()=>tagInput&&addTag(tagInput)} placeholder="Tag + Enter"/></div>{tagInput&&suggestions.length>0&&<div className="tag-suggestions">{suggestions.map(t=><button type="button" key={t} onMouseDown={e=>e.preventDefault()} onClick={()=>addTag(t)}>#{t}</button>)}</div>}</div></details>
    <details className="composer-advanced"><summary>Nội dung YHCT chuyên sâu (tùy chọn)</summary><div className="four"><label>Vọng<textarea value={draft.fourExams.vong} onChange={e=>onChange({...draft,fourExams:{...draft.fourExams,vong:e.target.value}})}/></label><label>Văn<textarea value={draft.fourExams.van} onChange={e=>onChange({...draft,fourExams:{...draft.fourExams,van:e.target.value}})}/></label><label>Vấn<textarea value={draft.fourExams.vanHoi} onChange={e=>onChange({...draft,fourExams:{...draft.fourExams,vanHoi:e.target.value}})}/></label><label>Thiết<textarea value={draft.fourExams.thiet} onChange={e=>onChange({...draft,fourExams:{...draft.fourExams,thiet:e.target.value}})}/></label></div><label>Bát cương<input value={draft.eightPrinciples.join(', ')} onChange={e=>onChange({...draft,eightPrinciples:e.target.value.split(/[;,]/).map(x=>x.trim()).filter(Boolean)})}/></label><label>Biện chứng<textarea value={draft.syndrome} onChange={e=>onChange({...draft,syndrome:e.target.value})}/></label><label>Pháp trị<textarea value={draft.treatmentPrinciple} onChange={e=>onChange({...draft,treatmentPrinciple:e.target.value})}/></label><label>Phương<textarea value={draft.formula||''} onChange={e=>onChange({...draft,formula:e.target.value})}/></label><label>Huyệt<input value={draft.acupoints.join(', ')} onChange={e=>onChange({...draft,acupoints:e.target.value.split(/[;,]/).map(x=>x.trim()).filter(Boolean)})}/></label></details>
    <div className="media-editor"><div className="between"><div><b>Ảnh minh họa</b><small>Tự crop 16:9/1:1 · tối đa {MAX_IMAGES} ảnh.</small></div><button type="button" className="secondary" disabled={draft.media.length>=MAX_IMAGES} onClick={()=>fileRef.current?.click()}><ImagePlus/>Thêm ảnh</button></div><input ref={fileRef} hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>void pickImages(e.target.files)}/>{draft.media.length>0&&<div className="media-preview-grid">{draft.media.map(m=><figure key={m.id} className={`media-${m.aspect.replace(':','x')}`}><img src={m.url} alt={m.name}/><figcaption>{m.aspect}<button type="button" onClick={()=>onChange({...draft,media:draft.media.filter(x=>x.id!==m.id)})}><X/></button></figcaption></figure>)}</div>}</div>
    {error&&<div className="error" role="alert">{error}</div>}<div className="schedule-actions"><button disabled={!canSave} onClick={onSave}>{busy?'Đang gửi…':<><Plus/>Gửi kiểm duyệt</>}</button><button className="secondary" onClick={onClose}>Đóng</button></div>
  </section>;
}
