import type { ExamAnswer,ExamQuestion } from '../types';
import { supabase } from './authService';
export function localGapAnalysis(answers:ExamAnswer[]){const wrong=answers.filter(a=>!a.correct);const counts=new Map<string,number>();wrong.forEach(a=>counts.set(a.topic,(counts.get(a.topic)||0)+1));return [...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([x])=>x)}
export async function analyzeExamGaps(answers:ExamAnswer[],questions:ExamQuestion[]):Promise<string>{const weak=localGapAnalysis(answers);if(!weak.length)return 'Kết quả hiện tại chưa cho thấy lỗ hổng nổi bật. Hãy duy trì ôn tập xen kẽ các phân môn.';const payload={weakTopics:weak,wrongQuestionIds:answers.filter(a=>!a.correct).slice(0,12).map(a=>a.questionId),context:questions.filter(q=>answers.some(a=>a.questionId===q.id&&!a.correct)).slice(0,12).map(q=>({id:q.id,topic:q.topic,explanation:q.explanation}))};try{const {data:{session}}=await supabase.auth.getSession();const headers:Record<string,string>={'Content-Type':'application/json'};if(session?.access_token)headers.authorization=`Bearer ${session.access_token}`;const r=await fetch('/api/ai/exam-gap',{method:'POST',headers,body:JSON.stringify(payload)});if(!r.ok)throw new Error('AI unavailable');const j=await r.json();return j.advice||`Ưu tiên ôn: ${weak.join(', ')}.`}catch{return `Ưu tiên ôn: ${weak.join(', ')}. AI cloud tạm thời không phản hồi; hệ thống đã dùng phân tích cục bộ.`}}
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
const herbRules:[string,string,string,string][]=[
  ['cam thao','cam toai','Thập Bát Phản','Cam thảo phản Cam toại'],['cam thao','dai kich','Thập Bát Phản','Cam thảo phản Đại kích'],['cam thao','hai tao','Thập Bát Phản','Cam thảo phản Hải tảo'],['cam thao','nguyen hoa','Thập Bát Phản','Cam thảo phản Nguyên hoa'],
  ['o dau','ban ha','Thập Bát Phản','Ô đầu phản Bán hạ'],['o dau','qua lau','Thập Bát Phản','Ô đầu phản Qua lâu'],['o dau','boi mau','Thập Bát Phản','Ô đầu phản Bối mẫu'],['o dau','bach cap','Thập Bát Phản','Ô đầu phản Bạch cập'],['o dau','bach liem','Thập Bát Phản','Ô đầu phản Bạch liễm'],
  ['le lo','nhan sam','Thập Bát Phản','Lê lô phản Nhân sâm'],['le lo','sa sam','Thập Bát Phản','Lê lô phản Sa sâm'],['le lo','dan sam','Thập Bát Phản','Lê lô phản Đan sâm'],['le lo','huyen sam','Thập Bát Phản','Lê lô phản Huyền sâm'],['le lo','te tan','Thập Bát Phản','Lê lô phản Tế tân'],['le lo','thuoc duoc','Thập Bát Phản','Lê lô phản Thược dược'],
  ['luu hoang','phac tieu','Thập Cửu Úy','Lưu hoàng úy Phác tiêu'],['thuy ngan','thach tin','Thập Cửu Úy','Thủy ngân úy Thạch tín'],['lang doc','mat da','Thập Cửu Úy','Lang độc úy Mật đà tăng'],['ba dau','khien nguu','Thập Cửu Úy','Ba đậu úy Khiên ngưu'],['dinh huong','uat kim','Thập Cửu Úy','Đinh hương úy Uất kim'],['xuyen o','te giac','Thập Cửu Úy','Xuyên ô úy Tê giác'],['thao o','te giac','Thập Cửu Úy','Thảo ô úy Tê giác'],['nha tieu','tam lang','Thập Cửu Úy','Nha tiêu úy Tam lăng'],['quan que','thach chi','Thập Cửu Úy','Quan quế úy Xích thạch chi'],['nhan sam','ngu linh chi','Thập Cửu Úy','Nhân sâm úy Ngũ linh chi']
];
export function checkHerbConflict(text:string){const n=norm(text);return herbRules.filter(([a,b])=>n.includes(a)&&n.includes(b)).map(([, ,rule,message])=>`Cảnh báo ${rule}: ${message}`)}
