import { createClient } from '@supabase/supabase-js';
import type { AppointmentTitle,Member,MemberStatus,SystemRole } from '../types';
const env=import.meta.env as Record<string,string|undefined>;
const url=(env.VITE_SUPABASE_URL||'https://gzmpnsrwqjpsbklyflqr.supabase.co').trim();
const anon=(env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_Y4hMhXROZ-aVgWoaQ5fFKQ_ZAcXuIzG').trim();
export const SUPABASE_URL=url;export const SUPABASE_PUBLISHABLE_KEY=anon;
export const supabase=createClient(url,anon,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const ref=(()=>{try{return new URL(url).hostname.split('.')[0]}catch{return ''}})();const authKey=`sb-${ref}-auth-token`;
const timeout=<T>(p:PromiseLike<T>,ms:number)=>new Promise<T>((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('timeout')),ms);Promise.resolve(p).then(v=>{clearTimeout(t);resolve(v)},e=>{clearTimeout(t);reject(e)})});
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
export function mapMember(row:Record<string,unknown>):Member{const title=(String(row.position_title||row.title||'Hội viên')) as AppointmentTitle;const role=(String(row.role||'member')) as SystemRole;const status=(String(row.status||'approved')) as MemberStatus;return {id:String(row.id||''),studentCode:String(row.student_code||row.studentCode||'')||undefined,fullName:String(row.full_name||row.fullName||'Thành viên'),email:String(row.email||'')||undefined,phone:String(row.phone||'')||undefined,role,title,status,reputation:Number(row.academic_reputation_multiplier||row.reputation||1)*20,totalPoints:Number(row.total_points||row.totalPoints||0),avatarUrl:String(row.avatar_url||row.avatarUrl||'')||undefined,herbalAlias:String(row.herbal_alias||row.herbalAlias||'')||undefined,wallTheme:String(row.wall_theme||row.wallTheme||'')||undefined,wallMotto:String(row.wall_motto||row.wallMotto||'')||undefined,departmentSlug:String(row.department_slug||'')||undefined,elementRank:String(row.element_rank||'')||undefined,loginEnabled:row.login_enabled===undefined?true:Boolean(row.login_enabled),dataConflict:Boolean(row.data_conflict)};}
export async function loginFast(studentCode:string,password:string):Promise<Member>{const c=new AbortController(); const t=setTimeout(()=>c.abort(),3500);try{const r=await fetch(`${url}/functions/v1/member-login`,{method:'POST',headers:{apikey:anon,'Content-Type':'application/json'},body:JSON.stringify({studentCode:studentCode.trim(),password}),signal:c.signal});const body=await r.json().catch(()=>({})); if(!r.ok)throw new Error(body.error||'Đăng nhập không thành công');const set=await timeout(supabase.auth.setSession({access_token:body.access_token,refresh_token:body.refresh_token}),1800) as {error?:Error|null}; if(set.error)throw set.error;return mapMember(body.member||{});}catch(e){if((e as Error).name==='AbortError'||(e as Error).message==='timeout')throw new Error('Máy chủ phản hồi chậm. Hãy thử lại ngay.'); throw e}finally{clearTimeout(t)}}
async function readSessionResilient(){let lastError:unknown=null;for(const [attempt,ms] of [2600,4500,6500].entries()){try{const result=await timeout(supabase.auth.getSession(),ms) as any;if(result.error)throw result.error;return result.data.session}catch(error){lastError=error;if(attempt<2)await sleep(250*(attempt+1))}}try{const raw=localStorage.getItem(authKey);const cached=raw?JSON.parse(raw):null;if(cached?.access_token&&cached?.user)return cached}catch{}if(lastError)throw lastError;return null}
async function loadMemberFromSession(session:any){const select='id,auth_user_id,full_name,avatar_url,herbal_alias,wall_theme,wall_motto,department_slug,role,status,element_rank,position_title,login_enabled,data_conflict,academic_reputation_multiplier';const memberId=String(session.user?.app_metadata?.member_id||'');const authUserId=String(session.user?.id||'');let query=memberId?supabase.from('club_members').select(select).eq('id',memberId).maybeSingle():supabase.from('club_members').select(select).eq('auth_user_id',authUserId).maybeSingle();let result=await timeout(query,6000) as any;if(result.error)throw result.error;if(!result.data&&memberId&&authUserId){result=await timeout(supabase.from('club_members').select(select).eq('auth_user_id',authUserId).maybeSingle(),6000) as any;if(result.error)throw result.error}if(!result.data)return null;return mapMember({...result.data,student_code:session.user?.user_metadata?.student_code})}
export async function restoreMember():Promise<Member|null>{let lastError:unknown=null;for(let attempt=0;attempt<3;attempt++){try{const session=await readSessionResilient();if(!session)return null;const member=await loadMemberFromSession(session);if(member)return member;return null}catch(error){lastError=error;if(attempt<2)await sleep(350*(attempt+1))}}console.warn('restoreMember failed after retries',lastError);return null}
export function logoutFast(){let token=''; try{const raw=localStorage.getItem(authKey); token=raw?JSON.parse(raw)?.access_token||'':''}catch{}try{localStorage.removeItem(authKey);sessionStorage.removeItem(authKey)}catch{}if(token)void fetch(`${url}/auth/v1/logout?scope=local`,{method:'POST',headers:{apikey:anon,Authorization:`Bearer ${token}`},keepalive:true}).catch(()=>{});}