import { supabase } from './authService';
export type ResearchWork={id:string;title:string;authors:string[];year:number|null;source:string;url:string;doi?:string;abstract?:string;citedBy?:number;provider:'PubMed'|'OpenAlex'|'ClinicalTrials.gov'|'Europe PMC'|'Crossref'};
export type RagDocument={id:string;name:string;mime:string;text:string;source:'local'|'drive';url?:string;updatedAt?:string};
const HTTP_TIMEOUT=8500,RAG_DB='yhct-hiu-rag-cache',RAG_STORE='documents';
const stripTags=(s:string)=>s.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const normalizeDoi=(s:string)=>String(s||'').replace(/^https?:\/\/(?:dx\.)?doi\.org\//i,'').trim();
async function fetchTimed(input:RequestInfo|URL,init:RequestInit={},timeout=HTTP_TIMEOUT){const c=new AbortController(),t=window.setTimeout(()=>c.abort(),timeout);try{return await fetch(input,{...init,signal:c.signal})}catch(e){if((e as Error).name==='AbortError')throw new Error('Nguồn dữ liệu quá thời gian chờ');throw e}finally{window.clearTimeout(t)}}
function decodeOpenAlexAbstract(index:Record<string,number[]>|null|undefined){if(!index)return'';let max=-1;for(const p of Object.values(index))for(const i of p)max=Math.max(max,i);const out=Array(max+1).fill('');for(const [w,p] of Object.entries(index))for(const i of p)out[i]=w;return out.join(' ')}
export async function searchOpenAlex(query:string,limit=10):Promise<ResearchWork[]>{const u=new URL('https://api.openalex.org/works');u.searchParams.set('search',query.trim());u.searchParams.set('per_page',String(Math.min(25,Math.max(1,limit))));u.searchParams.set('select','id,doi,title,publication_year,authorships,primary_location,cited_by_count,abstract_inverted_index');const r=await fetchTimed(u);if(!r.ok)throw new Error(`OpenAlex lỗi ${r.status}`);const d=await r.json();return(d.results||[]).map((w:any)=>({id:w.id,title:w.title||'Không tiêu đề',authors:(w.authorships||[]).map((a:any)=>a.author?.display_name).filter(Boolean),year:w.publication_year||null,source:w.primary_location?.source?.display_name||'OpenAlex',url:w.doi||w.id,doi:w.doi||undefined,abstract:decodeOpenAlexAbstract(w.abstract_inverted_index),citedBy:w.cited_by_count||0,provider:'OpenAlex'}))}
async function searchPubMedPrimary(query:string,limit=10):Promise<ResearchWork[]>{const es=new URL('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi');es.searchParams.set('db','pubmed');es.searchParams.set('term',query.trim());es.searchParams.set('retmode','json');es.searchParams.set('retmax',String(Math.min(25,Math.max(1,limit))));es.searchParams.set('tool','YHCT_HIU_4_0');const er=await fetchTimed(es);if(!er.ok)throw new Error(`PubMed ESearch lỗi ${er.status}`);const ed=await er.json(),ids:string[]=ed.esearchresult?.idlist||[];if(!ids.length)return[];const su=new URL('https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi');su.searchParams.set('db','pubmed');su.searchParams.set('id',ids.join(','));su.searchParams.set('retmode','json');su.searchParams.set('version','2.0');su.searchParams.set('tool','YHCT_HIU_4_0');const sr=await fetchTimed(su);if(!sr.ok)throw new Error(`PubMed ESummary lỗi ${sr.status}`);const sd=await sr.json();return ids.map(id=>sd.result?.[id]).filter(Boolean).map((x:any)=>({id:String(x.uid),title:stripTags(x.title||'Không tiêu đề'),authors:(x.authors||[]).map((a:any)=>a.name).filter(Boolean),year:Number((x.pubdate||'').slice(0,4))||null,source:x.fulljournalname||x.source||'PubMed',url:`https://pubmed.ncbi.nlm.nih.gov/${x.uid}/`,doi:(x.articleids||[]).find((a:any)=>a.idtype==='doi')?.value,provider:'PubMed'}))}
export async function searchEuropePmc(query:string,limit=10):Promise<ResearchWork[]>{const u=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');u.searchParams.set('query',query.trim());u.searchParams.set('format','json');u.searchParams.set('resultType','core');u.searchParams.set('pageSize',String(Math.min(25,Math.max(1,limit))));const r=await fetchTimed(u,{},7000);if(!r.ok)throw new Error(`Europe PMC lỗi ${r.status}`);const d=await r.json();return(d.resultList?.result||[]).map((x:any)=>{const sourceKey=String(x.source||'MED'),extId=String(x.id||x.pmid||x.pmcid||x.doi||x.title||'');const authors=(x.authorList?.author||[]).map((a:any)=>a.fullName||[a.firstName,a.lastName].filter(Boolean).join(' ')).filter(Boolean);const doi=normalizeDoi(x.doi||'')||undefined;return{id:`${sourceKey}:${extId}`,title:stripTags(x.title||'Không tiêu đề'),authors:authors.length?authors:String(x.authorString||'').split(',').map((s:string)=>s.trim()).filter(Boolean),year:Number(x.pubYear)||Number(String(x.firstPublicationDate||'').slice(0,4))||null,source:x.journalTitle||x.publisher||'Europe PMC',url:`https://europepmc.org/article/${encodeURIComponent(sourceKey)}/${encodeURIComponent(extId)}`,doi,abstract:stripTags(x.abstractText||''),citedBy:Number(x.citedByCount)||0,provider:'Europe PMC' as const}}).filter((w:ResearchWork)=>Boolean(w.id))}
export async function searchPubMed(query:string,limit=10):Promise<ResearchWork[]>{let primaryError:unknown=null;try{const primary=await searchPubMedPrimary(query,limit);if(primary.length)return primary}catch(e){primaryError=e}try{return await searchEuropePmc(query,limit)}catch(fallbackError){if(primaryError)throw new Error(`${(primaryError as Error).message} · fallback Europe PMC: ${(fallbackError as Error).message}`);throw fallbackError}}
async function searchClinicalTrialsPrimary(query:string,limit=8):Promise<ResearchWork[]>{const u=new URL('https://clinicaltrials.gov/api/v2/studies');u.searchParams.set('query.term',query.trim());u.searchParams.set('pageSize',String(Math.min(20,Math.max(1,limit))));u.searchParams.set('format','json');const r=await fetchTimed(u,{},9500);if(!r.ok)throw new Error(`ClinicalTrials.gov lỗi ${r.status}`);const d=await r.json();return(d.studies||[]).map((study:any)=>{const p=study.protocolSection||{},id=String(p.identificationModule?.nctId||''),title=p.identificationModule?.briefTitle||p.identificationModule?.officialTitle||id||'Không tiêu đề',lead=p.sponsorCollaboratorsModule?.leadSponsor?.name,summary=p.descriptionModule?.briefSummary||'',start=p.statusModule?.startDateStruct?.date||'',status=p.statusModule?.overallStatus||'';return{id,title,authors:lead?[lead]:[],year:Number(String(start).slice(0,4))||null,source:`ClinicalTrials.gov${status?` · ${status}`:''}`,url:`https://clinicaltrials.gov/study/${encodeURIComponent(id)}`,abstract:summary,provider:'ClinicalTrials.gov' as const}}).filter((w:ResearchWork)=>Boolean(w.id))}
export async function searchCrossref(query:string,limit=8):Promise<ResearchWork[]>{const u=new URL('https://api.crossref.org/works');u.searchParams.set('query.bibliographic',query.trim());u.searchParams.set('rows',String(Math.min(20,Math.max(1,limit))));const r=await fetchTimed(u,{headers:{accept:'application/json'}},7000);if(!r.ok)throw new Error(`Crossref lỗi ${r.status}`);const d=await r.json();return(d.message?.items||[]).map((x:any)=>{const doi=normalizeDoi(x.DOI||'')||undefined;const authors=(x.author||[]).map((a:any)=>[a.given,a.family].filter(Boolean).join(' ')).filter(Boolean);const year=Number(x.published?.['date-parts']?.[0]?.[0]||x.published_print?.['date-parts']?.[0]?.[0]||x.created?.['date-parts']?.[0]?.[0])||null;const title=stripTags(Array.isArray(x.title)?x.title[0]||'Không tiêu đề':x.title||'Không tiêu đề');return{id:doi||String(x.URL||title),title,authors,year,source:(Array.isArray(x['container-title'])&&x['container-title'][0])||x.publisher||'Crossref',url:x.URL||(doi?`https://doi.org/${doi}`:'https://search.crossref.org/'),doi,abstract:stripTags(x.abstract||''),citedBy:Number(x['is-referenced-by-count'])||0,provider:'Crossref' as const}}).filter((w:ResearchWork)=>Boolean(w.id))}
export async function searchClinicalTrials(query:string,limit=8):Promise<ResearchWork[]>{let primaryError:unknown=null;try{const primary=await searchClinicalTrialsPrimary(query,limit);if(primary.length)return primary}catch(e){primaryError=e}try{return await searchCrossref(query,limit)}catch(fallbackError){if(primaryError)throw new Error(`${(primaryError as Error).message} · fallback Crossref: ${(fallbackError as Error).message}`);throw fallbackError}}
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(RAG_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(RAG_STORE))r.result.createObjectStore(RAG_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('RAG cache bị khóa'))})}
export async function loadPersistedRagDocuments(){try{const db=await openDb();const docs=await new Promise<RagDocument[]>((resolve,reject)=>{const r=db.transaction(RAG_STORE).objectStore(RAG_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)});db.close();return docs.slice(0,500)}catch{return[]}}
export async function persistRagDocuments(docs:RagDocument[]){try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(RAG_STORE,'readwrite'),s=tx.objectStore(RAG_STORE);s.clear();for(const d of docs.slice(0,500))s.put({...d,text:(d.text||'').slice(0,1_000_000)});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}catch{}}
export async function ingestLocalFiles(files:File[]){const docs:RagDocument[]=[];for(const f of files.slice(0,200)){if(f.size>2*1024*1024)continue;const lower=f.name.toLowerCase(),textLike=f.type.startsWith('text/')||/\.(txt|md|csv|json|tsv|html?)$/.test(lower);let text='';if(textLike)try{text=(await f.text()).slice(0,1_000_000)}catch{}docs.push({id:`local:${f.webkitRelativePath||f.name}:${f.size}:${f.lastModified}`,name:(f.webkitRelativePath||f.name).slice(0,240),mime:f.type||'application/octet-stream',text,source:'local',updatedAt:new Date(f.lastModified).toISOString()})}return docs}
export async function listPublicDriveFolder(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Cần phiên Admin hợp lệ để đọc Drive RAG.');const r=await fetch('/api/research/drive',{cache:'no-store',headers:{authorization:`Bearer ${session.access_token}`}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`Drive API lỗi ${r.status}`);return(j.documents||[]) as RagDocument[]}
const terms=(s:string)=>new Set(s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().match(/[a-z0-9\u00C0-\u024f]{2,}/g)||[]);
export function retrieveLocalRag(query:string,documents:RagDocument[],limit=5){const q=terms(query);return documents.map(d=>{const sample=(d.text||d.name).slice(0,30000),t=terms(sample);let hit=0;for(const w of q)if(t.has(w))hit++;return{document:d,score:q.size?hit/q.size:0,snippet:bestSnippet(sample,q)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
function bestSnippet(text:string,q:Set<string>){if(!text)return'Tệp chưa có nội dung văn bản có thể lập chỉ mục trực tiếp trong trình duyệt.';const ss=text.replace(/\s+/g,' ').split(/(?<=[.!?。])\s+/).filter(Boolean);let best='',bs=-1;for(const s of ss){const t=terms(s);let sc=0;for(const w of q)if(t.has(w))sc++;if(sc>bs){bs=sc;best=s}}return(best||text.slice(0,500)).slice(0,700)}
export function extractiveSummary(text:string,maxSentences=5){const ss=text.replace(/\s+/g,' ').split(/(?<=[.!?。])\s+/).filter(s=>s.length>30);if(ss.length<=maxSentences)return ss.join(' ');const freq=new Map<string,number>();for(const s of ss)for(const w of terms(s))freq.set(w,(freq.get(w)||0)+1);return ss.map((s,i)=>({s,i,score:[...terms(s)].reduce((n,w)=>n+(freq.get(w)||0),0)})).sort((a,b)=>b.score-a.score).slice(0,maxSentences).sort((a,b)=>a.i-b.i).map(x=>x.s).join(' ')}
