import { useEffect,useMemo,useState } from 'react';
import { Award,KeyRound,Printer,RefreshCw,ShieldCheck } from 'lucide-react';
import type { Member } from '../../types';
import { supabase } from '../../services/authService';
import { changeMemberPassword } from '../../services/authRuntimeService';

type DrlSemester={semester_code:string;semester_title:string;total_points:number};
type ProfileSummary={id:string;full_name:string;student_code:string|null;email:string|null;role:string;position_title:string|null;avatar_url:string|null;element_rank:string|null;community_credits:number;community_rank:string;drl_semesters:DrlSemester[]};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase();
const validPassword=(value:string)=>value.length>=8&&/[A-Z]/.test(value)&&/[0-9]/.test(value)&&/[^A-Za-z0-9]/.test(value);

export default function ProfileCenter({member}:{member:Member}){
  const [profile,setProfile]=useState<ProfileSummary|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  const [passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState<{kind:'ok'|'bad';text:string}|null>(null);
  const load=async()=>{setLoading(true);setLoadError('');try{const {data,error}=await supabase.rpc('member_profile_summary_v1');if(error)throw error;setProfile(data as ProfileSummary)}catch(error){setLoadError(error instanceof Error?error.message:'Không thể tải hồ sơ.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[member.id]);
  const drlTotal=useMemo(()=>profile?.drl_semesters?.reduce((sum,item)=>sum+Number(item.total_points||0),0)||0,[profile]);
  const submitPassword=async(event:React.FormEvent)=>{event.preventDefault();setPasswordMessage(null);if(!validPassword(newPassword)){setPasswordMessage({kind:'bad',text:'Mật khẩu mới phải có ít nhất 8 ký tự, gồm chữ hoa, số và ký tự đặc biệt.'});return}if(newPassword!==confirmPassword){setPasswordMessage({kind:'bad',text:'Xác nhận mật khẩu mới chưa khớp.'});return}if(currentPassword===newPassword){setPasswordMessage({kind:'bad',text:'Mật khẩu mới phải khác mật khẩu hiện tại.'});return}setPasswordBusy(true);try{await changeMemberPassword(currentPassword,newPassword);setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage({kind:'ok',text:'Đổi mật khẩu thành công.'})}catch(error){setPasswordMessage({kind:'bad',text:error instanceof Error?error.message:'Không thể đổi mật khẩu.'})}finally{setPasswordBusy(false)}};
  const display=profile||{id:member.id,full_name:member.fullName,student_code:member.studentCode||null,email:member.email||null,role:member.role,position_title:member.title,avatar_url:member.avatarUrl||null,element_rank:member.elementRank||null,community_credits:0,community_rank:'Đang tải…',drl_semesters:[]};
  return <section className="profile-shell">
    <article className="panel"><div className="profile-summary"><div className="profile-avatar-large">{display.avatar_url?<img src={display.avatar_url} alt={`Ảnh đại diện ${display.full_name}`}/>:initials(display.full_name)}</div><div className="profile-summary-copy"><h2>{display.full_name}</h2><p>{display.student_code?`MSSV ${display.student_code}`:'MSSV chưa cập nhật'} · {display.email||'Email chưa cập nhật'}</p><div className="profile-role-row"><span className="profile-role-badge"><ShieldCheck/> {display.role}</span><span className="profile-rank-badge"><Award/> {display.community_rank||display.element_rank||'Chưa xếp hạng'}</span></div></div></div>
      {loadError&&<div className="error" role="alert">{loadError}</div>}
      <div className="profile-kpis"><article><b>{drlTotal}</b><small>Tổng DRL đã công bố</small></article><article><b>{display.community_credits}</b><small>Tín dụng cộng đồng trọn đời</small></article><article><b>{display.drl_semesters.length}</b><small>Học kỳ đã chốt</small></article></div>
      <div className="schedule-actions"><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw/>Làm mới</button><button className="secondary" onClick={()=>window.print()}><Printer/>In hồ sơ</button><button onClick={()=>setPasswordOpen(open=>!open)}><KeyRound/>{passwordOpen?'Đóng đổi mật khẩu':'Đổi mật khẩu'}</button></div>
    </article>

    <article className="panel"><h3>Điểm rèn luyện theo học kỳ</h3>{loading?<p className="muted">Đang tải dữ liệu đã công bố…</p>:display.drl_semesters.length?<div className="profile-drl-grid">{display.drl_semesters.map(item=><article key={item.semester_code}><b>{item.semester_title}</b><small>{item.semester_code}</small><strong>{Number(item.total_points||0)} điểm</strong></article>)}</div>:<p className="muted">Chưa có học kỳ được công bố.</p>}</article>

    {passwordOpen&&<article className="panel"><div className="row"><KeyRound/><div><h3>Đổi mật khẩu</h3><p className="muted">Mật khẩu hiện tại được xác minh ở backend; mật khẩu mới không được lưu trong ứng dụng.</p></div></div><form className="password-form" onSubmit={event=>void submitPassword(event)}><label>Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} autoComplete="current-password" required disabled={passwordBusy}/></label><label>Mật khẩu mới<input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} autoComplete="new-password" required disabled={passwordBusy}/></label><label>Xác nhận mật khẩu mới<input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} autoComplete="new-password" required disabled={passwordBusy}/></label><p className="password-requirements">Tối thiểu 8 ký tự, có chữ hoa, số và ký tự đặc biệt.</p>{passwordMessage&&<div className={`password-toast ${passwordMessage.kind}`} role="status">{passwordMessage.text}</div>}<div className="password-actions"><button type="submit" disabled={passwordBusy||!currentPassword||!newPassword||!confirmPassword}>{passwordBusy?'Đang cập nhật…':'Xác nhận đổi mật khẩu'}</button><button type="button" className="secondary" disabled={passwordBusy} onClick={()=>{setPasswordOpen(false);setPasswordMessage(null);setCurrentPassword('');setNewPassword('');setConfirmPassword('')}}>Hủy</button></div></form></article>}
  </section>;
}
