import {useEffect,useMemo,useRef,useState} from 'react';
import {Award,Camera,ImagePlus,KeyRound,Palette,Printer,RefreshCw,Send,ShieldCheck,Trash2} from 'lucide-react';
import type {Member} from '../../types';
import {supabase} from '../../services/authService';
import {changeMemberPassword} from '../../services/authRuntimeService';
import styles from './ProfileCenter.module.css';

type DrlSemester={semester_code:string;semester_title:string;total_points:number};
type ProfileSummary={id:string;full_name:string;student_code:string|null;email:string|null;role:string;position_title:string|null;avatar_url:string|null;element_rank:string|null;community_credits:number;community_rank:string;drl_semesters:DrlSemester[]};
type WallPost={id:string;body:string;image_url?:string|null;visibility:'public'|'members';created_at:string};
type WallData={member:{id:string;full_name:string;herbal_alias:string;avatar_url?:string|null;position_title?:string|null;wall_theme:string;wall_motto?:string|null};posts:WallPost[]};
const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(-2).map(x=>x[0]).join('').toUpperCase();
const validPassword=(value:string)=>value.length>=8&&/[A-Z]/.test(value)&&/[0-9]/.test(value)&&/[^A-Za-z0-9]/.test(value);
const THEMES=[['herbal-paper','Giấy thảo mộc'],['bamboo','Trúc xanh'],['lotus','Liên hoa'],['stone','Thạch viên'],['lantern','Đèn dược phòng']] as const;
async function imageToWebp(file:File,max=1280){if(!file.type.startsWith('image/'))throw new Error('Chỉ hỗ trợ JPG, PNG hoặc WebP.');if(file.size>5*1024*1024)throw new Error('Ảnh vượt giới hạn 5 MB.');const src=await createImageBitmap(file),scale=Math.min(1,max/Math.max(src.width,src.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(src.width*scale));canvas.height=Math.max(1,Math.round(src.height*scale));const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Trình duyệt không hỗ trợ xử lý ảnh.');ctx.drawImage(src,0,0,canvas.width,canvas.height);src.close();return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Không nén được ảnh.')),'image/webp',.82))}

export default function ProfileCenter({member}:{member:Member}){
  const [profile,setProfile]=useState<ProfileSummary|null>(null),[wall,setWall]=useState<WallData|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('');
  const [wallBody,setWallBody]=useState(''),[wallVisibility,setWallVisibility]=useState<'public'|'members'>('public'),[wallImage,setWallImage]=useState<File|null>(null),[wallBusy,setWallBusy]=useState(false),[wallMsg,setWallMsg]=useState(''),wallFile=useRef<HTMLInputElement>(null),avatarFile=useRef<HTMLInputElement>(null);
  const [theme,setTheme]=useState('herbal-paper'),[motto,setMotto]=useState('');
  const [passwordOpen,setPasswordOpen]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[passwordBusy,setPasswordBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState<{kind:'ok'|'bad';text:string}|null>(null);
  const load=async()=>{setLoading(true);setLoadError('');try{const [p,w]=await Promise.all([supabase.rpc('member_profile_summary_v1'),supabase.rpc('member_wall_feed_v1',{p_member_id:member.id})]);if(p.error)throw p.error;if(w.error)throw w.error;setProfile(p.data as ProfileSummary);const wd=w.data as WallData;setWall(wd);setTheme(wd.member.wall_theme||'herbal-paper');setMotto(wd.member.wall_motto||'')}catch(error){setLoadError(error instanceof Error?error.message:'Không thể tải hồ sơ.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[member.id]);
  const drlTotal=useMemo(()=>profile?.drl_semesters?.reduce((sum,item)=>sum+Number(item.total_points||0),0)||0,[profile]);
  const upload=async(file:File,folder:string)=>{const blob=await imageToWebp(file),{data:userData}=await supabase.auth.getUser(),uid=userData.user?.id;if(!uid)throw new Error('Phiên đăng nhập đã hết hạn.');const path=`${uid}/${folder}/${crypto.randomUUID()}.webp`,result=await supabase.storage.from('member-media').upload(path,blob,{contentType:'image/webp',cacheControl:'31536000'});if(result.error)throw result.error;return supabase.storage.from('member-media').getPublicUrl(path).data.publicUrl};
  const changeAvatar=async(file:File|null)=>{if(!file)return;setWallBusy(true);setWallMsg('');try{const url=await upload(file,'avatar'),r=await supabase.rpc('member_profile_update_v2',{p_avatar_url:url,p_wall_theme:null,p_wall_motto:null});if(r.error)throw r.error;setWallMsg('Đã cập nhật ảnh đại diện.');await load()}catch(e){setWallMsg((e as Error).message)}finally{setWallBusy(false);if(avatarFile.current)avatarFile.current.value=''}};
  const saveDecor=async()=>{setWallBusy(true);setWallMsg('');try{const r=await supabase.rpc('member_profile_update_v2',{p_avatar_url:null,p_wall_theme:theme,p_wall_motto:motto});if(r.error)throw r.error;setWallMsg('Đã lưu trang trí tường cá nhân.');await load()}catch(e){setWallMsg((e as Error).message)}finally{setWallBusy(false)}};
  const postWall=async()=>{const body=wallBody.trim();if(!body||body.length>500)return;setWallBusy(true);setWallMsg('');try{const imageUrl=wallImage?await upload(wallImage,'wall'):null,r=await supabase.rpc('member_wall_post_create_v1',{p_body:body,p_image_url:imageUrl,p_visibility:wallVisibility});if(r.error)throw r.error;setWallBody('');setWallImage(null);if(wallFile.current)wallFile.current.value='';setWallMsg('Đã đăng lên tường cá nhân.');await load()}catch(e){setWallMsg((e as Error).message)}finally{setWallBusy(false)}};
  const deleteWall=async(id:string)=>{setWallBusy(true);try{const r=await supabase.rpc('member_wall_post_delete_v1',{p_id:id});if(r.error)throw r.error;await load()}catch(e){setWallMsg((e as Error).message)}finally{setWallBusy(false)}};
  const submitPassword=async(event:React.FormEvent)=>{event.preventDefault();setPasswordMessage(null);if(!validPassword(newPassword)){setPasswordMessage({kind:'bad',text:'Mật khẩu mới phải có ít nhất 8 ký tự, gồm chữ hoa, số và ký tự đặc biệt.'});return}if(newPassword!==confirmPassword){setPasswordMessage({kind:'bad',text:'Xác nhận mật khẩu mới chưa khớp.'});return}if(currentPassword===newPassword){setPasswordMessage({kind:'bad',text:'Mật khẩu mới phải khác mật khẩu hiện tại.'});return}setPasswordBusy(true);try{await changeMemberPassword(currentPassword,newPassword);setCurrentPassword('');setNewPassword('');setConfirmPassword('');setPasswordMessage({kind:'ok',text:'Đổi mật khẩu thành công.'})}catch(error){setPasswordMessage({kind:'bad',text:error instanceof Error?error.message:'Không thể đổi mật khẩu.'})}finally{setPasswordBusy(false)}};
  const display=profile||{id:member.id,full_name:member.fullName,student_code:member.studentCode||null,email:member.email||null,role:member.role,position_title:member.title,avatar_url:member.avatarUrl||null,element_rank:member.elementRank||null,community_credits:0,community_rank:'Đang tải…',drl_semesters:[]};
  const alias=wall?.member.herbal_alias||member.herbalAlias||display.full_name;
  const wallTheme=wall?.member.wall_theme||theme;

  return <section className={styles.root} data-wall-theme={wallTheme}>
    <article className={`${styles.card} ${styles.overviewCard}`}>
      <div className={styles.summary}>
        <div className={styles.avatar}>{(wall?.member.avatar_url||display.avatar_url)?<img src={wall?.member.avatar_url||display.avatar_url||''} alt={`Ảnh đại diện ${display.full_name}`}/>:initials(display.full_name)}<button onClick={()=>avatarFile.current?.click()} disabled={wallBusy} aria-label="Đổi ảnh đại diện"><Camera/></button><input ref={avatarFile} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>void changeAvatar(e.target.files?.[0]||null)}/></div>
        <div className={styles.summaryCopy}><h2>{alias}</h2><p><b>{display.full_name}</b> · {display.student_code?`MSSV ${display.student_code}`:'MSSV chưa cập nhật'} · {display.email||'Email chưa cập nhật'}</p>{wall?.member.wall_motto&&<p className={styles.motto}>“{wall.member.wall_motto}”</p>}<div className={styles.roleRow}><span className={styles.roleBadge}><ShieldCheck/> {display.role}</span><span className={styles.rankBadge}><Award/> {display.community_rank||display.element_rank||'Chưa xếp hạng'}</span></div></div>
      </div>
      {loadError&&<div className={styles.statusError} role="alert">{loadError}</div>}{wallMsg&&<div className={styles.status} role="status">{wallMsg}</div>}
      <div className={styles.kpis}><article><b>{drlTotal}</b><small>Tổng DRL đã công bố</small></article><article><b>{display.community_credits}</b><small>Tín dụng cộng đồng trọn đời</small></article><article><b>{display.drl_semesters.length}</b><small>Học kỳ đã chốt</small></article></div>
      <div className={styles.actions}><button className={styles.secondaryButton} disabled={loading} onClick={()=>void load()}><RefreshCw/>Làm mới</button><button className={styles.secondaryButton} onClick={()=>window.print()}><Printer/>In hồ sơ</button><button className={styles.primaryButton} onClick={()=>setPasswordOpen(open=>!open)}><KeyRound/>{passwordOpen?'Đóng đổi mật khẩu':'Đổi mật khẩu'}</button></div>
    </article>

    <article className={`${styles.card} ${styles.wallCard}`}>
      <div className={styles.between}><div className={styles.row}><Palette/><div><h3>Tường cá nhân · {alias}</h3><p className={styles.muted}>Trang trí, status tối đa 500 ký tự và ảnh. Chỉ hiển thị 3 bài mới nhất.</p></div></div></div>
      <div className={styles.wallCustomize}><label>Phong cách<select value={theme} onChange={e=>setTheme(e.target.value)}>{THEMES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Lời giới thiệu<input maxLength={160} value={motto} onChange={e=>setMotto(e.target.value)} placeholder="Một câu ngắn trên tường…"/></label><button className={styles.secondaryButton} disabled={wallBusy} onClick={()=>void saveDecor()}>Lưu trang trí</button></div>
      <div className={styles.wallCompose}><textarea maxLength={500} value={wallBody} onChange={e=>setWallBody(e.target.value)} placeholder="Bạn đang nghĩ gì về YHCT hôm nay?"/><div className={styles.wallComposeFooter}><small>{wallBody.length}/500</small><div className={styles.actions}><select value={wallVisibility} onChange={e=>setWallVisibility(e.target.value as typeof wallVisibility)}><option value="public">Công khai</option><option value="members">Thành viên</option></select><button className={styles.secondaryButton} onClick={()=>wallFile.current?.click()} disabled={wallBusy}><ImagePlus/>{wallImage?'Đã chọn ảnh':'Thêm ảnh'}</button><input ref={wallFile} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>setWallImage(e.target.files?.[0]||null)}/><button className={styles.primaryButton} disabled={wallBusy||!wallBody.trim()} onClick={()=>void postWall()}><Send/>Đăng</button></div></div></div>
      <div className={styles.wallPosts}>{wall?.posts.map(post=><article className={styles.wallPost} key={post.id}><div className={styles.between}><small>{new Date(post.created_at).toLocaleString('vi-VN')} · {post.visibility==='members'?'Thành viên':'Công khai'}</small><button className={styles.iconButton} disabled={wallBusy} onClick={()=>void deleteWall(post.id)} aria-label="Xóa bài trên tường"><Trash2/></button></div><p>{post.body}</p>{post.image_url&&<img src={post.image_url} alt="Ảnh trên tường cá nhân" loading="lazy"/>}</article>)}{!loading&&!wall?.posts.length&&<p className={styles.muted}>Tường chưa có bài viết.</p>}</div>
    </article>

    <article className={`${styles.card} ${styles.drlCard}`}><h3>Điểm rèn luyện theo học kỳ</h3>{loading?<p className={styles.muted}>Đang tải dữ liệu đã công bố…</p>:display.drl_semesters.length?<div className={styles.drlGrid}>{display.drl_semesters.map(item=><article key={item.semester_code}><b>{item.semester_title}</b><small>{item.semester_code}</small><strong>{Number(item.total_points||0)} điểm</strong></article>)}</div>:<p className={styles.muted}>Chưa có học kỳ được công bố.</p>}</article>

    {passwordOpen&&<article className={`${styles.card} ${styles.passwordCard}`}><div className={styles.row}><KeyRound/><div><h3>Đổi mật khẩu</h3><p className={styles.muted}>Mật khẩu hiện tại được xác minh ở backend; mật khẩu mới không được lưu trong ứng dụng.</p></div></div><form className={styles.passwordForm} onSubmit={event=>void submitPassword(event)}><label>Mật khẩu hiện tại<input type="password" value={currentPassword} onChange={event=>setCurrentPassword(event.target.value)} autoComplete="current-password" required disabled={passwordBusy}/></label><label>Mật khẩu mới<input type="password" value={newPassword} onChange={event=>setNewPassword(event.target.value)} autoComplete="new-password" required disabled={passwordBusy}/></label><label>Xác nhận mật khẩu mới<input type="password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} autoComplete="new-password" required disabled={passwordBusy}/></label><p className={styles.passwordRequirements}>Tối thiểu 8 ký tự, có chữ hoa, số và ký tự đặc biệt.</p>{passwordMessage&&<div className={`${styles.passwordToast} ${passwordMessage.kind==='ok'?styles.passwordToastOk:styles.passwordToastBad}`} role="status">{passwordMessage.text}</div>}<div className={styles.passwordActions}><button className={styles.primaryButton} type="submit" disabled={passwordBusy||!currentPassword||!newPassword||!confirmPassword}>{passwordBusy?'Đang cập nhật…':'Xác nhận đổi mật khẩu'}</button><button type="button" className={styles.secondaryButton} disabled={passwordBusy} onClick={()=>{setPasswordOpen(false);setPasswordMessage(null);setCurrentPassword('');setNewPassword('');setConfirmPassword('')}}>Hủy</button></div></form></article>}
  </section>;
}
