import mammoth from 'mammoth';
import {createSign} from 'node:crypto';

export const DEFAULT_RESEARCH_FOLDER_ID='1IjoX3TwCz-mp4g6tE72OnWv2rH00m1NX';
const MAX_FILES=80,MAX_TEXT=750000,CACHE_MS=5*60*1000,HTTP_MS=9000;
let cache={at:0,documents:[],folderId:''};
const clean=(v,max=1000)=>String(v??'').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/\s+/g,' ').trim().slice(0,max);
const folderId=()=>String(process.env.YHCT_DRIVE_RESEARCH_FOLDER_ID||DEFAULT_RESEARCH_FOLDER_ID).trim();
const apiKey=()=>String(process.env.GOOGLE_DRIVE_API_KEY||'').trim();
let tokenCache={token:'',expiresAt:0};
function serviceAccount(){const raw=String(process.env.GOOGLE_SERVICE_ACCOUNT_JSON||'').trim();if(!raw)return null;try{const value=JSON.parse(raw),email=clean(value?.client_email,320),key=String(value?.private_key||'').replace(/\\n/g,'\n');return email&&key?{email,key}:null}catch{return null}}
const b64url=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
async function serviceToken(){const cfg=serviceAccount();if(!cfg)return'';const now=Math.floor(Date.now()/1000);if(tokenCache.token&&tokenCache.expiresAt>now+60)return tokenCache.token;const header=b64url({alg:'RS256',typ:'JWT'}),claims=b64url({iss:cfg.email,scope:'https://www.googleapis.com/auth/drive.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3300}),unsigned=`${header}.${claims}`,signer=createSign('RSA-SHA256');signer.update(unsigned);signer.end();const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${unsigned}.${signer.sign(cfg.key,'base64url')}`})});if(!response.ok)throw new Error(`Google OAuth ${response.status}`);const payload=await response.json(),token=String(payload?.access_token||'');if(!token)throw new Error('Google OAuth returned no access token');tokenCache={token,expiresAt:now+Math.min(3200,Number(payload?.expires_in||3300))};return token}
const driveConfigured=()=>Boolean(serviceAccount()||apiKey());
async function driveFetch(url,init={},ms=HTTP_MS){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const target=new URL(String(url)),headers=new Headers(init.headers||{}),token=await serviceToken();if(token)headers.set('authorization',`Bearer ${token}`);else{const key=apiKey();if(!key)throw new Error('Google Drive credential missing');target.searchParams.set('key',key)}headers.set('user-agent','HIU-YHCT-Research-RAG/1.0');return await fetch(target,{...init,headers,signal:c.signal})}finally{clearTimeout(t)}}
const fileUrl=f=>{const id=encodeURIComponent(f.id),mime=String(f.mimeType||'');if(mime==='application/vnd.google-apps.document')return`https://docs.google.com/document/d/${id}/edit`;if(mime==='application/vnd.google-apps.spreadsheet')return`https://docs.google.com/spreadsheets/d/${id}/edit`;if(mime==='application/vnd.google-apps.presentation')return`https://docs.google.com/presentation/d/${id}/edit`;return`https://drive.google.com/file/d/${id}/view`};
async function listChildren(parent){const u=new URL('https://www.googleapis.com/drive/v3/files');u.searchParams.set('q',`'${parent}' in parents and trashed=false`);u.searchParams.set('fields','files(id,name,mimeType,modifiedTime,size,webViewLink)');u.searchParams.set('pageSize','100');u.searchParams.set('orderBy','modifiedTime desc');u.searchParams.set('supportsAllDrives','true');u.searchParams.set('includeItemsFromAllDrives','true');const r=await driveFetch(u);if(!r.ok)throw new Error(`Google Drive list ${r.status}`);return (await r.json()).files||[]}
async function rawBytes(file){const u=new URL(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}`);u.searchParams.set('alt','media');const r=await driveFetch(u,{},11000);if(!r.ok)return null;const length=Number(r.headers.get('content-length')||0);if(length>5_000_000)return null;return Buffer.from(await r.arrayBuffer())}
async function exportText(file,mimeType){const u=new URL(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}/export`);u.searchParams.set('mimeType',mimeType);const r=await driveFetch(u,{},11000);return r.ok?(await r.text()).slice(0,MAX_TEXT):''}
async function extractText(file){const mime=String(file.mimeType||''),name=String(file.name||'').toLowerCase();try{
  if(mime==='application/vnd.google-apps.document')return await exportText(file,'text/plain');
  if(mime==='application/vnd.google-apps.spreadsheet')return await exportText(file,'text/csv');
  if(mime==='application/vnd.google-apps.presentation')return await exportText(file,'text/plain');
  if(mime.startsWith('text/')||mime.includes('json')||mime.includes('csv')||mime.includes('markdown')){const b=await rawBytes(file);return b?b.toString('utf8').slice(0,MAX_TEXT):''}
  if(mime==='application/vnd.openxmlformats-officedocument.wordprocessingml.document'||name.endsWith('.docx')){const b=await rawBytes(file);if(!b)return'';const out=await mammoth.extractRawText({buffer:b});return clean(out.value,MAX_TEXT)}
  return'';
}catch{return''}}
export async function buildDriveRagIndex({force=false}={}){const root=folderId();if(!driveConfigured())return{configured:false,folderId:root,documents:[],reason:'missing_google_drive_credential'};if(!force&&cache.folderId===root&&Date.now()-cache.at<CACHE_MS)return{configured:true,folderId:root,documents:cache.documents,cached:true};
 const first=await listChildren(root),files=[];for(const f of first){if(f.mimeType==='application/vnd.google-apps.folder'){const nested=await listChildren(f.id).catch(()=>[]);files.push(...nested.map(x=>({...x,parentName:f.name})))}else files.push(f);if(files.length>=MAX_FILES)break}const selected=files.slice(0,MAX_FILES);const texts=await Promise.allSettled(selected.map(f=>extractText(f)));const docs=selected.map((f,i)=>({id:String(f.id),name:clean(f.name,240),mime:String(f.mimeType||''),text:texts[i].status==='fulfilled'?texts[i].value:'',source:'drive',url:f.webViewLink||fileUrl(f),updatedAt:f.modifiedTime||null,parentName:clean(f.parentName||'',160)}));cache={at:Date.now(),documents:docs,folderId:root};return{configured:true,folderId:root,documents:docs,cached:false}}
const tokens=s=>new Set(clean(s,10000).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().match(/[a-z0-9]{2,}/g)||[]);
export function retrieveDriveRag(query,documents,limit=5){const q=tokens(query);return documents.map(d=>{const sample=(d.text||d.name).slice(0,50000),t=tokens(sample);let hit=0;for(const w of q)if(t.has(w))hit++;const score=q.size?hit/q.size:0;let snippet='';if(d.text){const parts=d.text.replace(/\s+/g,' ').split(/(?<=[.!?])\s+/).filter(Boolean);let best=-1;for(const p of parts){const pt=tokens(p);let s=0;for(const w of q)if(pt.has(w))s++;if(s>best){best=s;snippet=p}}}return{document:d,score,snippet:clean(snippet||d.text||d.name,900)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,Math.max(1,Math.min(8,limit)))}
