import {useEffect,useMemo,useState} from 'react';
import {BrainCircuit,CheckCircle2,DatabaseBackup,RefreshCw,ShieldAlert,Trash2} from 'lucide-react';
import {supabase} from '../../services/authService';

type Ops={pendingModeration:number;openFeedback:number;recentErrors:number;recentWarnings:number;lastDailySnapshotAt?:string|null;lastMonthlySnapshotAt?:string|null;serverTime:string};
type Feedback={id:string;reporter_name:string;reporter_student_code:string;kind:string;body:string;context:Record<string,unknown>;status:string;created_at:string};
function ageHours(iso?:string|null){return iso?Math.max(0,(Date.now()-Date.parse(iso))/3600000):Infinity}
export default function AdminOpsAssistant(){
  const [ops,setOps]=useState<Ops|null>(null),[feedback,setFeedback]=useState<Feedback[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const load=async()=>{setBusy(true);setMsg('');try{const [a,b]=await Promise.all([supabase.rpc('admin_ops_status_v1'),supabase.rpc('feedback_admin_list_v1',{p_limit:40})]);if(a.error)throw a.error;if(b.error)throw b.error;setOps(a.data as Ops);setFeedback((Array.isArray(b.data)?b.data:[]) as Feedback[])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[]);
  const signals=useMemo(()=>{if(!ops)return[];const out:Array<{level:'ok'|'warn'|'high';title:string;detail:string}>=[];const age=ageHours(ops.lastDailySnapshotAt);out.push(age>36?{level:'high',title:'Backup daily quá hạn',detail:`Bản daily gần nhất cách ${Math.round(age)} giờ. Ưu tiên backup Drive thủ công.`}:{level:'ok',title:'Backup daily trong ngưỡng',detail:`Bản gần nhất cách ${Math.round(age)} giờ.`});if(ops.recentErrors)out.push({level:'high',title:`${ops.recentErrors} lỗi trong 24 giờ`,detail:'Mở A.I Diagnostic để phân tích log trước khi dọn dữ liệu.'});else if(ops.recentWarnings)out.push({level:'warn',title:`${ops.recentWarnings} cảnh báo trong 24 giờ`,detail:'Theo dõi; chưa có lỗi mức error/critical.'});else out.push({level:'ok',title:'Không có lỗi hệ thống mới',detail:'Không ghi nhận error/critical 24 giờ gần đây.'});if(ops.pendingModeration)out.push({level:'warn',title:`${ops.pendingModeration} bài chờ kiểm duyệt`,detail:'MOD/Admin nên xử lý hàng đợi để tác giả nhận phản hồi.'});if(ops.openFeedback)out.push({level:'warn',title:`${ops.openFeedback} góp ý đang mở`,detail:'Có phản hồi người dùng cần Admin xem.'});return out},[ops]);
  const retention=async()=>{if(!window.confirm('Chạy retention an toàn theo chính sách hiện hành? Chỉ dữ liệu đã quá hạn mới bị xóa.'))return;setBusy(true);setMsg('');try{const {data,error}=await supabase.rpc('admin_run_retention_v1');if(error)throw error;setMsg(`Đã dọn dữ liệu hết hạn: ${JSON.stringify(data)}`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const resolve=async(id:string)=>{setBusy(true);try{const {error}=await supabase.rpc('feedback_admin_resolve_v1',{p_id:id,p_status:'resolved'});if(error)throw error;await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  return <section className="admin-ops-assistant panel"><div className="between"><div className="row"><BrainCircuit/><div><h3>Vận hành hệ thống · Quy tắc xác định</h3><p className="muted">Luật cảnh báo chạy xác định; A.I Diagnostic chỉ hỗ trợ phân tích, không tự xóa dữ liệu.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Làm mới</button></div>{msg&&<div className="ai-note" role="status">{msg}</div>}<div className="ops-signal-grid">{signals.map((s,i)=><article key={i} className={`ops-${s.level}`}>{s.level==='ok'?<CheckCircle2/>:<ShieldAlert/>}<div><b>{s.title}</b><small>{s.detail}</small></div></article>)}</div><div className="schedule-actions"><button className="secondary" disabled={busy} onClick={()=>void retention()}><Trash2/>Dọn dữ liệu hết hạn</button><span className="badge"><DatabaseBackup/> Backup Drive vẫn ưu tiên thủ công</span></div><div className="feedback-admin-list"><h4>Hộp góp ý từ A.I Mini</h4>{feedback.filter(x=>x.status!=='resolved').length===0&&<p className="muted">Không có góp ý đang mở.</p>}{feedback.filter(x=>x.status!=='resolved').map(x=><article key={x.id}><div><b>{x.kind==='bug'?'Báo lỗi':x.kind==='suggestion'?'Góp ý':'Phản hồi'} · {x.reporter_name}</b><small>{x.reporter_student_code} · {new Date(x.created_at).toLocaleString('vi-VN')}</small><p>{x.body}</p></div><button disabled={busy} onClick={()=>void resolve(x.id)}><CheckCircle2/>Đã xử lý</button></article>)}</div></section>;
}
