import {useEffect,useState} from 'react';
import {CheckCircle2,RefreshCcw,ShieldCheck,XCircle} from 'lucide-react';
import {getAnswerReviewQueue,resolveAnswerReview,type AnswerReviewRequest} from '../../services/dailyPracticeService';
import './answer-review.css';

export default function AnswerReviewQueue(){
  const [items,setItems]=useState<AnswerReviewRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[corrections,setCorrections]=useState<Record<string,number>>({});
  const load=async()=>setItems(await getAnswerReviewQueue(30));
  useEffect(()=>{void load().catch(()=>{})},[]);
  const act=async(item:AnswerReviewRequest,resolution:'confirmed'|'corrected'|'dismissed')=>{if(busy)return;setBusy(true);setMessage('');try{const next=corrections[item.requestId];if(resolution==='corrected'&&!Number.isInteger(next))throw new Error('Chọn đáp án A–D trước khi sửa.');await resolveAnswerReview(item.requestId,resolution,next,resolution==='corrected'?'Điều chỉnh theo kiểm tra của Ban Quản lý Học tập.':'Đã kiểm tra yêu cầu của sinh viên.');await load();setMessage(resolution==='corrected'?'Đã sửa đáp án và xác nhận lại câu hỏi.':resolution==='confirmed'?'Đã xác nhận đáp án hiện tại.':'Đã đóng báo cáo.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  return <section className="answer-review-box" aria-label="Báo đáp án sai">
    <div className="answer-review-head"><div><b>Báo đáp án sai</b><span className="badge">{items.length} chờ xử lý</span></div><button type="button" className="secondary answer-review-refresh" disabled={busy} onClick={()=>void load().catch(()=>{})} aria-label="Cập nhật báo cáo đáp án sai"><RefreshCcw/></button></div>
    {message&&<p className="qi-status" role="status">{message}</p>}
    {items.length===0?<p className="answer-review-empty">Không có báo cáo mới.</p>:<div className="qi-drafts answer-review-items">{items.map(item=><article key={item.requestId}><div className="answer-review-meta"><b>{item.subject} · {item.topic}</b><span>{item.requestCount} báo cáo</span></div><p>{item.stem}</p><ol type="A">{item.options.map((option,index)=><li key={index}>{option}{item.correctIndex===index?' ✓ hiện tại':''}</li>)}</ol><small>{item.sourceFileName}{item.reason?` · ${item.reason}`:''}</small><div className="qi-actions"><button disabled={busy} onClick={()=>void act(item,'confirmed')}><CheckCircle2/>Đúng</button><label className="answer-review-correct"><span>Sửa thành</span><select value={corrections[item.requestId]??''} disabled={busy} onChange={e=>setCorrections(current=>({...current,[item.requestId]:Number(e.target.value)}))}><option value="">A–D</option>{item.options.map((_,index)=><option key={index} value={index}>{String.fromCharCode(65+index)}</option>)}</select></label><button disabled={busy||!Number.isInteger(corrections[item.requestId])} onClick={()=>void act(item,'corrected')}><ShieldCheck/>Sửa & duyệt</button><button className="secondary" disabled={busy} onClick={()=>void act(item,'dismissed')}><XCircle/>Đóng</button></div></article>)}</div>}
  </section>;
}