import {useEffect,useState} from 'react';
import {CheckCircle2,RefreshCcw,ShieldCheck,XCircle} from 'lucide-react';
import {getAnswerReviewQueue,resolveAnswerReview,type AnswerReviewRequest} from '../../services/dailyPracticeService';
import './answer-review.css';

export default function AnswerReviewQueue(){
  const [items,setItems]=useState<AnswerReviewRequest[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[corrections,setCorrections]=useState<Record<string,number>>({});
  const load=async()=>setItems(await getAnswerReviewQueue(30));
  useEffect(()=>{void load().catch(()=>{})},[]);
  const act=async(item:AnswerReviewRequest,resolution:'confirmed'|'corrected'|'dismissed')=>{if(busy)return;setBusy(true);setMessage('');try{const next=corrections[item.requestId];if(resolution==='corrected'&&!Number.isInteger(next))throw new Error('Chọn đáp án A–D trước khi sửa.');await resolveAnswerReview(item.requestId,resolution,next,resolution==='corrected'?'Điều chỉnh theo kiểm tra của Ban Quản lý Học tập.':'Đã kiểm tra yêu cầu của sinh viên.');await load();setMessage(resolution==='corrected'?'Đã sửa đáp án và xác nhận lại câu hỏi.':resolution==='confirmed'?'Đã xác nhận đáp án hiện tại.':'Đã đóng yêu cầu kiểm tra.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  return <details className="publish-exceptions answer-review-queue"><summary>Yêu cầu kiểm tra đáp án ({items.length})</summary><div className="qi-drafts">{message&&<p className="qi-status" role="status">{message}</p>}{items.length===0&&<p className="muted">Chưa có yêu cầu kiểm tra đáp án từ sinh viên.</p>}{items.map(item=><article key={item.requestId}><b>{item.subject} · {item.topic}</b><p>{item.stem}</p><ol type="A">{item.options.map((option,index)=><li key={index}>{option}{item.correctIndex===index?' ✓ hiện tại':''}</li>)}</ol><small>Nguồn: {item.sourceFileName} · {item.requestCount} yêu cầu · {item.reason||'Không ghi lý do'}</small><div className="qi-actions"><button disabled={busy} onClick={()=>void act(item,'confirmed')}><CheckCircle2/>Xác nhận đáp án</button><label className="answer-review-correct"><span>Sửa thành</span><select value={corrections[item.requestId]??''} disabled={busy} onChange={e=>setCorrections(current=>({...current,[item.requestId]:Number(e.target.value)}))}><option value="">A–D</option>{item.options.map((_,index)=><option key={index} value={index}>{String.fromCharCode(65+index)}</option>)}</select></label><button disabled={busy||!Number.isInteger(corrections[item.requestId])} onClick={()=>void act(item,'corrected')}><ShieldCheck/>Sửa & duyệt</button><button className="secondary" disabled={busy} onClick={()=>void act(item,'dismissed')}><XCircle/>Đóng yêu cầu</button></div></article>)}</div><button type="button" className="secondary" disabled={busy} onClick={()=>void load().catch(()=>{})}><RefreshCcw/>Tải lại yêu cầu</button></details>;
}
