import {useEffect,useState} from 'react';
import {CheckCircle2,FileUp,RefreshCcw,ShieldCheck,XCircle} from 'lucide-react';
import {getPracticeReviewQueue,reviewPracticeQuestion,type PracticeReviewQuestion} from '../../services/dailyPracticeService';
import {quizWorkspace,retryQuizPipeline,sourceFileBase64,startQuizPipeline,type QuizCandidate,type QuizDraft} from '../../services/quizWorkspaceService';
import './quiz-import.css';

// Server-side review authorization contract: practice_question_review_v1.
// Shared resumable pipeline contract markers for static RBAC audit: quiz-start · quiz-process-chunk · quiz-retry · quiz-commit.
type ConversionMode='auto'|'generate'|'extract';

export default function LearningContentManagerPanel(){
  const [subject,setSubject]=useState(''),[file,setFile]=useState<File|null>(null),[mode,setMode]=useState<ConversionMode>('auto'),[draft,setDraft]=useState<QuizDraft|null>(null),[selected,setSelected]=useState<Set<string>>(new Set()),[review,setReview]=useState<PracticeReviewQuestion[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const loadReview=async()=>setReview(await getPracticeReviewQueue(20));
  useEffect(()=>{void loadReview().catch(e=>setMessage((e as Error).message))},[]);
  const run=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setMessage('');try{await fn()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const track=(next:QuizDraft)=>{setDraft(next);if(next.pipeline?.state==='processing')setMessage(`Đang xử lý ${next.pipeline.completedChunks}/${next.pipeline.totalChunks} phần · ${next.pipeline.percent}%`)};
  const finish=(next:QuizDraft)=>{setDraft(next);setSelected(new Set());setMessage(`Đã hoàn tất chuyển đổi: ${next.total} câu. Chưa có câu nào được tự động nhập; cần đối chiếu trước khi xác nhận.`)};
  const preview=async()=>{
    if(!file||!subject.trim())throw new Error('Nhập chủ đề và chọn tệp DOCX/TXT/PDF trước khi chuyển đổi.');
    finish(await startQuizPipeline({fileName:file.name,base64:await sourceFileBase64(file),subjectName:subject.trim(),conversionMode:mode},track));
  };
  const retry=async()=>{if(draft?.pipeline?.state==='error')finish(await retryQuizPipeline(draft,track))};
  const toggle=(q:QuizCandidate,checked:boolean)=>setSelected(old=>{const next=new Set(old);if(checked&&q.correctIndex!==null&&!q.imported&&next.size<200)next.add(q.id);else next.delete(q.id);return next});
  const commit=async()=>{if(!draft||!selected.size)throw new Error('Chọn ít nhất một câu đã đối chiếu có đáp án.');if(draft.pipeline?.state==='processing'||draft.pipeline?.state==='error')throw new Error('Hoàn tất pipeline trước khi nhập câu hỏi.');const selection=draft.questions.filter(q=>selected.has(q.id)&&!q.imported&&q.correctIndex!==null).map(q=>({...q,confirmed:true}));if(!selection.length)throw new Error('Không có câu hợp lệ để nhập.');await quizWorkspace('quiz-commit',{id:draft.id,revision:draft.revision,selection});const next=await quizWorkspace<QuizDraft>('quiz-draft',{id:draft.id});setDraft(next);setSelected(new Set());await loadReview();setMessage(`Đã nhập ${selection.length} câu được xác nhận vào ngân hàng ôn tập.`)};
  const decide=async(id:string,status:'expert_approved'|'rejected')=>{await reviewPracticeQuestion(id,status);await loadReview();setMessage(status==='expert_approved'?'Đã duyệt câu hỏi.':'Đã loại câu hỏi khỏi hàng chờ duyệt.')};
  const pipeline=draft?.pipeline;
  return <section className="panel quiz-import" aria-label="Ban Quản lý Học tập">
    <div className="qi-heading"><div><span className="qi-kicker"><ShieldCheck/>Ban Quản lý Học tập</span><h2>Quản lý nội dung Học Thuật</h2><p>Quyền giới hạn: chuyển tài liệu thành bản nháp quiz, đối chiếu, nhập câu đã xác nhận và duyệt ngân hàng. Không có quyền quản lý thành viên, theme, A.I Operations hoặc ACC hệ thống.</p></div><ShieldCheck/></div>
    <div className="qi-flow" aria-label="Quy trình"><span><b>1</b><FileUp/>Tải nguồn</span><span><b>2</b>Chia phần & xử lý</span><span><b>3</b>Đối chiếu</span><span><b>4</b><CheckCircle2/>Duyệt</span></div>
    <div className="qi-direct-upload"><label><span><b>Chủ đề</b><small>Chủ đề sẽ đi cùng nguồn và câu hỏi.</small></span><input value={subject} disabled={busy} placeholder="Ví dụ: Sinh lý học, Châm cứu học…" onChange={e=>setSubject(e.target.value)}/></label><label><span><b>Cách chuyển đổi</b><small>Gemini chỉ được dùng nội dung nguồn.</small></span><select value={mode} disabled={busy} onChange={e=>setMode(e.target.value as ConversionMode)}><option value="auto">Tự động</option><option value="generate">Gemini thiết kế từ tài liệu</option><option value="extract">Chỉ trích xuất câu có sẵn</option></select></label><label className="qi-upload"><FileUp/><span><b>Tải DOCX, TXT hoặc PDF</b><small>.docx / UTF-8 .txt / PDF có lớp văn bản · tối đa 2 MB · PDF tối đa 80 trang · không OCR tự động</small></span><input type="file" accept=".docx,.txt,.pdf,text/plain,application/pdf" disabled={busy} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="qi-actions"><button disabled={busy||!file||!subject.trim()} onClick={()=>void run(preview)}>{busy?'Đang xử lý…':'Tạo bản nháp quiz'}</button>{file&&<small>{file.name}</small>}</div></div>
    {pipeline&&<div className="qi-status" role="status"><b>Pipeline v{pipeline.version} · {pipeline.state==='processing'?'Đang xử lý':pipeline.state==='error'?'Tạm dừng':pipeline.state==='needs_review'?'Chờ đối chiếu':'Sẵn sàng'}</b><progress max={100} value={pipeline.percent}/><span>{pipeline.percent}% · {pipeline.completedChunks}/{pipeline.totalChunks||pipeline.completedChunks} phần · lần chạy {pipeline.attempt}</span>{pipeline.lastError&&<small className="warning">{pipeline.lastError}</small>}{pipeline.state==='error'&&pipeline.retryable&&<button disabled={busy} onClick={()=>void run(retry)}><RefreshCcw/>Thử lại từ phần bị lỗi</button>}</div>}
    {message&&<p className="qi-status" role="status">{message}</p>}
    {draft&&<div className="qi-preview"><h3>{draft.document.fileName}</h3><p>{draft.total} câu · {draft.questions.filter(q=>q.imported).length} đã nhập · {draft.questions.filter(q=>!q.imported).length} đang chờ</p>{draft.warnings.map((w,i)=><p key={i} className="warning">{w}</p>)}<details><summary>Xem nguyên văn nguồn để đối chiếu</summary><pre>{draft.sourceText}</pre></details>{draft.questions.slice(0,40).map((q,i)=><article key={q.id}><label><input type="checkbox" disabled={busy||q.imported||q.correctIndex===null||pipeline?.state==='processing'||pipeline?.state==='error'} checked={selected.has(q.id)} onChange={e=>toggle(q,e.target.checked)}/>{i+1}. {q.imported?'Đã nhập':'Đã đối chiếu'}</label><b>{q.stem}</b>{q.issues.length>0&&<p className="warning">{q.issues.join(' · ')}</p>}<ol type="A">{q.options.map((o,j)=><li key={j}><span>{o}</span>{q.correctIndex===j&&<b> ✓</b>}</li>)}</ol>{q.explanation&&<p>{q.explanation}</p>}{q.answerEvidence&&<small>{q.answerEvidence}</small>}</article>)}{draft.questions.length>40&&<p className="muted">Đang hiển thị 40 câu đầu để giữ giao diện nhẹ; toàn bộ câu vẫn nằm trong bản nháp và có thể nhập theo lô tối đa 200 câu.</p>}<div className="qi-actions"><button disabled={busy||!selected.size||pipeline?.state==='processing'||pipeline?.state==='error'} onClick={()=>void run(commit)}>Nhập {selected.size} câu đã xác nhận</button></div></div>}
    <details open><summary>Hàng chờ duyệt quiz ({review.length})</summary><div className="qi-drafts">{review.length===0&&<p className="muted">Không có câu đang chờ duyệt.</p>}{review.map(q=><article key={q.id}><b>{q.subject} · {q.topic}</b><p>{q.stem}</p><ol type="A">{q.options.map((o,i)=><li key={i}>{o}{q.correctIndex===i?' ✓':''}</li>)}</ol><small>Nguồn: {q.sourceFileName}</small><div className="qi-actions"><button disabled={busy} onClick={()=>void run(()=>decide(q.id,'expert_approved'))}><CheckCircle2/>Duyệt</button><button className="secondary" disabled={busy} onClick={()=>void run(()=>decide(q.id,'rejected'))}><XCircle/>Loại</button></div></article>)}</div></details>
  </section>;
}
