import { useState } from 'react';
import * as XLSX from 'xlsx';
import { Download,FileSpreadsheet,Upload } from 'lucide-react';
import { supabase } from '../../services/authService';

type InputRow={mssv:string;ho_ten:string;lop:string;contact:string;ban:string};
type ResultRow=InputRow&{row:number;username?:string;temporary_password?:string;reason?:string;existing_name?:string};
type ImportResult={summary:{input:number;created:number;duplicates:number;invalid:number;failed:number};created:ResultRow[];duplicates:ResultRow[];errors:ResultRow[];failed:ResultRow[]};
const fold=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const text=(v:unknown,max=180)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const aliases={mssv:['mssv','ma_sinh_vien','student_code'],name:['ho_va_ten','ho_ten','full_name'],className:['lop','class','class_name'],contact:['sdt_email','so_dien_thoai_email','email','sdt','phone'],department:['chi_hoi_ban','ban','chi_hoi','department']};
const find=(row:unknown[],names:string[])=>row.findIndex(v=>names.includes(fold(v)));
function parse(buffer:ArrayBuffer):InputRow[]{const wb=XLSX.read(buffer,{type:'array',cellFormula:false,cellHTML:false,cellStyles:false});const name=wb.SheetNames[0];if(!name)throw new Error('Workbook không có sheet.');const matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[name],{header:1,defval:'',raw:false});let header=-1,map={mssv:-1,name:-1,className:-1,contact:-1,department:-1};for(let i=0;i<Math.min(matrix.length,50);i++){const row=matrix[i]||[];const next={mssv:find(row,aliases.mssv),name:find(row,aliases.name),className:find(row,aliases.className),contact:find(row,aliases.contact),department:find(row,aliases.department)};if(next.mssv>=0&&next.name>=0){header=i;map=next;break}}if(header<0)throw new Error('Không tìm thấy cột MSSV và Họ và tên.');const rows:InputRow[]=[];for(let i=header+1;i<matrix.length;i++){const row=matrix[i]||[];const item={mssv:text(row[map.mssv],20).replace(/\s/g,'').toUpperCase(),ho_ten:text(row[map.name]),lop:map.className>=0?text(row[map.className],80):'',contact:map.contact>=0?text(row[map.contact]):'',ban:map.department>=0?text(row[map.department],120):''};if(!item.mssv&&!item.ho_ten)continue;rows.push(item);if(rows.length>1000)throw new Error('Tối đa 1.000 thành viên mỗi lần nhập.')}if(!rows.length)throw new Error('Không có dữ liệu thành viên.');return rows}
function csvEscape(v:unknown){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadReport(result:ImportResult){const header=['Trạng thái','MSSV','Họ và tên','Lớp','Liên hệ','Chi hội/Ban','Username','Mật khẩu tạm','Ghi chú'];const data=[...result.created.map(x=>['Tạo mới',x]),...result.duplicates.map(x=>['Trùng',x]),...result.errors.map(x=>['Không hợp lệ',x]),...result.failed.map(x=>['Lỗi tạo',x])];const lines=[header.join(','),...data.map(([status,raw])=>{const x=raw as ResultRow;return [status,x.mssv,x.ho_ten,x.lop,x.contact,x.ban,x.username||'',x.temporary_password||'',x.reason||x.existing_name||''].map(csvEscape).join(',')})];const blob=new Blob(['\uFEFF'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`member-import-report-${new Date().toISOString().slice(0,10)}.csv`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}

export default function MemberBulkImport(){
  const [fileName,setFileName]=useState(''),[rows,setRows]=useState<InputRow[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[result,setResult]=useState<ImportResult|null>(null);
  const read=async(file:File)=>{setBusy(true);setMsg('');setResult(null);try{if(!/\.(xlsx|xls)$/i.test(file.name))throw new Error('Chỉ hỗ trợ Excel .xlsx hoặc .xls.');if(file.size<=0||file.size>8*1024*1024)throw new Error('File tối đa 8 MB.');const parsed=parse(await file.arrayBuffer());setRows(parsed);setFileName(file.name);setMsg(`Đã đọc ${parsed.length} dòng. Hệ thống sẽ đối chiếu MSSV với dữ liệu thật trước khi tạo tài khoản.`)}catch(e){setRows([]);setFileName('');setMsg((e as Error).message)}finally{setBusy(false)}};
  const commit=async()=>{if(!rows.length||busy)return;setBusy(true);setMsg('');try{const {data,error}=await supabase.functions.invoke('member-bulk-import',{body:{file_name:fileName,rows}});if(error)throw error;const r=data as ImportResult;if(!r?.summary)throw new Error('Phản hồi import không hợp lệ.');setResult(r);setMsg(`Hoàn tất: ${r.summary.created} tạo mới · ${r.summary.duplicates} trùng · ${r.summary.invalid} không hợp lệ · ${r.summary.failed} lỗi.`)}catch(e){setMsg((e as Error).message||'Không thể nhập thành viên.')}finally{setBusy(false)}};
  return <section className="moderation-card member-bulk-import"><div className="between"><div><h3>Bulk Import thành viên</h3><p className="muted">Excel: MSSV · Họ và tên · Lớp · SĐT/Email · Chi hội/Ban. Tài khoản mới dùng username=MSSV và mật khẩu tạm ngẫu nhiên.</p></div><FileSpreadsheet/></div><label className="upload-zone"><input hidden type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void read(f);e.currentTarget.value=''}}/><Upload/>Chọn file Excel</label>{msg&&<div className="ai-note" role="status">{msg}</div>}{rows.length>0&&<><div className="data-list compact"><article><div><b>{fileName}</b><small>{rows.length} dòng sẵn sàng kiểm tra server-side</small></div><span className="badge">Preview</span></article>{rows.slice(0,5).map((x,i)=><article key={`${x.mssv}-${i}`}><div><b>{x.mssv} · {x.ho_ten}</b><small>{x.lop||'Chưa có lớp'} · {x.ban||'Chưa gán ban'}</small></div></article>)}</div><div className="schedule-actions"><button disabled={busy} onClick={()=>void commit()}>{busy?'Đang xử lý…':'Lọc trùng & tạo tài khoản'}</button><button className="secondary" disabled={busy} onClick={()=>{setRows([]);setResult(null);setFileName('');setMsg('')}}>Xóa file</button></div></>}{result&&<div className="schedule-actions"><button className="secondary" onClick={()=>downloadReport(result)}><Download/>Tải báo cáo CSV</button></div>}</section>;
}
