import { useState } from 'react';
import { Download,FileSpreadsheet,Upload } from 'lucide-react';
import * as XLSX from 'xlsx';
import { SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL,supabase } from '../../services/authService';

type Row={mssv:string;ho_ten:string;lop:string;contact:string;ban:string};
type ResultRow=Row&{row?:number;reason?:string;existing_name?:string;username?:string;temporary_password?:string};
type ImportResult={summary:{input:number;created:number;duplicates:number;invalid:number;failed:number};created:ResultRow[];duplicates:ResultRow[];errors:ResultRow[];failed:ResultRow[]};
const key=(s:unknown)=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
function find(headers:unknown[],aliases:string[]){return headers.findIndex(v=>aliases.includes(key(v)))}
function parse(buffer:ArrayBuffer){const wb=XLSX.read(buffer,{type:'array'}),name=wb.SheetNames[0];if(!name)throw new Error('Workbook không có sheet.');const matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[name],{header:1,defval:'',raw:false});if(!matrix.length)throw new Error('File trống.');let header=-1,map={mssv:-1,name:-1,lop:-1,contact:-1,ban:-1};for(let i=0;i<Math.min(40,matrix.length);i++){const h=matrix[i];const next={mssv:find(h,['mssv','ma_sinh_vien','student_code']),name:find(h,['ho_va_ten','ho_ten','full_name']),lop:find(h,['lop','class','class_name']),contact:find(h,['sdt_email','sd_t_email','email','sdt','phone','contact']),ban:find(h,['chi_hoi_ban','chi_hoi','ban','department','organizational_unit'])};if(next.mssv>=0&&next.name>=0){header=i;map=next;break}}if(header<0)throw new Error('Thiếu cột MSSV và Họ và tên.');const rows:Row[]=[];for(let i=header+1;i<matrix.length;i++){const r=matrix[i],m=String(r[map.mssv]??'').replace(/\s/g,'').trim();const n=String(r[map.name]??'').replace(/\s+/g,' ').trim();if(!m&&!n)continue;rows.push({mssv:m,ho_ten:n,lop:map.lop>=0?String(r[map.lop]??'').trim():'',contact:map.contact>=0?String(r[map.contact]??'').trim():'',ban:map.ban>=0?String(r[map.ban]??'').trim():''});if(rows.length>1000)throw new Error('Tối đa 1.000 thành viên mỗi lần nhập.')}if(!rows.length)throw new Error('Không có dữ liệu thành viên.');return rows}
function csvCell(v:unknown){const s=String(v??'');return `"${s.replace(/"/g,'""')}"`}
function download(result:ImportResult){const lines=[['Trạng thái','MSSV','Họ và tên','Lớp','Liên hệ','Chi hội/Ban','Username','Mật khẩu tạm','Ghi chú'].map(csvCell).join(',')];const add=(status:string,rows:ResultRow[])=>rows.forEach(r=>lines.push([status,r.mssv,r.ho_ten,r.lop,r.contact,r.ban,r.username||'',r.temporary_password||'',r.reason||r.existing_name||''].map(csvCell).join(',')));add('Tạo mới',result.created);add('Trùng - bỏ qua',result.duplicates);add('Không hợp lệ',result.errors);add('Lỗi',result.failed);const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bao-cao-bulk-thanh-vien-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}

export default function MemberBulkImport(){const [fileName,setFileName]=useState(''),[rows,setRows]=useState<Row[]>([]),[result,setResult]=useState<ImportResult|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');const choose=async(file:File|null)=>{setRows([]);setResult(null);setMsg('');if(!file)return;try{if(!/\.(xlsx|xls|csv)$/i.test(file.name))throw new Error('Chỉ hỗ trợ .xlsx, .xls, .csv.');if(file.size>8*1024*1024)throw new Error('File tối đa 8 MB.');setRows(parse(await file.arrayBuffer()));setFileName(file.name)}catch(e){setMsg((e as Error).message)}};const commit=async()=>{if(!rows.length)return;setBusy(true);setMsg('');try{const {data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Phiên đăng nhập đã hết hạn.');const response=await fetch(`${SUPABASE_URL}/functions/v1/member-bulk-import`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({file_name:fileName,rows})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Nhập thành viên thất bại.');setResult(body as ImportResult);setMsg('Import hoàn tất. Mật khẩu tạm chỉ hiển thị trong báo cáo phiên này; hãy tải file và bàn giao an toàn cho thành viên.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};return <section className="member-bulk-import moderation-card"><div className="row panel-title"><FileSpreadsheet/><div><h3>Bulk Import thành viên</h3><p>MSSV · Họ và tên · Lớp · SĐT/Email · Chi hội/Ban</p></div></div><label className="bulk-drop"><Upload/><span><b>Chọn file Excel</b><small>.xlsx / .xls / .csv · tối đa 1.000 dòng</small></span><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>void choose(e.target.files?.[0]||null)}/></label>{rows.length>0&&<div className="bulk-preview"><b>{fileName}</b><span>{rows.length.toLocaleString('vi-VN')} dòng sẵn sàng đối chiếu MSSV.</span><button disabled={busy} onClick={()=>void commit()}>{busy?'Đang tạo tài khoản…':'Lọc trùng & tạo tài khoản'}</button></div>}{result&&<><div className="bulk-summary"><span><b>{result.summary.created}</b>Tạo mới</span><span><b>{result.summary.duplicates}</b>Trùng</span><span><b>{result.summary.invalid}</b>Không hợp lệ</span><span><b>{result.summary.failed}</b>Lỗi</span></div><button className="secondary" onClick={()=>download(result)}><Download/>Tải báo cáo kết quả CSV</button>{result.duplicates.length>0&&<details><summary>Danh sách MSSV trùng ({result.duplicates.length})</summary><div className="bulk-duplicates">{result.duplicates.slice(0,100).map((r,i)=><div key={`${r.mssv}-${i}`}><b>{r.mssv}</b><span>{r.ho_ten} → đã có: {r.existing_name}</span></div>)}</div></details>}</>}{msg&&<div className="ai-note" role="status">{msg}</div>}</section>}
