import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2,Eye,EyeOff,RefreshCw,Search,ShieldAlert,ShieldCheck,XCircle} from 'lucide-react';
import type {Member} from '../../types';
import {roleAtLeast} from '../../types';
import {supabase} from '../../services/authService';

type WorkType='academic'|'news'|'feedback';
type WorkRow={entity_type:WorkType;entity_id:string;title:string;subtitle:string;status:string;created_at:string;payload:Record<string,unknown>;is_seen:boolean};
const LABELS:Record<WorkType,string>={academic:'Bài thành viên chờ duyệt',news:'Tin tức cần xử lý',feedback:'Góp ý / Báo lỗi'};
const needsSource=(row:WorkRow)=>['research','news','reference'].includes(String(row.payload?.post_type||''));
const citationCount=(row:WorkRow)=>Array.isArray(row.payload?.citations)?row.payload.citations.length:0;

export default function ModerationOpsPanel({member}:{member:Member|null}){
  const allowed=roleAtLeast(member?.role,'mod'),canAdmin=roleAtLeast(member?.role,'admin');
  const [items,setItems]=useState<WorkRow[]>([]),[q,setQ]=useState(''),[date,setDate]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const searching=Boolean(q.trim()||date);
  const load=async()=>{if(!allowed)return;setBusy(true);setMsg('');try{const {data,error}=await supabase.rpc('moderation_workbench_v2',{p_query:q.trim(),p_on_date:date||null});if(error)throw error;setItems((Array.isArray(data)?data:[]) as WorkRow[])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{if(!allowed)return;const t=window.setTimeout(()=>void load(),q||date?260:0);return()=>window.clearTimeout(t)},[allowed,q,date]);
  const groups=useMemo(()=>({academic:items.filter(x=>x.entity_type==='academic'),news:items.filter(x=>x.entity_type==='news'),feedback:items.filter(x=>x.entity_type==='feedback')}),[items]);
  const markSeen=async(row:WorkRow,seen=true)=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('moderation_mark_seen_v1',{p_entity_type:row.entity_type,p_entity_id:row.entity_id,p_seen:seen});if(error)throw error;await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const reviewAcademic=async(row:WorkRow,action:'approved'|'rejected'|'quarantined')=>{if(action==='approved'&&needsSource(row)&&citationCount(row)===0){setMsg('Loại bài này bắt buộc có nguồn trước khi duyệt.');return}setBusy(true);setMsg('');try{const {error}=await supabase.rpc('moderate_academic_post_v1',{p_post_id:row.entity_id,p_action:action});if(error)throw error;setMsg(action==='approved'?'Đã duyệt bài.':action==='quarantined'?'Đã cô lập bài.':'Đã từ chối bài.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const reviewNews=async(row:WorkRow,status:'published'|'rejected')=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('tcm_news_review_v1',{p_id:row.entity_id,p_status:status});if(error)throw error;await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const resolveFeedback=async(row:WorkRow)=>{if(!canAdmin)return;setBusy(true);setMsg('');try{const {error}=await supabase.rpc('feedback_admin_resolve_v1',{p_id:row.entity_id,p_status:'resolved'});if(error)throw error;await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const renderBlock=(type:WorkType)=>{if(type==='feedback'&&!canAdmin)return null;const rows=groups[type];return <section className="moderation-card work-block" key={type}><div className="between"><div><h4>{LABELS[type]}</h4><p className="muted">{searching?'Kết quả tra cứu theo từ khóa/ngày.':'Tối đa 5 nội dung chưa xem trong mỗi lần hiển thị.'}</p></div><span className="badge">{rows.length}</span></div><div className="work-block-list">{rows.map(row=><article key={`${type}-${row.entity_id}`} className={row.is_seen?'is-seen':''}><div className="work-block-copy"><b>{row.title}</b><small>{row.subtitle} · {new Date(row.created_at).toLocaleString('vi-VN')} · {row.status}</small>{type==='academic'&&<div className="review-badges"><span>{String(row.payload.post_type||'reference')}</span><span className={needsSource(row)&&!citationCount(row)?'source-bad':'source-ok'}>{citationCount(row)} nguồn</span></div>}{type==='feedback'&&<p>{String(row.payload.body||'')}</p>}</div><div className="schedule-actions work-actions">{type==='academic'&&row.status==='pending'&&<><button disabled={busy||(needsSource(row)&&citationCount(row)===0)} onClick={()=>void reviewAcademic(row,'approved')}><CheckCircle2/>Duyệt</button><button className="secondary" disabled={busy} onClick={()=>void reviewAcademic(row,'quarantined')}><ShieldAlert/>Cô lập</button><button className="danger-btn" disabled={busy} onClick={()=>void reviewAcademic(row,'rejected')}><XCircle/>Từ chối</button></>}{type==='news'&&row.status==='pending'&&<><button disabled={busy} onClick={()=>void reviewNews(row,'published')}><CheckCircle2/>Duyệt</button><button className="danger-btn" disabled={busy} onClick={()=>void reviewNews(row,'rejected')}><XCircle/>Từ chối</button></>}{type==='feedback'&&canAdmin&&!['resolved','closed'].includes(row.status)&&<button disabled={busy} onClick={()=>void resolveFeedback(row)}><CheckCircle2/>Đã xử lý</button>}<button className="secondary" disabled={busy} onClick={()=>void markSeen(row,!row.is_seen)}>{row.is_seen?<><Eye/>Hiện lại</>:<><EyeOff/>Đã xem</>}</button></div></article>)}{rows.length===0&&<p className="muted">{searching?'Không tìm thấy nội dung phù hợp.':'Khối này hiện không có việc chưa xem.'}</p>}</div></section>};
  if(!allowed)return null;
  return <section className="moderation-ops"><div className="between moderation-ops-heading"><div className="row panel-title"><ShieldCheck/><div><h3>Bàn công việc MOD / Admin</h3><p>Mỗi khối chỉ hiện 5 việc chưa xem. Duyệt hoặc đánh dấu đã xem sẽ ẩn khỏi bàn làm việc.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Làm mới</button></div>
    <div className="moderation-searchbar"><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm lại nội dung đã ẩn / đã duyệt…"/></div><label>Ngày<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{searching&&<button className="secondary" onClick={()=>{setQ('');setDate('')}}>Xóa lọc</button>}</div>
    {msg&&<div className="ai-note" role="status">{msg}</div>}
    <div className="moderation-work-grid">{renderBlock('academic')}{renderBlock('news')}{renderBlock('feedback')}</div>
  </section>;
}
