import { useEffect,useState } from 'react';
import { CheckCircle2,RefreshCw,ScrollText,ShieldCheck,XCircle,ShieldAlert } from 'lucide-react';
import type { Member } from '../../types';
import { roleAtLeast } from '../../types';
import { supabase } from '../../services/authService';

type NewsRow={id:string;title:string;publisher?:string|null;published_at?:string|null;status:'pending'|'published'|'rejected';trust_score:number;is_pinned:boolean};
type AcademicQueueRow={id:string;title:string;author_name:string;created_at:string;citations:unknown[];tags:string[];post_type:string;specialty:string;visibility:string;synthetic_flags:string[]};
type AuditRow={id:string;action:string;entity_type?:string|null;entity_id?:string|null;severity:string;metadata:Record<string,unknown>;created_at:string};
type SemesterRow={id:string;code:string;title:string;lock_at?:string|null;locked_at?:string|null;is_locked:boolean};

export default function ModerationOpsPanel({member}:{member:Member|null}){
  const allowed=roleAtLeast(member?.role,'mod');
  const [news,setNews]=useState<NewsRow[]>([]),[academic,setAcademic]=useState<AcademicQueueRow[]>([]),[logs,setLogs]=useState<AuditRow[]>([]),[semesters,setSemesters]=useState<SemesterRow[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const load=async()=>{if(!allowed)return;setBusy(true);setMsg('');try{const [newsResult,academicResult,logResult,semesterResult]=await Promise.all([supabase.rpc('tcm_news_admin_list_v1',{p_limit:30}),supabase.rpc('academic_moderation_queue_v1',{p_limit:100}),supabase.rpc('moderation_recent_logs_v1',{p_limit:60}),supabase.rpc('drl_semester_list_v1')]);for(const result of [newsResult,academicResult,logResult,semesterResult])if(result.error)throw result.error;setNews(Array.isArray(newsResult.data)?newsResult.data as NewsRow[]:[]);setAcademic(Array.isArray(academicResult.data)?academicResult.data as AcademicQueueRow[]:[]);setLogs(Array.isArray(logResult.data)?logResult.data as AuditRow[]:[]);setSemesters(Array.isArray(semesterResult.data)?semesterResult.data as SemesterRow[]:[])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{void load()},[allowed]);
  const reviewNews=async(item:NewsRow,status:'published'|'rejected')=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('tcm_news_review_v1',{p_id:item.id,p_status:status});if(error)throw error;await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const reviewAcademic=async(item:AcademicQueueRow,action:'approved'|'rejected'|'quarantined')=>{setBusy(true);setMsg('');try{if(action==='approved'&&(!Array.isArray(item.citations)||item.citations.length===0))throw new Error('Không thể duyệt bài chưa có nguồn.');const {error}=await supabase.rpc('moderate_academic_post_v1',{p_post_id:item.id,p_action:action});if(error)throw error;setMsg(action==='approved'?'Đã duyệt bài và xác minh nguồn.':action==='quarantined'?'Đã cô lập bài nghi ngờ synthetic/test.':'Đã từ chối bài.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  if(!allowed)return null;
  return <section className="moderation-ops"><div className="between moderation-ops-heading"><div className="row panel-title"><ShieldCheck/><div><h3>Hàng đợi kiểm duyệt</h3><p>Bài thành viên tách biệt hoàn toàn khỏi tin RSS tự động.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Làm mới</button></div>{msg&&<div className="ai-note" role="status">{msg}</div>}
    <section className="moderation-card"><h4>Bài học thuật chờ duyệt · {academic.length}</h4><div className="academic-review-list">{academic.map(item=><article key={item.id}><div className="academic-review-copy"><b>{item.title}</b><small>{item.author_name} · {new Date(item.created_at).toLocaleString('vi-VN')}</small><div className="review-badges"><span>{item.post_type}</span><span>{item.specialty}</span><span>{item.visibility}</span><span className={item.citations?.length?'source-ok':'source-bad'}>{item.citations?.length||0} nguồn</span>{item.synthetic_flags?.map(flag=><span className="source-bad" key={flag}>{flag}</span>)}</div></div><div className="schedule-actions"><button disabled={busy||!item.citations?.length} onClick={()=>void reviewAcademic(item,'approved')}><CheckCircle2/>Duyệt</button><button className="secondary" disabled={busy} onClick={()=>void reviewAcademic(item,'quarantined')}><ShieldAlert/>Cô lập</button><button className="danger-btn" disabled={busy} onClick={()=>void reviewAcademic(item,'rejected')}><XCircle/>Từ chối</button></div></article>)}{academic.length===0&&<p className="muted">Không có bài học thuật chờ duyệt.</p>}</div></section>
    <div className="moderation-grid"><section className="moderation-card"><h4>Tin tự động</h4><p className="muted">RSS/Google News YHCT được pipeline tin cậy tự gán published và không vào queue bài thành viên.</p><div className="news-review-list">{news.filter(x=>x.status==='pending').slice(0,5).map(item=><article key={item.id}><div><b>{item.title}</b><small>{item.publisher||'Nguồn tổng hợp'} · {Math.round(Number(item.trust_score||0)*100)}%</small></div><div className="schedule-actions"><button disabled={busy} onClick={()=>void reviewNews(item,'published')}><CheckCircle2/>Duyệt ngoại lệ</button><button className="danger-btn" disabled={busy} onClick={()=>void reviewNews(item,'rejected')}><XCircle/>Từ chối</button></div></article>)}{news.every(x=>x.status!=='pending')&&<p className="muted">Không có tin ngoại lệ chờ duyệt.</p>}</div></section><section className="moderation-card"><h4>Học kỳ DRL</h4><div className="data-list compact">{semesters.slice(0,8).map(s=><article key={s.id}><div><b>{s.title}</b><small>{s.code}</small></div><span className="badge">{s.is_locked?'Đã khóa':'Đang mở'}</span></article>)}</div></section></div>
    <section className="moderation-card moderation-log-card"><div className="row"><ScrollText/><h4>Log kiểm duyệt</h4></div><div className="log-list">{logs.slice(0,24).map(row=><article key={row.id} className={`log-${row.severity}`}><div><b>{row.action}</b><small>{new Date(row.created_at).toLocaleString('vi-VN')} · {row.entity_type||'system'} {row.entity_id||''}</small></div><span>{row.severity}</span></article>)}</div></section>
  </section>;
}
