import {useEffect,useState} from 'react';
import {Activity,BrainCircuit,CheckCircle2,CloudSun,DatabaseBackup,Download,Pencil,Pin,RefreshCw,RotateCcw,ShieldAlert,Trash2,XCircle} from 'lucide-react';
import {SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL,supabase} from '../../services/authService';
import {formatLunar} from '../../utils/lunar';
import {TaijiIcon} from '../icons/YhctIcons';

type Snapshot={id:string;scope:string;checksum_sha256:string;row_counts:Record<string,number>;created_at:string};
type Audit={id:string;action:string;severity:string;entity_type?:string|null;entity_id?:string|null;metadata:Record<string,unknown>;created_at:string};
type Health={ok:boolean;serverTime:string;postgres:string;counts:Record<string,number>;recentErrors:unknown[]};
type Weather={available:boolean;temperature?:number;apparentTemperature?:number;humidity?:number;windSpeed?:number;condition?:string;locationMode?:string};
type Semester={id:string;code:string;title:string;lock_at?:string|null;locked_at?:string|null;is_locked:boolean};
type AdminNews={id:string;title:string;summary:string;publisher?:string|null;published_at?:string|null;status:'pending'|'published'|'rejected';trust_score:number;is_pinned:boolean;canonical_url:string};

const MAX_BLOCK_ITEMS=5;
const downloadJson=(name:string,data:unknown)=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
const localDateTime=(iso?:string|null)=>{if(!iso)return'';const d=new Date(iso),pad=(n:number)=>String(n).padStart(2,'0');return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`};
const edgeUrl=(slug:string)=>`${SUPABASE_URL}/functions/v1/${slug}`;
const BlockTitle=({title}:{title:string})=><div className="between admin-v6-block-title"><h3>{title}</h3><span className="badge">5 gần nhất</span></div>;

export default function SystemAdminCenter(){
  const [health,setHealth]=useState<Health|null>(null),[snaps,setSnaps]=useState<Snapshot[]>([]),[logs,setLogs]=useState<Audit[]>([]),[weather,setWeather]=useState<Weather|null>(null),[semesters,setSemesters]=useState<Semester[]>([]),[adminNews,setAdminNews]=useState<AdminNews[]>([]),[diag,setDiag]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const now=new Date();
  const load=async()=>{setBusy(true);setMsg('');try{const [h,s,l,drl,news]=await Promise.all([supabase.rpc('acc_health_v1'),supabase.rpc('acc_list_snapshots_v1',{p_limit:MAX_BLOCK_ITEMS}),supabase.rpc('acc_recent_logs_v1',{p_limit:MAX_BLOCK_ITEMS}),supabase.rpc('drl_semester_list_v1'),supabase.rpc('tcm_news_admin_list_v1',{p_limit:MAX_BLOCK_ITEMS})]);for(const result of [h,s,l,drl,news])if(result.error)throw result.error;setHealth(h.data as Health);setSnaps(((s.data||[]) as Snapshot[]).slice(0,MAX_BLOCK_ITEMS));setLogs(((l.data||[]) as Audit[]).slice(0,MAX_BLOCK_ITEMS));setSemesters(((drl.data||[]) as Semester[]).slice(0,MAX_BLOCK_ITEMS));setAdminNews((Array.isArray(news.data)?news.data as AdminNews[]:[]).slice(0,MAX_BLOCK_ITEMS))}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const loadWeather=async(lat?:number,lon?:number)=>{try{const qs=Number.isFinite(lat)&&Number.isFinite(lon)?`?lat=${lat}&lon=${lon}`:'';const r=await fetch(`${edgeUrl('public-weather')}${qs}`,{cache:'no-store',headers:{apikey:SUPABASE_PUBLISHABLE_KEY}});if(!r.ok)throw new Error(`Weather HTTP ${r.status}`);setWeather(await r.json())}catch{setWeather({available:false})}};
  useEffect(()=>{void load();void loadWeather()},[]);
  const createSnapshot=async()=>{setBusy(true);try{const {data,error}=await supabase.rpc('acc_create_snapshot_v1');if(error)throw error;setMsg(`Snapshot đã tạo · checksum ${(data as {checksum:string}).checksum}`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const exportSnapshot=async(id:string)=>{setBusy(true);try{const {data,error}=await supabase.rpc('acc_export_snapshot_v1',{p_snapshot_id:id});if(error)throw error;downloadJson(`yhct-managed-snapshot-${id}.json`,data);setMsg('Đã xuất JSON cục bộ kèm checksum.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const restore=async(s:Snapshot)=>{if(window.prompt(`Nhập RESTORE để khôi phục snapshot ${s.id.slice(0,8)}.`)!=='RESTORE')return;setBusy(true);try{const {data,error}=await supabase.rpc('acc_restore_snapshot_v1',{p_snapshot_id:s.id});if(error)throw error;setMsg(`Restore hoàn tất. Pre-restore snapshot: ${(data as {preRestoreSnapshotId:string}).preRestoreSnapshotId}`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const purge=async()=>{try{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('yhct-hiu-4-')).map(k=>caches.delete(k)));const reg=await navigator.serviceWorker?.getRegistration();await reg?.update();setMsg(`Đã purge ${keys.length} cache client và yêu cầu Service Worker cập nhật.`)}catch(e){setMsg((e as Error).message)}};
  const diagnose=async()=>{setBusy(true);setDiag('');try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Phiên Admin đã hết hạn.');const r=await fetch(edgeUrl('acc-diagnostics'),{method:'POST',headers:{'content-type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY,authorization:`Bearer ${session.access_token}`},body:JSON.stringify({health,logs})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error((j as {error?:string}).error||`Diagnostic HTTP ${r.status}`)}const j=await r.json() as {analysis?:string};setDiag(j.analysis||'Không có kết quả.')}catch(e){setDiag((e as Error).message)}finally{setBusy(false)}};
  const gps=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>void loadWeather(p.coords.latitude,p.coords.longitude),e=>setMsg(`Không lấy được GPS: ${e.message}`),{timeout:7000,maximumAge:600000}):setMsg('Thiết bị không hỗ trợ GPS trình duyệt.');
  const setDeadline=async(s:Semester,value:string)=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('drl_admin_set_lock_at_v1',{p_semester_id:s.id,p_lock_at:value?new Date(value).toISOString():null});if(error)throw error;setMsg(`Đã cập nhật hạn khóa cho ${s.title}.`);await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const review=async(item:AdminNews,status:'published'|'rejected')=>{setBusy(true);setMsg('');try{const {error}=await supabase.rpc('tcm_news_review_v1',{p_id:item.id,p_status:status});if(error)throw error;setMsg(status==='published'?'Đã duyệt và công bố tin.':'Đã từ chối tin.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const editNews=async(item:AdminNews)=>{const title=window.prompt('Tiêu đề tin:',item.title);if(title===null)return;const summary=window.prompt('Tóm tắt:',item.summary||'');if(summary===null)return;setBusy(true);try{const {error}=await supabase.rpc('tcm_news_admin_update_v1',{p_id:item.id,p_title:title,p_summary:summary});if(error)throw error;setMsg('Đã cập nhật tin.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const togglePin=async(item:AdminNews)=>{setBusy(true);try{const {error}=await supabase.rpc('tcm_news_admin_set_pinned_v1',{p_id:item.id,p_pinned:!item.is_pinned});if(error)throw error;setMsg(item.is_pinned?'Đã bỏ ghim tin.':'Đã ghim tin.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const deleteNews=async(item:AdminNews)=>{if(!window.confirm(`Xóa vĩnh viễn tin “${item.title}”?`))return;setBusy(true);try{const {error}=await supabase.rpc('tcm_news_admin_delete_v1',{p_id:item.id});if(error)throw error;setMsg('Đã xóa tin.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};

  return <section>
    <div className="between"><div className="row panel-title"><ShieldAlert/><div><h2>Admin Control Center · System</h2><p>Mỗi khối vận hành chỉ hiển thị 5 nội dung gần nhất để giảm nhiễu.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void load()}><RefreshCw/>Làm mới</button></div>
    {msg&&<div className="ai-note" role="status">{msg}</div>}
    <div className="acc-grid"><section className="panel acc-status"><div className="row"><TaijiIcon/><div><b>{now.toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}</b><small>Âm lịch Việt Nam: {formatLunar(now)}</small></div></div><div className="row"><CloudSun/><div><b>{weather?.available?`${weather.temperature}°C · ${weather.condition}`:'Thời tiết chưa xác định'}</b><small>{weather?.available?`Cảm giác ${weather.apparentTemperature}°C · Ẩm ${weather.humidity}% · Gió ${weather.windSpeed} km/h`:'Dùng GPS thiết bị để tăng độ chính xác.'}</small></div></div><button className="secondary" onClick={gps}>Dùng GPS thiết bị</button></section><section className="panel"><div className="row"><Activity/><h3>System Health</h3></div>{health&&<><div className="health-kpis">{Object.entries(health.counts||{}).slice(0,5).map(([k,v])=><span key={k}><b>{v}</b><small>{k}</small></span>)}</div><p className="muted">Postgres {health.postgres} · {new Date(health.serverTime).toLocaleString('vi-VN')}</p></>}<div className="schedule-actions"><button onClick={()=>void purge()}><Trash2/>Purge cache</button><button className="secondary" disabled={busy} onClick={()=>void diagnose()}><BrainCircuit/>A.I Diagnostic</button></div>{diag&&<pre className="diagnostic-output">{diag}</pre>}</section></div>

    <div className="admin-v6-grid">
      <section className="panel admin-v6-block"><BlockTitle title="Hạn chót khóa điểm"/><div className="semester-grid compact">{semesters.map(s=><article key={s.id}><b>{s.title}</b><small>{s.code} · {s.is_locked?'Đã khóa':'Đang mở'}</small><label>Khóa lúc<input type="datetime-local" defaultValue={localDateTime(s.lock_at)} disabled={busy} onBlur={e=>{if(e.currentTarget.value!==localDateTime(s.lock_at))void setDeadline(s,e.currentTarget.value)}}/></label></article>)}</div></section>
      <section className="panel admin-v6-block"><BlockTitle title="Tin tức YHCT"/><p className="muted">Tin được cập nhật theo nguồn; feed ẩn tin quá 48 giờ và cron xóa tự động mỗi giờ.</p><div className="news-admin-list compact">{adminNews.map(n=><article key={n.id} className={n.is_pinned?'is-pinned':''}><div className="news-admin-copy"><b>{n.is_pinned?'📌 ':''}{n.title}</b><small>{n.publisher||'Nguồn tổng hợp'} · {n.status}{n.published_at?` · ${new Date(n.published_at).toLocaleString('vi-VN')}`:''}</small></div><div className="schedule-actions">{n.status==='pending'&&<><button disabled={busy} onClick={()=>void review(n,'published')}><CheckCircle2/>Duyệt</button><button className="danger-btn" disabled={busy} onClick={()=>void review(n,'rejected')}><XCircle/>Từ chối</button></>}<button className="secondary" disabled={busy} onClick={()=>void editNews(n)}><Pencil/>Sửa</button><button className="secondary" disabled={busy} onClick={()=>void togglePin(n)}><Pin/>{n.is_pinned?'Bỏ ghim':'Ghim'}</button><button className="danger-btn" disabled={busy} onClick={()=>void deleteNews(n)}><Trash2/>Xóa</button></div></article>)}{!adminNews.length&&<p className="muted">Không có tin trong 48 giờ gần nhất.</p>}</div></section>
      <section className="panel admin-v6-block"><BlockTitle title="Snapshot & Restore"/><div className="between"><p className="muted">Snapshot logic có checksum.</p><button disabled={busy} onClick={()=>void createSnapshot()}><DatabaseBackup/>Tạo</button></div><div className="data-list compact">{snaps.map(s=><article key={s.id}><div><b>{new Date(s.created_at).toLocaleString('vi-VN')}</b><small>SHA-256 {s.checksum_sha256.slice(0,18)}…</small></div><div className="schedule-actions"><button className="secondary" onClick={()=>void exportSnapshot(s.id)}><Download/>JSON</button><button className="danger-btn" onClick={()=>void restore(s)}><RotateCcw/>Restore</button></div></article>)}</div></section>
      <section className="panel admin-v6-block"><BlockTitle title="Audit & Error Logs"/><div className="log-list compact">{logs.map(x=><article key={x.id} className={`log-${x.severity}`}><div><b>{x.action}</b><small>{new Date(x.created_at).toLocaleString('vi-VN')} · {x.entity_type||'system'} {x.entity_id||''}</small></div><span>{x.severity}</span></article>)}</div></section>
    </div>
  </section>;
}
