import { useEffect,useMemo,useState } from 'react';
import { BookHeart,CalendarClock,FlaskConical,Leaf,Search,TimerReset } from 'lucide-react';
import type { Member } from '../../types';
import { supabase } from '../../services/authService';

type DrlData={semester_title?:string|null;total_points?:number;deadline_at?:string|null};
type ResearchItem={id:string;title:string;summary:string;slots:number;deadline_at?:string|null;applied:boolean};
type ScheduleItem={id:string;title:string;kind:string;starts_at:string;ends_at:string;location:string;checked_in:boolean};
type WidgetData={drl:DrlData;research:ResearchItem[];schedule:ScheduleItem[]};
type Interaction={herb:string;drug:string;severity:'info'|'caution'|'high';summary:string;source_title:string;source_url?:string|null;verified_at:string};

const SOLAR_TERMS=[[1,5,'Tiểu hàn'],[1,20,'Đại hàn'],[2,4,'Lập xuân'],[2,19,'Vũ thủy'],[3,5,'Kinh trập'],[3,20,'Xuân phân'],[4,4,'Thanh minh'],[4,20,'Cốc vũ'],[5,5,'Lập hạ'],[5,21,'Tiểu mãn'],[6,5,'Mang chủng'],[6,21,'Hạ chí'],[7,7,'Tiểu thử'],[7,22,'Đại thử'],[8,7,'Lập thu'],[8,23,'Xử thử'],[9,7,'Bạch lộ'],[9,23,'Thu phân'],[10,8,'Hàn lộ'],[10,23,'Sương giáng'],[11,7,'Lập đông'],[11,22,'Tiểu tuyết'],[12,7,'Đại tuyết'],[12,21,'Đông chí']] as const;
const MERIDIANS=[['Tý','Đởm',23,1],['Sửu','Can',1,3],['Dần','Phế',3,5],['Mão','Đại trường',5,7],['Thìn','Vị',7,9],['Tỵ','Tỳ',9,11],['Ngọ','Tâm',11,13],['Mùi','Tiểu trường',13,15],['Thân','Bàng quang',15,17],['Dậu','Thận',17,19],['Tuất','Tâm bào',19,21],['Hợi','Tam tiêu',21,23]] as const;
function currentSolarTerm(now:Date){const month=now.getMonth()+1,day=now.getDate();let current=SOLAR_TERMS[SOLAR_TERMS.length-1][2];for(const [m,d,name] of SOLAR_TERMS){if(month>m||(month===m&&day>=d))current=name;else break}return current}
function currentMeridian(hour:number){return MERIDIANS.find(([, ,start,end])=>start>end?(hour>=start||hour<end):(hour>=start&&hour<end))||MERIDIANS[0]}
function daysUntil(value?:string|null){if(!value)return null;return Math.ceil((new Date(value).getTime()-Date.now())/86400000)}
const fmt=(value:string)=>new Date(value).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});

export default function DesktopAcademicWidgets({member}:{member:Member|null}){
  const [data,setData]=useState<WidgetData>({drl:{},research:[],schedule:[]}),[msg,setMsg]=useState(''),[herb,setHerb]=useState(''),[drug,setDrug]=useState(''),[interactions,setInteractions]=useState<Interaction[]|null>(null),[busy,setBusy]=useState(false),[clock,setClock]=useState(()=>new Date());
  const load=async()=>{if(!member){setData({drl:{},research:[],schedule:[]});return}const {data,error}=await supabase.rpc('desktop_widgets_v1');if(error)throw error;const x=(data||{}) as Partial<WidgetData>;setData({drl:x.drl||{},research:Array.isArray(x.research)?x.research:[],schedule:Array.isArray(x.schedule)?x.schedule:[]})};
  useEffect(()=>{void load().catch(()=>setMsg('Không thể làm mới widget thành viên lúc này.'));const id=window.setInterval(()=>setClock(new Date()),60000);return()=>window.clearInterval(id)},[member?.id]);
  const solar=currentSolarTerm(clock),meridian=currentMeridian(clock.getHours()),deadline=daysUntil(data.drl.deadline_at);
  const searchInteraction=async()=>{if(herb.trim().length<2||drug.trim().length<2){setMsg('Nhập ít nhất 2 ký tự cho cả vị thuốc và hoạt chất.');return}setBusy(true);setMsg('');try{const {data:found,error}=await supabase.rpc('herb_drug_interaction_search_v1',{p_herb:herb.trim(),p_drug:drug.trim()});if(error)throw error;setInteractions(Array.isArray(found)?found as Interaction[]:[])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const apply=async(id:string)=>{if(!member){setMsg('Đăng nhập thành viên để xin tham gia đề tài.');return}setBusy(true);try{const {error}=await supabase.rpc('research_apply_v1',{p_opportunity_id:id});if(error)throw error;await load();setMsg('Đã gửi yêu cầu tham gia đề tài.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const checkin=async(id:string)=>{if(!member){setMsg('Đăng nhập thành viên để check-in.');return}setBusy(true);try{const {error}=await supabase.rpc('schedule_checkin_v1',{p_schedule_id:id});if(error)throw error;await load();setMsg('Check-in đã được ghi nhận.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const nearest=useMemo(()=>data.schedule[0],[data.schedule]);
  return <aside className="desktop-academic-widgets" aria-label="Tiện ích học thuật YHCT trên desktop">
    <section className="desktop-widget solar-widget"><header><CalendarClock/><div><b>Tiết khí & Thời trực</b><small>Tham khảo lịch YHCT</small></div></header><div className="widget-metric"><strong>{solar}</strong><span>{meridian[0]} · Kinh {meridian[1]}</span></div><p>Giữ nhịp ngủ, vận động và ăn uống điều độ theo mùa. Nội dung này mang tính học thuật/văn hóa, không phải chỉ định điều trị.</p></section>
    <section className="desktop-widget drl-widget"><header><TimerReset/><div><b>DRL Tracker</b><small>Điểm học kỳ đã công bố</small></div></header>{member?<><div className="widget-metric"><strong>{Number(data.drl.total_points||0).toLocaleString('vi-VN')} điểm</strong><span>{data.drl.semester_title||'Chưa có học kỳ công bố'}</span></div>{deadline!==null&&<p className={deadline<=7?'widget-warning':''}>{deadline>=0?`Còn ${deadline} ngày đến mốc khóa sổ.`:'Mốc khóa sổ đã qua.'}</p>}</>:<p>Đăng nhập để xem điểm cá nhân và mốc khóa sổ.</p>}</section>
    <section className="desktop-widget interaction-widget"><header><BookHeart/><div><b>Tương tác Đông – Tây y</b><small>Chỉ dữ liệu đã kiểm chứng</small></div></header><div className="widget-search"><input value={herb} onChange={e=>setHerb(e.target.value)} placeholder="Vị thuốc"/><input value={drug} onChange={e=>setDrug(e.target.value)} placeholder="Hoạt chất"/><button disabled={busy} onClick={()=>void searchInteraction()} aria-label="Tra tương tác"><Search/></button></div>{interactions!==null&&(interactions.length?<div className="widget-list">{interactions.slice(0,3).map((x,i)=><article key={`${x.herb}-${x.drug}-${i}`}><b>{x.herb} × {x.drug}</b><small>{x.severity==='high'?'Nguy cơ cao':x.severity==='caution'?'Thận trọng':'Thông tin'} · {x.summary}</small><em>Nguồn: {x.source_title}</em></article>)}</div>:<p>Chưa có bản ghi kiểm chứng phù hợp. Hệ thống không suy đoán tương tác thuốc.</p>)}</section>
    <section className="desktop-widget research-widget"><header><FlaskConical/><div><b>NCKH & Tìm nhóm</b><small>Đề tài đang mở</small></div></header>{member?<div className="widget-list">{data.research.length?data.research.map(x=><article key={x.id}><b>{x.title}</b><small>{x.summary||`${x.slots} vị trí cộng tác`}{x.deadline_at?` · hạn ${fmt(x.deadline_at)}`:''}</small><button disabled={busy||x.applied} onClick={()=>void apply(x.id)}>{x.applied?'Đã xin tham gia':'Xin tham gia'}</button></article>):<p>Chưa có đề tài mở được công bố.</p>}</div>:<p>Đăng nhập để xem đề tài nội bộ và xin tham gia.</p>}</section>
    <section className="desktop-widget schedule-widget"><header><Leaf/><div><b>Lịch trực & Phòng thực hành</b><small>Ca sắp tới</small></div></header>{member?(nearest?<div className="widget-list">{data.schedule.slice(0,3).map(x=><article key={x.id}><b>{x.title}</b><small>{fmt(x.starts_at)} · {x.location||'Chưa ghi địa điểm'}</small><button disabled={busy||x.checked_in} onClick={()=>void checkin(x.id)}>{x.checked_in?'Đã check-in':'Check-in'}</button></article>)}</div>:<p>Chưa có lịch hoạt động sắp tới.</p>):<p>Đăng nhập để xem lịch trực và check-in.</p>}</section>
    {msg&&<div className="widget-status" role="status">{msg}</div>}
  </aside>;
}
