import {useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,Coins,Droplets,Home,Leaf,LockKeyhole,Palette,RefreshCw,Search,ShoppingBasket,Sprout,Store,Users} from 'lucide-react';
import type {Member} from '../../types';
import {supabase} from '../../services/authService';
import '../../garden-v6.css';

type DirectoryRow={member_id:string;display_name:string;full_name:string;avatar_url?:string|null;theme:string;decor:string[];active_plots:number;unlocked_plots:number};
type VisitPlot={slot_no:number;unlocked:boolean;harvest_count:number;plant:null|{id:string;status:string;planted_at:string;matures_at:string;water_count:number;fertilizer_count:number;can_water:boolean;can_fertilize:boolean;name?:string|null;visual_variant?:number|null}};
type VisitData={owner:{id:string;display_name:string;full_name:string;avatar_url?:string|null};theme:string;decor:string[];plots:VisitPlot[]};
type MarketRow={id:string;seller_member_id:string;seller_name:string;herb_name:string;botanical_name:string;seed_key:string;quantity:number;price_credits:number;created_at:string};
type Inventory={seed_key:string;name:string;botanical_name:string;quantity:number};
type Tab='visit'|'market'|'decorate';
const THEMES=[['bamboo','Trúc xanh'],['lotus','Liên hoa'],['stone','Thạch viên'],['lantern','Đèn dược phòng'],['herbal-paper','Giấy thảo mộc']] as const;
const DECOR=[['pond','Ao sen'],['lantern','Đèn lồng'],['stone-path','Lối đá'],['bamboo-gate','Cổng trúc'],['lotus-pot','Chậu sen'],['herb-sign','Bảng tên dược liệu']] as const;
const COMMUNITY_PAGE_SIZE=5;
const sprite=`${import.meta.env.BASE_URL}garden-decor-sprite.svg`;
function DecorArt({name}:{name:string}){return <svg className="garden-decor-svg" role="img" aria-label={DECOR.find(x=>x[0]===name)?.[1]||name}><use href={`${sprite}#${name}`}/></svg>}

export default function HerbGardenSocialHub({member}:{member:Member}){
  const [tab,setTab]=useState<Tab>('visit'),[q,setQ]=useState(''),[directory,setDirectory]=useState<DirectoryRow[]>([]),[directoryPage,setDirectoryPage]=useState(0),[visit,setVisit]=useState<VisitData|null>(null),[visitSlot,setVisitSlot]=useState<number|null>(null),[market,setMarket]=useState<MarketRow[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[wallet,setWallet]=useState(0),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const [theme,setTheme]=useState('bamboo'),[decor,setDecor]=useState<string[]>([]),[sellKey,setSellKey]=useState(''),[sellQty,setSellQty]=useState(1),[sellPrice,setSellPrice]=useState(5);
  const myListings=useMemo(()=>market.filter(x=>x.seller_member_id===member.id),[market,member.id]);
  const selectedVisit=useMemo(()=>visit?.plots?.find(x=>x.slot_no===visitSlot)||null,[visit,visitSlot]);
  const directoryPageCount=Math.max(1,Math.ceil(directory.length/COMMUNITY_PAGE_SIZE));
  const visibleDirectory=useMemo(()=>{const start=directoryPage*COMMUNITY_PAGE_SIZE;return directory.slice(start,start+COMMUNITY_PAGE_SIZE)},[directory,directoryPage]);
  const directoryRangeStart=directory.length?directoryPage*COMMUNITY_PAGE_SIZE+1:0;
  const directoryRangeEnd=Math.min(directory.length,(directoryPage+1)*COMMUNITY_PAGE_SIZE);

  const loadDirectory=async(term=q)=>{const r=await supabase.rpc('herb_garden_directory_v2',{p_query:term.trim(),p_limit:30});if(r.error)throw r.error;const rows=(r.data||[]) as DirectoryRow[];setDirectory(rows);setDirectoryPage(page=>Math.min(page,Math.max(0,Math.ceil(rows.length/COMMUNITY_PAGE_SIZE)-1)))};
  const loadMarket=async()=>{const [m,i,w,own]=await Promise.all([supabase.rpc('herb_garden_market_v1',{p_limit:50}),supabase.rpc('herb_garden_inventory_v3'),supabase.rpc('herb_garden_wallet_v1'),supabase.rpc('herb_garden_visit_v2',{p_member_id:member.id})]);for(const r of [m,i,w,own])if(r.error)throw r.error;setMarket((m.data||[]) as MarketRow[]);setInventory((i.data||[]) as Inventory[]);setWallet(Number(w.data||0));const ownData=own.data as VisitData;setTheme(ownData.theme||'bamboo');setDecor(Array.isArray(ownData.decor)?ownData.decor:[]);setSellKey(x=>x||String((i.data as Inventory[]|null)?.[0]?.seed_key||''))};
  const refresh=async()=>{setBusy(true);setMsg('');try{await Promise.all([loadDirectory(),loadMarket()])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{void refresh()},[member.id]);
  useEffect(()=>{setDirectoryPage(0);const t=window.setTimeout(()=>void loadDirectory(q).catch(e=>setMsg((e as Error).message)),250);return()=>window.clearTimeout(t)},[q]);
  const openGarden=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_visit_v2',{p_member_id:id});if(r.error)throw r.error;const data=r.data as VisitData;setVisit(data);setVisitSlot(data.plots.find(x=>x.plant)?.slot_no||data.plots.find(x=>x.unlocked)?.slot_no||null)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const help=async(kind:'water'|'fertilize')=>{if(!visit||!selectedVisit?.plant)return;setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_help_v2',{p_owner_id:visit.owner.id,p_slot_no:selectedVisit.slot_no,p_kind:kind});if(r.error)throw r.error;setVisit(r.data as VisitData);setMsg(kind==='water'?`Đã giúp tưới ô ${selectedVisit.slot_no}.`:`Đã giúp bón phân ô ${selectedVisit.slot_no}.`)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const createListing=async()=>{if(!sellKey)return;setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_create_v1',{p_seed_key:sellKey,p_quantity:sellQty,p_price_credits:sellPrice});if(r.error)throw r.error;setMsg('Đã đưa dược liệu lên chợ trao đổi.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const buy=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_buy_v1',{p_listing_id:id});if(r.error)throw r.error;setMsg('Giao dịch thành công.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const cancel=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_cancel_v1',{p_listing_id:id});if(r.error)throw r.error;setMsg('Đã hủy tin và hoàn dược liệu về kho.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const saveDecor=async()=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_profile_update_v1',{p_theme:theme,p_decor:decor});if(r.error)throw r.error;const verify=await supabase.rpc('herb_garden_visit_v2',{p_member_id:member.id});if(verify.error)throw verify.error;const own=verify.data as VisitData,persistedTheme=own.theme||'bamboo',persistedDecor=Array.isArray(own.decor)?own.decor:[];if(persistedTheme!==theme||[...persistedDecor].sort().join('|')!==[...decor].sort().join('|'))throw new Error('Cá nhân hóa chưa được ghi bền vững.');setTheme(persistedTheme);setDecor(persistedDecor);window.dispatchEvent(new CustomEvent('yhct:garden-profile-updated',{detail:{theme:persistedTheme,decor:persistedDecor}}));setMsg('Đã lưu và xác nhận cá nhân hóa Gia Viên.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};

  return <section className="garden-social panel"><div className="between"><div className="row"><Users/><div><h3>Gia Viên cộng đồng</h3><p className="muted">Thăm lưới vườn 3×3, hỗ trợ đúng ô, trao đổi dược liệu và cá nhân hóa không gian.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw/>Làm mới</button></div>
    {msg&&<div className="ai-note" role="status">{msg}</div>}
    <div className="garden-social-tabs"><button className={tab==='visit'?'active':''} onClick={()=>setTab('visit')}><Home/>Thăm vườn</button><button className={tab==='market'?'active':''} onClick={()=>setTab('market')}><Store/>Chợ dược liệu</button><button className={tab==='decorate'?'active':''} onClick={()=>setTab('decorate')}><Palette/>Trang trí</button></div>
    {tab==='visit'&&<div className="garden-community-layout"><aside><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên hoặc biệt danh cây thuốc"/></div><div className="garden-directory garden-directory--paged">{visibleDirectory.map(row=><button key={row.member_id} onClick={()=>void openGarden(row.member_id)}><span className="garden-person-avatar">{row.avatar_url?<img src={row.avatar_url} alt=""/>:<Sprout/>}</span><span><b>{row.display_name}</b><small>{row.full_name} · {row.active_plots} cây · mở {row.unlocked_plots||0}/9 ô</small></span></button>)}{!visibleDirectory.length&&<div className="garden-directory-empty"><Users/><small>Không tìm thấy thành viên phù hợp.</small></div>}</div><div className="garden-directory-pager" aria-label="Phân trang Gia Viên cộng đồng"><button type="button" disabled={directoryPage===0} onClick={()=>setDirectoryPage(page=>Math.max(0,page-1))}><ChevronLeft/>Trước</button><span><b>{directoryRangeStart}–{directoryRangeEnd}</b> / {directory.length} · trang {directoryPage+1}/{directoryPageCount}</span><button type="button" disabled={directoryPage>=directoryPageCount-1} onClick={()=>setDirectoryPage(page=>Math.min(directoryPageCount-1,page+1))}>Sau<ChevronRight/></button></div></aside><section className={`visited-garden garden-theme-${visit?.theme||'bamboo'}`}>{visit?<><header><div className="row"><Leaf/><div><h4>Vườn của {visit.owner.display_name}</h4><small>{visit.owner.full_name}</small></div></div></header><div className="visited-decor garden-decor-live-preview v6">{visit.decor?.map(x=><span key={x}><DecorArt name={x}/><small>{DECOR.find(d=>d[0]===x)?.[1]||x}</small></span>)}</div><div className="visited-grid-v3">{visit.plots.map(p=><button key={p.slot_no} disabled={!p.unlocked} onClick={()=>p.unlocked&&setVisitSlot(p.slot_no)} className={`visited-plot-v3 ${p.unlocked?'':'is-locked'} ${p.plant?'is-active':''} ${visitSlot===p.slot_no?'is-selected':''}`}><b>Ô {p.slot_no}</b>{!p.unlocked?<LockKeyhole/>:p.plant?<><Sprout/><small>{p.plant.name||p.plant.status}</small></>:<small>Trống</small>}</button>)}</div>{selectedVisit?.plant?<article className="visited-plant"><Sprout/><div><b>Ô {selectedVisit.slot_no} · {selectedVisit.plant.name||'Cây thuốc bí ẩn'}</b><small>{selectedVisit.plant.status} · Tưới {selectedVisit.plant.water_count}/12 · Bón {selectedVisit.plant.fertilizer_count}/3</small></div></article>:<p className="muted">Chọn một ô đang có cây để hỗ trợ.</p>}<div className="schedule-actions"><button disabled={busy||!selectedVisit?.plant?.can_water} onClick={()=>void help('water')}><Droplets/>Giúp tưới ô</button><button disabled={busy||!selectedVisit?.plant?.can_fertilize} onClick={()=>void help('fertilize')}><Leaf/>Giúp bón phân ô</button></div></>:<div className="empty-state compact"><Users/><p>Chọn một thành viên để ghé thăm Gia Viên.</p></div>}</section></div>}
    {tab==='market'&&<div className="garden-market"><div className="garden-wallet"><Coins/><div><b>{wallet} tín dụng vườn</b><small>Giao dịch vườn không làm giảm xếp hạng học thuật.</small></div></div><section className="garden-sell-box"><h4>Rao bán từ kho của bạn</h4>{inventory.length?<div className="garden-sell-form"><select value={sellKey} onChange={e=>setSellKey(e.target.value)}>{inventory.map(x=><option key={x.seed_key} value={x.seed_key}>{x.name} · kho ×{x.quantity}</option>)}</select><input type="number" min={1} max={20} value={sellQty} onChange={e=>setSellQty(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/><input type="number" min={1} max={10000} value={sellPrice} onChange={e=>setSellPrice(Math.max(1,Math.min(10000,Number(e.target.value)||1)))}/><button disabled={busy||!sellKey} onClick={()=>void createListing()}><ShoppingBasket/>Đăng bán</button></div>:<p className="muted">Kho chưa có dược liệu để giao dịch.</p>}</section><div className="garden-market-list">{market.map(row=><article key={row.id}><div><b>{row.herb_name} ×{row.quantity}</b><small>{row.botanical_name} · người bán {row.seller_name}</small></div><strong>{row.price_credits} tín dụng</strong>{row.seller_member_id===member.id?<button className="secondary" disabled={busy} onClick={()=>void cancel(row.id)}>Hủy tin</button>:<button disabled={busy||wallet<row.price_credits} onClick={()=>void buy(row.id)}>Mua</button>}</article>)}{!market.length&&<p className="muted">Chợ hiện chưa có tin trao đổi.</p>}</div>{myListings.length>0&&<small>Bạn đang có {myListings.length} tin bán hoạt động.</small>}</div>}
    {tab==='decorate'&&<div className={`garden-decor-editor garden-theme-${theme}`}><label>Chủ đề<select value={theme} onChange={e=>setTheme(e.target.value)}>{THEMES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="garden-decor-live-preview v6" aria-label="Xem trước trang trí">{decor.length?decor.map(x=><span key={x}><DecorArt name={x}/><small>{DECOR.find(d=>d[0]===x)?.[1]||x}</small></span>):<small>Chưa chọn vật trang trí.</small>}</div><div className="garden-decor-options">{DECOR.map(([v,l])=><label className="garden-decor-option-v6" key={v}><input type="checkbox" checked={decor.includes(v)} onChange={e=>setDecor(xs=>e.target.checked?[...new Set([...xs,v])]:xs.filter(x=>x!==v))}/><DecorArt name={v}/><span>{l}</span></label>)}</div><button disabled={busy} onClick={()=>void saveDecor()}><Palette/>Lưu không gian vườn</button></div>}
  </section>;
}
