import {useEffect,useMemo,useState} from 'react';
import {Coins,Droplets,Home,Leaf,Palette,RefreshCw,Search,ShoppingBasket,Sprout,Store,Users} from 'lucide-react';
import type {Member} from '../../types';
import {supabase} from '../../services/authService';

type DirectoryRow={member_id:string;display_name:string;full_name:string;avatar_url?:string|null;theme:string;decor:string[];plant_status?:string|null;plant_progress:number};
type VisitData={owner:{id:string;display_name:string;full_name:string;avatar_url?:string|null};theme:string;decor:string[];plant:null|{id:string;status:string;planted_at:string;matures_at:string;water_count:number;fertilizer_count:number;can_water:boolean;can_fertilize:boolean;name?:string|null;visual_variant?:number|null}};
type MarketRow={id:string;seller_member_id:string;seller_name:string;herb_name:string;botanical_name:string;seed_key:string;quantity:number;price_credits:number;created_at:string};
type Inventory={seed_key:string;name:string;botanical_name:string;quantity:number};
type Tab='visit'|'market'|'decorate';
const THEMES=[['bamboo','Trúc xanh'],['lotus','Liên hoa'],['stone','Thạch viên'],['lantern','Đèn dược phòng'],['herbal-paper','Giấy thảo mộc']] as const;
const DECOR=[['pond','Ao sen'],['lantern','Đèn lồng'],['stone-path','Lối đá'],['bamboo-gate','Cổng trúc'],['lotus-pot','Chậu sen'],['herb-sign','Bảng tên dược liệu']] as const;

export default function HerbGardenSocialHub({member}:{member:Member}){
  const [tab,setTab]=useState<Tab>('visit'),[q,setQ]=useState(''),[directory,setDirectory]=useState<DirectoryRow[]>([]),[visit,setVisit]=useState<VisitData|null>(null),[market,setMarket]=useState<MarketRow[]>([]),[inventory,setInventory]=useState<Inventory[]>([]),[wallet,setWallet]=useState(0),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const [theme,setTheme]=useState('bamboo'),[decor,setDecor]=useState<string[]>([]),[sellKey,setSellKey]=useState(''),[sellQty,setSellQty]=useState(1),[sellPrice,setSellPrice]=useState(5);
  const myListings=useMemo(()=>market.filter(x=>x.seller_member_id===member.id),[market,member.id]);
  const loadDirectory=async(term=q)=>{const r=await supabase.rpc('herb_garden_directory_v1',{p_query:term.trim(),p_limit:30});if(r.error)throw r.error;setDirectory((r.data||[]) as DirectoryRow[])};
  const loadMarket=async()=>{const [m,i,w,own]=await Promise.all([supabase.rpc('herb_garden_market_v1',{p_limit:50}),supabase.rpc('herb_garden_inventory_v3'),supabase.rpc('herb_garden_wallet_v1'),supabase.rpc('herb_garden_visit_v1',{p_member_id:member.id})]);for(const r of [m,i,w,own])if(r.error)throw r.error;setMarket((m.data||[]) as MarketRow[]);setInventory((i.data||[]) as Inventory[]);setWallet(Number(w.data||0));const ownData=own.data as VisitData;setTheme(ownData.theme||'bamboo');setDecor(Array.isArray(ownData.decor)?ownData.decor:[]);setSellKey(x=>x||String((i.data as Inventory[]|null)?.[0]?.seed_key||''))};
  const refresh=async()=>{setBusy(true);setMsg('');try{await Promise.all([loadDirectory(),loadMarket()])}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{void refresh()},[member.id]);
  useEffect(()=>{const t=window.setTimeout(()=>void loadDirectory(q).catch(e=>setMsg((e as Error).message)),250);return()=>window.clearTimeout(t)},[q]);
  const openGarden=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_visit_v1',{p_member_id:id});if(r.error)throw r.error;setVisit(r.data as VisitData)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const help=async(kind:'water'|'fertilize')=>{if(!visit)return;setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_help_v1',{p_owner_id:visit.owner.id,p_kind:kind});if(r.error)throw r.error;setVisit(r.data as VisitData);setMsg(kind==='water'?'Đã giúp bạn tưới cây.':'Đã giúp bạn bón phân.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const createListing=async()=>{if(!sellKey)return;setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_create_v1',{p_seed_key:sellKey,p_quantity:sellQty,p_price_credits:sellPrice});if(r.error)throw r.error;setMsg('Đã đưa dược liệu lên chợ trao đổi.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const buy=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_buy_v1',{p_listing_id:id});if(r.error)throw r.error;setMsg('Giao dịch thành công. Dược liệu đã vào kho của bạn.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const cancel=async(id:string)=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_market_cancel_v1',{p_listing_id:id});if(r.error)throw r.error;setMsg('Đã hủy tin và hoàn dược liệu về kho.');await loadMarket()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const saveDecor=async()=>{setBusy(true);setMsg('');try{const r=await supabase.rpc('herb_garden_profile_update_v1',{p_theme:theme,p_decor:decor});if(r.error)throw r.error;setMsg('Đã lưu cá nhân hóa Gia Viên.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  return <section className="garden-social panel"><div className="between"><div className="row"><Users/><div><h3>Gia Viên cộng đồng</h3><p className="muted">Thăm vườn, hỗ trợ chăm sóc, trao đổi dược liệu và cá nhân hóa không gian.</p></div></div><button className="secondary" disabled={busy} onClick={()=>void refresh()}><RefreshCw/>Làm mới</button></div>
    {msg&&<div className="ai-note" role="status">{msg}</div>}
    <div className="garden-social-tabs"><button className={tab==='visit'?'active':''} onClick={()=>setTab('visit')}><Home/>Thăm vườn</button><button className={tab==='market'?'active':''} onClick={()=>setTab('market')}><Store/>Chợ dược liệu</button><button className={tab==='decorate'?'active':''} onClick={()=>setTab('decorate')}><Palette/>Trang trí</button></div>
    {tab==='visit'&&<div className="garden-community-layout"><aside><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên hoặc biệt danh cây thuốc"/></div><div className="garden-directory">{directory.map(row=><button key={row.member_id} onClick={()=>void openGarden(row.member_id)}><span className="garden-person-avatar">{row.avatar_url?<img src={row.avatar_url} alt=""/>:<Sprout/>}</span><span><b>{row.display_name}</b><small>{row.full_name} · {row.plant_status||'vườn trống'} · {row.plant_progress||0}%</small></span></button>)}</div></aside><section className={`visited-garden garden-theme-${visit?.theme||'bamboo'}`}>{visit?<><header><div className="row"><Leaf/><div><h4>Vườn của {visit.owner.display_name}</h4><small>{visit.owner.full_name}</small></div></div></header><div className="visited-decor">{visit.decor?.map(x=><span key={x}>{DECOR.find(d=>d[0]===x)?.[1]||x}</span>)}</div>{visit.plant?<article className="visited-plant"><Sprout/><div><b>{visit.plant.name||'Cây thuốc bí ẩn'}</b><small>{visit.plant.status} · Tưới {visit.plant.water_count}/12 · Bón {visit.plant.fertilizer_count}/3</small></div></article>:<p className="muted">Vườn này chưa có cây đang hoạt động.</p>}<div className="schedule-actions"><button disabled={busy||!visit.plant?.can_water} onClick={()=>void help('water')}><Droplets/>Giúp tưới</button><button disabled={busy||!visit.plant?.can_fertilize} onClick={()=>void help('fertilize')}><Leaf/>Giúp bón phân</button></div></>:<div className="empty-state compact"><Users/><p>Chọn một thành viên để ghé thăm Gia Viên.</p></div>}</section></div>}
    {tab==='market'&&<div className="garden-market"><div className="garden-wallet"><Coins/><div><b>{wallet} tín dụng vườn</b><small>Khởi tạo từ tín dụng cộng đồng; giao dịch vườn không làm giảm xếp hạng học thuật.</small></div></div><section className="garden-sell-box"><h4>Rao bán từ kho của bạn</h4>{inventory.length?<div className="garden-sell-form"><select value={sellKey} onChange={e=>setSellKey(e.target.value)}>{inventory.map(x=><option key={x.seed_key} value={x.seed_key}>{x.name} · kho ×{x.quantity}</option>)}</select><input type="number" min={1} max={20} value={sellQty} onChange={e=>setSellQty(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/><input type="number" min={1} max={10000} value={sellPrice} onChange={e=>setSellPrice(Math.max(1,Math.min(10000,Number(e.target.value)||1)))}/><button disabled={busy||!sellKey} onClick={()=>void createListing()}><ShoppingBasket/>Đăng bán</button></div>:<p className="muted">Kho chưa có dược liệu để giao dịch.</p>}</section><div className="garden-market-list">{market.map(row=><article key={row.id}><div><b>{row.herb_name} ×{row.quantity}</b><small>{row.botanical_name} · người bán {row.seller_name}</small></div><strong>{row.price_credits} tín dụng</strong>{row.seller_member_id===member.id?<button className="secondary" disabled={busy} onClick={()=>void cancel(row.id)}>Hủy tin</button>:<button disabled={busy||wallet<row.price_credits} onClick={()=>void buy(row.id)}>Mua</button>}</article>)}{!market.length&&<p className="muted">Chợ hiện chưa có tin trao đổi.</p>}</div>{myListings.length>0&&<small>Bạn đang có {myListings.length} tin bán hoạt động.</small>}</div>}
    {tab==='decorate'&&<div className={`garden-decor-editor garden-theme-${theme}`}><label>Chủ đề<select value={theme} onChange={e=>setTheme(e.target.value)}>{THEMES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="garden-decor-options">{DECOR.map(([v,l])=><label key={v}><input type="checkbox" checked={decor.includes(v)} onChange={e=>setDecor(xs=>e.target.checked?[...new Set([...xs,v])]:xs.filter(x=>x!==v))}/>{l}</label>)}</div><button disabled={busy} onClick={()=>void saveDecor()}><Palette/>Lưu không gian vườn</button></div>}
  </section>;
}
