import {useEffect,useMemo,useState} from 'react';
import {CalendarCheck2,CalendarClock,CalendarX2,CheckCircle2,ClipboardList,Clock3,Coins,HeartPulse,LibraryBig,RefreshCw,ShieldCheck,Sparkles,Stethoscope,Trophy,UserRound} from 'lucide-react';
import type {Member} from '../../types';
import {supabase} from '../../services/authService';
import '../../hiu-y-quan.css';

type PlayerState={active:boolean;display_name?:string|null;gender?:'male'|'female'|null;wallet_balance:number;total_cases:number;correct_cases:number;next_visit_at:string};
type Option={code:string;label:string};
type AppointmentStatus='none'|'pending'|'accepted'|'declined';
type ClinicCase={case_key:string;patient_age:number;patient_gender:'male'|'female';vong:string;van_am:string;van_hoi:string;thiet:string;options:Option[];completed:boolean;correct:boolean;credits_awarded:number;appointment_offered?:boolean;appointment_status?:AppointmentStatus;appointment_for_at?:string|null;appointment_decided_at?:string|null};
type SubmitResult={already_answered?:boolean;correct:boolean;credits_awarded:number;expected_label:string;explanation:string;wallet_balance:number};
type ClinicView='clinic'|'record'|'pharmacy'|'progress';
type ClinicScene='consult'|'ward'|'lab';

const emptyState:PlayerState={active:false,wallet_balance:0,total_cases:0,correct_cases:0,next_visit_at:new Date(Date.now()+3600000).toISOString()};
const genderLabel=(value:'male'|'female')=>value==='female'?'Nữ':'Nam';
const patientName=(patient:ClinicCase,index:number)=>`${patient.patient_gender==='female'?'Bệnh nhân nữ':'Bệnh nhân nam'} ${index+1}`;
const formatCountdown=(iso:string,now:number)=>{const ms=Math.max(0,Date.parse(iso)-now),m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};
const formatAppointment=(iso?:string|null)=>iso?new Date(iso).toLocaleString('vi-VN',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'khung giờ sắp tới';
const pharmacyDrawers=['Quế','Cam thảo','Trần bì','Bạch truật','Đương quy','Phục linh','Sa nhân','Ý dĩ','Mạch môn','Đan sâm','Ích mẫu','Kim ngân'];
const sceneOrder:ClinicScene[]=['consult','lab','ward'];
const sceneLabel:Record<ClinicScene,string>={consult:'Phòng Chẩn Mạch',ward:'Phòng Dưỡng Trị',lab:'Phòng Chế Dược'};

function DoctorAvatar({gender}:{gender:'male'|'female'}){
  return <div className={`hyq-doctor hyq-doctor--${gender}`} aria-label={`Thầy thuốc ${genderLabel(gender)}`}><span className="hyq-hair"/><span className="hyq-face"><i/><i/><b/></span><span className="hyq-neck"/><span className="hyq-robe"><i className="hyq-robe-cross"/><i className="hyq-belt"/></span><span className="hyq-sleeve left"/><span className="hyq-sleeve right"/></div>;
}
function PatientAvatar({gender}:{gender:'male'|'female'}){return <div className={`hyq-patient hyq-patient--${gender}`} aria-hidden="true"><span className="head"><i/><i/></span><span className="body"/></div>}

function AppointmentCard({item,busy,onDecision,compact=false}:{item:ClinicCase;busy:boolean;onDecision:(accept:boolean)=>void;compact?:boolean}){
  if(!item.appointment_offered)return null;
  const status=item.appointment_status||'pending';
  return <section className={`hyq-appointment hyq-appointment--${status}${compact?' compact':''}`}>
    <div className="hyq-appointment-copy"><CalendarClock/><div><b>Yêu cầu đặt lịch khám mô phỏng</b><span>Bệnh nhân muốn hẹn vào <strong>{formatAppointment(item.appointment_for_at)}</strong>.</span><small>Lịch chỉ thuộc HIU Y Quán, không phải lịch khám thực tế và không ảnh hưởng điểm chẩn thể.</small></div></div>
    {status==='pending'?<div className="hyq-appointment-actions"><button disabled={busy} className="accept" onClick={()=>onDecision(true)}><CalendarCheck2/>Nhận lịch</button><button disabled={busy} className="decline" onClick={()=>onDecision(false)}><CalendarX2/>Không nhận</button></div>:<div className="hyq-appointment-state">{status==='accepted'?<><CalendarCheck2/><b>Đã nhận lịch</b></>:<><CalendarX2/><b>Đã từ chối lịch</b></>}<span>{item.appointment_decided_at?`Xác nhận ${new Date(item.appointment_decided_at).toLocaleString('vi-VN')}`:'Quyết định đã được lưu'}</span></div>}
  </section>;
}

function GameRules(){
  return <details className="hyq-rules"><summary><span><Sparkles/><b>Luật chơi & cốt truyện</b></span><small>Mở hướng dẫn</small></summary><div className="hyq-rules-grid"><article><b>1 · Đón khách</b><p>Mỗi giờ có 1–2 bệnh nhân mô phỏng. Thầy thuốc tự về Phòng Chẩn Mạch khi còn ca đang chờ.</p></article><article><b>2 · Tứ chẩn</b><p>Đọc Vọng · Văn · Vấn · Thiết, chọn một thể bệnh. Mỗi ca chỉ ghi nhận lần chẩn đầu tiên.</p></article><article><b>3 · Dưỡng trị</b><p>Sau khi xử lý ca, hoạt cảnh chuyển sang giường theo dõi ngắn rồi thầy thuốc quay lại đón ca tiếp theo.</p></article><article><b>4 · Khi quán rảnh</b><p>Thầy thuốc tự đi giữa bàn khám, khu chế dược và phòng dưỡng trị. Hoạt cảnh chỉ phục vụ học tập, không phải hướng dẫn điều trị.</p></article></div></details>;
}

function ClinicWorld({doctorGender,doctorName,current,currentIndex,actorScene,focusScene,onFocus,actorAction,showWardPatient}:{doctorGender:'male'|'female';doctorName?:string|null;current:ClinicCase|null;currentIndex:number;actorScene:ClinicScene;focusScene:ClinicScene;onFocus:(scene:ClinicScene)=>void;actorAction:string;showWardPatient:boolean}){
  const waiting=Boolean(current&&!current.completed);
  return <section className="hyq-world-shell" aria-label="Phòng khám HIU Y Quán ba bối cảnh">
    <header className="hyq-scene-toolbar"><div><span className="hyq-live-dot"/><div><b>{actorAction}</b><small>Thầy thuốc đang ở {sceneLabel[actorScene]}</small></div></div><nav aria-label="Chọn bối cảnh">{(['consult','ward','lab'] as ClinicScene[]).map(scene=><button key={scene} className={focusScene===scene?'active':''} onClick={()=>onFocus(scene)}>{scene==='consult'?<Stethoscope/>:scene==='ward'?<HeartPulse/>:<LibraryBig/>}<span>{sceneLabel[scene]}</span></button>)}</nav></header>
    <div className="hyq-world" data-actor={actorScene} data-focus={focusScene}>
      <section className={`hyq-room hyq-room--consult ${focusScene==='consult'?'is-focus':''}`} data-scene="consult"><div className="hyq-room-title"><b>CHẨN MẠCH</b><small>Vọng · Văn · Vấn · Thiết</small></div><div className="hyq-world-window"><i/><i/></div><div className="hyq-world-cabinet"><b>TỦ DƯỢC</b>{Array.from({length:12},(_,i)=><span key={i}><small>{['Quế','Cam','Trần','Bạch'][i%4]}</small></span>)}</div><div className="hyq-world-desk"><i className="pillow"/><i className="teapot"/><b>BÀN BẮT MẠCH</b></div>{waiting&&current&&<div className="hyq-consult-patient"><PatientAvatar gender={current.patient_gender}/><div className="hyq-world-speech"><b>{patientName(current,currentIndex)} · {current.patient_age} tuổi</b><span>“Thầy thuốc xem giúp tôi với…”</span></div></div>} {!waiting&&<div className="hyq-room-status"><Clock3/><span>Bàn khám đang sẵn sàng</span></div>}</section>
      <section className={`hyq-room hyq-room--ward ${focusScene==='ward'?'is-focus':''}`} data-scene="ward"><div className="hyq-room-title"><b>DƯỠNG TRỊ</b><small>Giường theo dõi mô phỏng</small></div><div className="hyq-ward-screen"><i/><i/><i/></div><div className="hyq-bed"><span className="hyq-bed-pillow"/>{showWardPatient&&current?<span className={`hyq-bed-patient hyq-bed-patient--${current.patient_gender}`}><i className="head"/><i className="blanket"/></span>:<span className="hyq-bed-empty">Giường sẵn sàng</span>}<b>GIƯỜNG THEO DÕI</b></div><div className="hyq-ward-lamp"><i/></div><div className="hyq-room-status"><HeartPulse/><span>{showWardPatient?'Đang nghỉ và theo dõi sau ca':'Không có người bệnh lưu tại phòng'}</span></div></section>
      <section className={`hyq-room hyq-room--lab ${focusScene==='lab'?'is-focus':''}`} data-scene="lab"><div className="hyq-room-title"><b>CHẾ DƯỢC</b><small>Thực hành nhận diện dược liệu</small></div><div className="hyq-lab-shelf">{['Cam thảo','Bạch truật','Đương quy','Phục linh','Sa nhân','Ý dĩ'].map(x=><span key={x}>{x}</span>)}</div><div className="hyq-lab-table"><span className="hyq-mortar"><i/></span><span className="hyq-scale"><i/><i/></span><span className="hyq-herb-tray"><i/><i/><i/></span><b>BÀN CHẾ BIẾN</b></div><div className="hyq-herb-kettle"><i/><i/><i/></div><div className="hyq-room-status"><LibraryBig/><span>Dược liệu minh họa · không phải toa thuốc</span></div></section>
      <div className={`hyq-world-actor hyq-world-actor--${actorScene}`}><DoctorAvatar gender={doctorGender}/><span className="hyq-world-nameplate">{doctorName||'Thầy thuốc HIU'}</span></div>
      <div className="hyq-world-floor"/>
    </div>
  </section>;
}

export default function HiuYQuanGame({member}:{member:Member}){
  const [state,setState]=useState<PlayerState>(emptyState),[cases,setCases]=useState<ClinicCase[]>([]),[activeCase,setActiveCase]=useState(0),[selected,setSelected]=useState(''),[result,setResult]=useState<SubmitResult|null>(null),[busy,setBusy]=useState(false),[appointmentBusy,setAppointmentBusy]=useState(false),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now()),[view,setView]=useState<ClinicView>('clinic');
  const [name,setName]=useState(member.herbalAlias||member.fullName||''),[gender,setGender]=useState<'male'|'female'>('female'),[idleScene,setIdleScene]=useState<ClinicScene>('lab'),[focusScene,setFocusScene]=useState<ClinicScene>('consult'),[careUntil,setCareUntil]=useState(0);

  const load=async(clear=true)=>{if(clear)setMessage('');setBusy(true);try{const {data,error}=await supabase.rpc('hiu_y_quan_state_v1');if(error)throw error;const next={...emptyState,...(data||{})} as PlayerState;setState(next);if(next.active){let current=await supabase.rpc('hiu_y_quan_hourly_cases_v2');if(current.error&&/function|schema cache|does not exist/i.test(current.error.message||''))current=await supabase.rpc('hiu_y_quan_hourly_cases_v1');if(current.error)throw current.error;const rows=(Array.isArray(current.data)?current.data:[]) as ClinicCase[];setCases(rows);setActiveCase(i=>Math.min(i,Math.max(0,rows.length-1)))}}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{void load();const tick=window.setInterval(()=>setNow(Date.now()),1000),sync=window.setInterval(()=>void load(false),60000);return()=>{window.clearInterval(tick);window.clearInterval(sync)}},[member.id]);
  useEffect(()=>{setSelected('');setResult(null)},[activeCase]);

  const current=cases[activeCase]||null;
  const waitingCount=cases.filter(x=>!x.completed).length;
  const accuracy=state.total_cases?Math.round(state.correct_cases/state.total_cases*100):0;
  const nextVisit=useMemo(()=>formatCountdown(state.next_visit_at,now),[state.next_visit_at,now]);
  const completedThisHour=cases.filter(x=>x.completed).length;
  const actorScene:ClinicScene=current&&!current.completed?'consult':current?.completed&&now<careUntil?'ward':waitingCount>0?'consult':idleScene;
  const showWardPatient=Boolean(current?.completed&&now<careUntil);
  const actorAction=current&&!current.completed?'Đang tiếp nhận Tứ chẩn':showWardPatient?'Đang theo dõi người bệnh sau khám':actorScene==='lab'?'Đang chế biến dược liệu mô phỏng':actorScene==='ward'?'Đang kiểm tra phòng dưỡng trị':'Đang sắp xếp bàn chẩn mạch';

  useEffect(()=>{setFocusScene(actorScene)},[actorScene]);
  useEffect(()=>{if(waitingCount>0)return;const timer=window.setInterval(()=>{if(Date.now()<careUntil)return;setIdleScene(scene=>sceneOrder[(sceneOrder.indexOf(scene)+1)%sceneOrder.length])},6000);return()=>window.clearInterval(timer)},[waitingCount,careUntil]);
  useEffect(()=>{if(!current?.completed||waitingCount<1||now<careUntil)return;const nextIndex=cases.findIndex(x=>!x.completed);if(nextIndex>=0&&nextIndex!==activeCase)setActiveCase(nextIndex)},[now,careUntil,current?.completed,current?.case_key,waitingCount,cases,activeCase]);

  const activate=async()=>{const clean=name.replace(/\s+/g,' ').trim();if(clean.length<2){setMessage('Tên thầy thuốc cần ít nhất 2 ký tự.');return}setBusy(true);setMessage('');try{const {error}=await supabase.rpc('hiu_y_quan_activate_v1',{p_display_name:clean,p_gender:gender});if(error)throw error;await load(false)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const submit=async()=>{if(!current||!selected||current.completed||busy)return;setBusy(true);setMessage('');try{const {data,error}=await supabase.rpc('hiu_y_quan_submit_v1',{p_case_key:current.case_key,p_selected_code:selected});if(error)throw error;const next=data as SubmitResult;setResult(next);setCareUntil(Date.now()+6500);setFocusScene('ward');setState(s=>({...s,wallet_balance:next.wallet_balance,total_cases:s.total_cases+1,correct_cases:s.correct_cases+(next.correct?1:0)}));setCases(rows=>rows.map(x=>x.case_key===current.case_key?{...x,completed:true,correct:next.correct,credits_awarded:next.credits_awarded}:x))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const decideAppointment=async(accept:boolean)=>{if(!current||!current.appointment_offered||(current.appointment_status||'pending')!=='pending'||appointmentBusy)return;setAppointmentBusy(true);setMessage('');try{const {data,error}=await supabase.rpc('hiu_y_quan_appointment_decide_v2',{p_case_key:current.case_key,p_accept:accept});if(error)throw error;const status=String(data?.status||'') as AppointmentStatus,decided=String(data?.decided_at||new Date().toISOString());setCases(rows=>rows.map(x=>x.case_key===current.case_key?{...x,appointment_status:status,appointment_decided_at:decided}:x));setMessage(status==='accepted'?'Đã nhận lịch khám mô phỏng của bệnh nhân.':'Đã ghi nhận không nhận lịch khám mô phỏng này.')}catch(e){setMessage((e as Error).message)}finally{setAppointmentBusy(false)}};
  const openCase=(index:number)=>{const item=cases[index];setActiveCase(index);setFocusScene(item?.completed?'ward':'consult');setCareUntil(item?.completed?Date.now()+5000:0)};

  if(!state.active)return <section className="hyq-page hyq-onboarding"><div className="hyq-onboarding-card"><div className="hyq-seal"><Stethoscope/></div><span className="hyq-kicker">HIU · Y · QUÁN</span><h2>Khai trương phòng khám của bạn</h2><p>Game mô phỏng học tập Y học cổ truyền. Tình huống chỉ dùng để luyện nhận diện thể bệnh, không dùng chẩn đoán người bệnh thực tế.</p><label>Tên thầy thuốc<input value={name} maxLength={40} onChange={e=>setName(e.target.value)} placeholder="Nhập tên nhân vật"/></label><div className="hyq-gender"><button type="button" className={gender==='female'?'active':''} onClick={()=>setGender('female')}><UserRound/>Nữ</button><button type="button" className={gender==='male'?'active':''} onClick={()=>setGender('male')}><UserRound/>Nam</button></div><div className="hyq-avatar-preview"><DoctorAvatar gender={gender}/><div><b>{name.trim()||'Thầy thuốc HIU'}</b><small>Trang phục YHCT 2D nguyên bản · {genderLabel(gender)}</small></div></div>{message&&<div className="hyq-message">{message}</div>}<button className="hyq-primary" disabled={busy} onClick={()=>void activate()}><Sparkles/>{busy?'Đang kích hoạt…':'Kích hoạt HIU - Y - Quán'}</button></div></section>;

  return <section className="hyq-page hyq-page--v12">
    <header className="hyq-header"><div><span className="hyq-kicker"><Sparkles/> HIU · Y · QUÁN</span><h2>Phòng khám Y học cổ truyền</h2><p>Game 2D ba bối cảnh · Tứ chẩn → nhận diện thể bệnh → theo dõi mô phỏng → vận hành quán.</p></div><button className="hyq-refresh" disabled={busy} onClick={()=>void load()}><RefreshCw/>Làm mới</button></header>
    <div className="hyq-hud"><article><Coins/><span><small>Tín dụng Gia Viên</small><b>{state.wallet_balance}</b></span></article><article><HeartPulse/><span><small>Ca đã xử lý</small><b>{state.total_cases}</b></span></article><article><CheckCircle2/><span><small>Tỷ lệ đúng</small><b>{accuracy}%</b></span></article><article><Clock3/><span><small>Đợt khách mới</small><b>{nextVisit}</b></span></article></div>
    {message&&<div className="hyq-message">{message}</div>}
    <GameRules/>
    <nav className="hyq-view-tabs" aria-label="Khu vực HIU Y Quán"><button className={view==='clinic'?'active':''} onClick={()=>setView('clinic')}><Stethoscope/><span><b>Khám bệnh</b><small>Ba phòng & chẩn thể</small></span></button><button className={view==='record'?'active':''} onClick={()=>setView('record')}><ClipboardList/><span><b>Hồ sơ ca</b><small>Tóm tắt Tứ chẩn</small></span></button><button className={view==='pharmacy'?'active':''} onClick={()=>setView('pharmacy')}><LibraryBig/><span><b>Dược phòng</b><small>Tủ dược học tập</small></span></button><button className={view==='progress'?'active':''} onClick={()=>setView('progress')}><Trophy/><span><b>Thành tích</b><small>Tiến độ cá nhân</small></span></button></nav>

    {view==='clinic'&&<div className="hyq-clinic-view hyq-clinic-view--v12"><ClinicWorld doctorGender={(state.gender||'female') as 'male'|'female'} doctorName={state.display_name} current={current} currentIndex={activeCase} actorScene={actorScene} focusScene={focusScene} onFocus={setFocusScene} actorAction={actorAction} showWardPatient={showWardPatient}/><div className="hyq-workspace"><aside className="hyq-queue"><header><b>Khách trong giờ</b><small>{cases.length} ca · {waitingCount} chờ</small></header>{cases.map((item,i)=><button key={item.case_key} className={`${i===activeCase?'active':''} ${item.completed?'done':''}`} onClick={()=>openCase(i)}><span>{i+1}</span><div><b>{patientName(item,i)}</b><small>{item.patient_age} tuổi · {item.appointment_offered?'có yêu cầu lịch · ':''}{item.completed?(item.correct?'Đã chẩn đúng':'Đã xử lý'):'Đang chờ'}</small></div>{item.completed&&<CheckCircle2/>}</button>)}</aside><main className="hyq-case-panel">{current?<><div className="hyq-four-exams"><article><b>VỌNG</b><p>{current.vong}</p></article><article><b>VĂN</b><p>{current.van_am}</p></article><article><b>VẤN</b><p>{current.van_hoi}</p></article><article><b>THIẾT</b><p>{current.thiet}</p></article></div><AppointmentCard item={current} busy={appointmentBusy} onDecision={accept=>void decideAppointment(accept)}/><div className="hyq-diagnosis"><header><div><ShieldCheck/><span><b>Chẩn thể bệnh</b><small>Chọn 1 đáp án. Mỗi ca chỉ được tính tín dụng một lần.</small></span></div><em>+1 tín dụng nếu đúng</em></header><div className="hyq-options">{current.options.map(option=><button key={option.code} disabled={current.completed||busy} className={selected===option.code?'selected':''} onClick={()=>setSelected(option.code)}><span/>{option.label}</button>)}</div><button className="hyq-primary" disabled={!selected||current.completed||busy} onClick={()=>void submit()}>{busy?'Đang đối chiếu…':'Xác nhận chẩn đoán'}</button></div>{result&&<div className={`hyq-result ${result.correct?'correct':'wrong'}`}><b>{result.correct?`Chính xác · +${result.credits_awarded} tín dụng`:'Chưa chính xác'}</b><p>Đáp án: <strong>{result.expected_label}</strong>. {result.explanation}</p></div>}{current.completed&&!result&&<div className={`hyq-result ${current.correct?'correct':'wrong'}`}><b>{current.correct?`Ca này đã chẩn đúng · +${current.credits_awarded} tín dụng`:'Ca này đã được xử lý'}</b><p>Chọn ca khác hoặc quan sát hoạt cảnh vận hành phòng khám phía trên.</p></div>}</>:<div className="hyq-no-case"><Clock3/><h3>Chưa có ca trong khung giờ này</h3><p>Hệ thống phát 1–2 khách ngẫu nhiên mỗi giờ. Khi quán rảnh, thầy thuốc tự tuần tra ba bối cảnh.</p></div>}</main></div></div>}

    {view==='record'&&<section className="hyq-view-panel hyq-record-view"><header><div><ClipboardList/><span><b>Hồ sơ ca hiện tại</b><small>Chỉ hiển thị dữ liệu tình huống đang được hệ thống cấp.</small></span></div>{current&&<span className={`hyq-case-state ${current.completed?'done':'waiting'}`}>{current.completed?'Đã xử lý':'Đang chờ chẩn'}</span>}</header>{current?<><div className="hyq-record-patient"><PatientAvatar gender={current.patient_gender}/><div><b>{patientName(current,activeCase)}</b><span>{current.patient_age} tuổi · {genderLabel(current.patient_gender)}</span><small>Ca {activeCase+1}/{cases.length} trong đợt khách hiện tại</small></div></div><div className="hyq-record-grid"><article><b>Vọng</b><p>{current.vong}</p></article><article><b>Văn</b><p>{current.van_am}</p></article><article><b>Vấn</b><p>{current.van_hoi}</p></article><article><b>Thiết</b><p>{current.thiet}</p></article></div><AppointmentCard item={current} busy={appointmentBusy} compact onDecision={accept=>void decideAppointment(accept)}/><button className="hyq-primary hyq-back-clinic" onClick={()=>setView('clinic')}><Stethoscope/>Mở bàn chẩn thể</button></>:<div className="hyq-no-case"><Clock3/><h3>Chưa có hồ sơ ca</h3><p>Hồ sơ sẽ xuất hiện khi hệ thống cấp khách trong giờ.</p></div>}</section>}

    {view==='pharmacy'&&<section className="hyq-view-panel hyq-pharmacy-view"><header><div><LibraryBig/><span><b>Dược phòng HIU</b><small>Không gian nhận diện dược liệu trong game; không phải khu kê đơn.</small></span></div><span className="hyq-wallet-chip"><Coins/>{state.wallet_balance} tín dụng</span></header><div className="hyq-pharmacy-room"><div className="hyq-pharmacy-sign">HIU · DƯỢC PHÒNG<small>Tủ dược học tập</small></div><div className="hyq-drawer-grid">{pharmacyDrawers.map((label,i)=><div key={label}><span>{label}</span><i>{String(i+1).padStart(2,'0')}</i></div>)}</div><div className="hyq-pharmacy-counter"><span/><b>Dược liệu mô phỏng</b><small>Các ngăn tủ là thành phần minh họa giao diện, không thể hiện đơn thuốc của người bệnh.</small></div></div><div className="hyq-pharmacy-notes"><article><ShieldCheck/><div><b>An toàn học tập</b><p>HIU Y Quán chỉ luyện tư duy Tứ chẩn và nhận diện thể bệnh; không sinh toa thuốc hoặc hướng dẫn điều trị cá nhân.</p></div></article><article><Sparkles/><div><b>Kết nối Gia Viên</b><p>Tín dụng nhận từ ca chẩn đúng được đồng bộ vào cùng ví Gia Viên hiện có.</p></div></article></div></section>}

    {view==='progress'&&<section className="hyq-view-panel hyq-progress-view"><header><div><Trophy/><span><b>Thành tích thầy thuốc</b><small>Dữ liệu lấy trực tiếp từ hồ sơ game hiện tại.</small></span></div><span className="hyq-doctor-badge">{state.display_name||'Thầy thuốc HIU'}</span></header><div className="hyq-progress-hero"><DoctorAvatar gender={(state.gender||'female') as 'male'|'female'}/><div><span>Tỷ lệ chẩn đúng</span><strong>{accuracy}%</strong><div className="hyq-progress-track"><i style={{width:`${Math.max(0,Math.min(100,accuracy))}%`}}/></div><small>{state.correct_cases}/{state.total_cases} ca đúng toàn thời gian</small></div></div><div className="hyq-progress-grid"><article><Coins/><span><small>Tín dụng hiện có</small><b>{state.wallet_balance}</b></span></article><article><HeartPulse/><span><small>Ca đã xử lý</small><b>{state.total_cases}</b></span></article><article><CheckCircle2/><span><small>Ca đúng</small><b>{state.correct_cases}</b></span></article><article><Clock3/><span><small>Đợt hiện tại</small><b>{completedThisHour}/{cases.length}</b></span></article></div><div className="hyq-next-visit"><Clock3/><div><b>Khách mới sau {nextVisit}</b><span>Quán tự đồng bộ khi sang đợt tiếp theo; không cần tải lại liên tục.</span></div></div></section>}
    <footer className="hyq-safety">Mô phỏng giáo dục · 20 thể bệnh YHCT cơ bản · ba bối cảnh chỉ phục vụ cốt truyện học tập · lịch hẹn chỉ trong game · không phải công cụ chẩn đoán, đặt lịch y tế hay kê đơn lâm sàng.</footer>
  </section>;
}
