import * as XLSX from 'xlsx';

type ImportRow={mssv:string;ho_ten:string;ten_hoat_dong:string;hoc_ky:string;diem_cong:string;ghi_chu:string;occurred_at?:string};
type RowError={row:number;field:'MSSV'|'Họ tên'|'Tên hoạt động'|'Học kỳ'|'Điểm cộng';value:string;message:string};
type ImportMeta={format:'hiu_drl_proposal'|'flat';sheet_name:string;header_row:number;activity_name:string;semester_label:string;academic_year:string;occurred_at?:string;location:string;suggested_semester_code:string;suggested_semester_title:string};
type ColMap={stt:number;mssv:number;name:number;faculty:number;role:number;points:number;activity:number;semester:number;note:number;occurred:number};
const key=(s:unknown)=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const text=(v:unknown,max:number)=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max);
const aliases={stt:['stt','so_thu_tu'],mssv:['mssv','ma_sinh_vien','student_code'],name:['ho_va_ten','ho_ten','hoten','full_name'],faculty:['khoa','faculty','department'],role:['vai_tro_tham_gia','vai_tro','tham_gia','role'],points:['diem_de_xuat_drl','diem_de_xuat','drl','diem_cong','diem','points'],activity:['ten_hoat_dong','hoat_dong','activity_name'],semester:['hoc_ky','hocky','semester'],note:['ghi_chu','ghichu','note'],occurred:['thoi_gian_to_chuc','ngay_to_chuc','occurred_at']};
const findCol=(row:unknown[],list:string[])=>row.findIndex(v=>list.includes(key(v)));
function findHeader(matrix:unknown[][]){for(let i=0;i<Math.min(matrix.length,80);i++){const row=matrix[i]||[];const map:ColMap={stt:findCol(row,aliases.stt),mssv:findCol(row,aliases.mssv),name:findCol(row,aliases.name),faculty:findCol(row,aliases.faculty),role:findCol(row,aliases.role),points:findCol(row,aliases.points),activity:findCol(row,aliases.activity),semester:findCol(row,aliases.semester),note:findCol(row,aliases.note),occurred:findCol(row,aliases.occurred)};if(map.mssv>=0&&map.name>=0&&map.points>=0)return{index:i,map}}throw new Error('Không nhận diện được cấu trúc cột [MSSV, Họ tên, Tên hoạt động, Học kỳ, Điểm cộng].')}
function nearestRight(row:unknown[],from:number){for(let j=from+1;j<Math.min(row.length,from+6);j++){const v=text(row[j],500);if(v)return v}return''}
function metaValue(matrix:unknown[][],end:number,labels:string[]){for(let i=0;i<end;i++){const row=matrix[i]||[];for(let j=0;j<row.length;j++)if(labels.includes(key(row[j])))return nearestRight(row,j)}return''}
function toIsoDate(value:string){const m=value.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);if(!m)return'';const d=Number(m[1]),mo=Number(m[2]),y=Number(m[3]);if(d<1||d>31||mo<1||mo>12)return'';return`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}T00:00:00+07:00`}
function semesterCode(label:string,year:string){const n=(label.match(/\d+/)||[])[0]||'';const y=(year.match(/20\d{2}\s*[-–]\s*20\d{2}/)||[])[0]?.replace(/\s/g,'').replace('–','-')||'';return n&&y?`HK${n}-${y}`:''}
function logicalKey(mssv:string,activity:string,semester:string){return`${mssv}|${key(activity)}|${key(semester)}`}
self.onmessage=(event:MessageEvent<ArrayBuffer>)=>{try{const wb=XLSX.read(event.data,{type:'array',cellDates:true,cellFormula:false,cellHTML:false,cellStyles:false}),first=wb.SheetNames[0];if(!first)throw new Error('Workbook không có sheet.');const matrix=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[first],{header:1,defval:'',raw:false,blankrows:true});const {index:headerIndex,map}=findHeader(matrix);const activityMeta=metaValue(matrix,headerIndex,['ten_hoat_dong']),semesterMeta=metaValue(matrix,headerIndex,['hoc_ky']),academicYear=metaValue(matrix,headerIndex,['nam_hoc']),occurredMeta=metaValue(matrix,headerIndex,['thoi_gian_to_chuc','ngay_to_chuc']),location=metaValue(matrix,headerIndex,['dia_diem']);const structured=Boolean(activityMeta&&semesterMeta&&map.activity<0&&map.semester<0),suggestedCode=semesterCode(semesterMeta,academicYear),suggestedTitle=[semesterMeta,academicYear?`Năm học ${academicYear}`:''].filter(Boolean).join(' · ');const rows:ImportRow[]=[],rowErrors:RowError[]=[];let invalid=0,duplicateRows=0;const seenCodes=new Set<string>(),duplicateCodes=new Set<string>(),seenLogical=new Set<string>();
for(let i=headerIndex+1;i<matrix.length;i++){const row=matrix[i]||[],rowNo=i+1,mssv=text(row[map.mssv],20).replace(/\s/g,'').toUpperCase(),name=text(row[map.name],160),rawPoints=text(row[map.points],40).replace(',','.'),stt=map.stt>=0?text(row[map.stt],20):'';if(!mssv&&!name&&!rawPoints)continue;if(!mssv&&stt&&!/^\d+$/.test(stt))continue;const activity=map.activity>=0?text(row[map.activity],240):text(activityMeta,240),semester=(map.semester>=0?text(row[map.semester],80):text(semesterMeta,80)).toUpperCase(),points=Number(rawPoints),noteParts:string[]=[];const note=map.note>=0?text(row[map.note],500):'';if(note)noteParts.push(note);const faculty=map.faculty>=0?text(row[map.faculty],120):'';if(faculty)noteParts.push(`Khoa: ${faculty}`);const role=map.role>=0?text(row[map.role],120):'';if(role)noteParts.push(`Vai trò: ${role}`);const occurredRaw=map.occurred>=0?text(row[map.occurred],64):occurredMeta,occurred=toIsoDate(occurredRaw)||text(occurredRaw,64);const item:ImportRow={mssv,ho_ten:name,ten_hoat_dong:activity,hoc_ky:semester,diem_cong:rawPoints,ghi_chu:noteParts.join(' · ')};if(occurred)item.occurred_at=occurred;const errors:RowError[]=[];if(!/^\d{8,14}$/.test(mssv))errors.push({row:rowNo,field:'MSSV',value:mssv,message:'MSSV phải gồm 8–14 chữ số.'});if(!name)errors.push({row:rowNo,field:'Họ tên',value:name,message:'Họ tên không được trống.'});if(!activity)errors.push({row:rowNo,field:'Tên hoạt động',value:activity,message:'Tên hoạt động không được trống.'});if(!semester)errors.push({row:rowNo,field:'Học kỳ',value:semester,message:'Học kỳ không được trống.'});if(!Number.isFinite(points))errors.push({row:rowNo,field:'Điểm cộng',value:rawPoints,message:'Điểm cộng phải là số.'});else if(points<0)errors.push({row:rowNo,field:'Điểm cộng',value:rawPoints,message:'Điểm cộng không được âm.'});else if(!Number.isInteger(points))errors.push({row:rowNo,field:'Điểm cộng',value:rawPoints,message:'Điểm cộng phải là số nguyên.'});else if(points>1000)errors.push({row:rowNo,field:'Điểm cộng',value:rawPoints,message:'Điểm cộng vượt giới hạn 1000.'});if(errors.length){invalid++;rowErrors.push(...errors);continue}if(seenCodes.has(mssv))duplicateCodes.add(mssv);else seenCodes.add(mssv);const identity=logicalKey(mssv,activity,semester);if(seenLogical.has(identity)){duplicateRows++;continue}seenLogical.add(identity);rows.push(item);if(rows.length>5000)throw new Error('Tối đa 5.000 dòng mỗi lần nhập.')}
if(!rows.length&&rowErrors.length)throw new Error(`Không có dòng hợp lệ. Lỗi đầu tiên: dòng ${rowErrors[0].row} - ${rowErrors[0].message}`);if(!rows.length)throw new Error('Không tìm thấy dòng dữ liệu điểm.');const meta:ImportMeta={format:structured?'hiu_drl_proposal':'flat',sheet_name:first,header_row:headerIndex+1,activity_name:activityMeta,semester_label:semesterMeta,academic_year:academicYear,location,suggested_semester_code:suggestedCode,suggested_semester_title:suggestedTitle};const iso=toIsoDate(occurredMeta);if(iso)meta.occurred_at=iso;self.postMessage({ok:true,rows,invalid,duplicateStudentCodes:duplicateCodes.size,duplicateRows,rowErrors:rowErrors.slice(0,200),meta})}catch(error){self.postMessage({ok:false,error:error instanceof Error?error.message:'Không thể đọc bảng tính.'})}};
export {};
