import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Bot,Database,ExternalLink,FileText,FolderOpen,HardDrive,Languages,Lightbulb,LockKeyhole,Search,Sparkles,UploadCloud,WandSparkles} from 'lucide-react';
import type {Member} from '../../types';
import {askServerAi,type AiRuntimeAnswer} from '../../services/aiRuntimeService';
import {extractiveSummary,ingestLocalFiles,listPublicDriveFolder,loadPersistedRagDocuments,persistRagDocuments,retrieveLocalRag,searchClinicalTrials,searchOpenAlex,searchPubMed,type RagDocument,type ResearchWork} from '../../services/researchService';
import {consumeGuestSearchQuota,formatQuotaCountdown,GUEST_SEARCH_LIMIT,readGuestSearchQuota,suggestResearchTopics} from '../../services/researchLocalAi';
import ResearchAiMini from './ResearchAiMini';
import ResearchProposalBuilder from './ResearchProposalBuilder';

const dedupeDocs=(docs:RagDocument[])=>[...new Map(docs.map(d=>[d.id,d])).values()];
const dedupeWorks=(works:ResearchWork[])=>[...new Map(works.map(w=>[(w.doi||w.url||w.title).toLowerCase(),w])).values()];
const providerClass=(provider:string)=>provider.toLowerCase().replace(/[^a-z0-9]+/g,'-');

type Props={member:Member|null;onLogin?:()=>void};

export default function ResearchCenter({member,onLogin}:Props){
  const [q,setQ]=useState(''),[works,setWorks]=useState<ResearchWork[]>([]),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[docs,setDocs]=useState<RagDocument[]>([]),[hydrated,setHydrated]=useState(false),[ragQ,setRagQ]=useState(''),[summary,setSummary]=useState(''),[aiAnswer,setAiAnswer]=useState<AiRuntimeAnswer|null>(null),[aiBusy,setAiBusy]=useState(false),[proposalOpen,setProposalOpen]=useState(false),[proposalTitle,setProposalTitle]=useState('');
  const [quota,setQuota]=useState(()=>readGuestSearchQuota()),[now,setNow]=useState(Date.now());
  const login=()=>{if(onLogin){onLogin();return}const button=document.querySelector<HTMLButtonElement>('.mobile-account-button, aside footer button');button?.click()};
  useEffect(()=>{document.documentElement.classList.add('research-route-active');return()=>document.documentElement.classList.remove('research-route-active')},[]);
  useEffect(()=>{let alive=true;void loadPersistedRagDocuments().then(x=>{if(alive){setDocs(x);setHydrated(true)}});return()=>{alive=false}},[]);
  useEffect(()=>{if(hydrated)void persistRagDocuments(docs)},[docs,hydrated]);
  useEffect(()=>{if(member)return;const id=window.setInterval(()=>{const t=Date.now();setNow(t);setQuota(readGuestSearchQuota(t))},1000);return()=>window.clearInterval(id)},[member]);
  const ragResults=useMemo(()=>retrieveLocalRag(ragQ,docs,6),[ragQ,docs]);
  const topics=useMemo(()=>suggestResearchTopics(q,works,3),[q,works]);
  const openProposal=(title='')=>{if(!member){login();return}setProposalTitle(title);setProposalOpen(true)};
  const search=async()=>{
    const query=q.trim();if(!query||busy)return;
    if(!member){const current=readGuestSearchQuota();if(current.remaining<=0){setQuota(current);setErr(`Khách đã dùng đủ ${GUEST_SEARCH_LIMIT} lượt tra cứu. Đăng nhập thành viên để tra cứu không giới hạn.`);return}setQuota(consumeGuestSearchQuota())}
    setBusy(true);setErr('');setAiAnswer(null);setSummary('');
    try{
      const results=await Promise.allSettled([searchPubMed(query,12),searchOpenAlex(query,12),searchClinicalTrials(query,8)]),merged=dedupeWorks(results.flatMap(x=>x.status==='fulfilled'?x.value:[]));
      setWorks(merged);
      const failures=results.filter((x):x is PromiseRejectedResult=>x.status==='rejected').map(x=>(x.reason as Error)?.message).filter(Boolean);
      if(!merged.length)setErr(failures.length?failures.join(' · '):'Không tìm thấy kết quả phù hợp. Hãy thử từ khóa tiếng Anh hoặc câu hỏi ngắn hơn.');else if(failures.length)setErr(`Một nguồn chưa phản hồi: ${failures.join(' · ')}`);
    }finally{setBusy(false)}
  };
  const importLocal=async(files:FileList|null)=>{if(!files)return;setBusy(true);try{const incoming=await ingestLocalFiles(Array.from(files));setDocs(x=>dedupeDocs([...x,...incoming]))}finally{setBusy(false)}};
  const importDrive=async()=>{setBusy(true);setErr('');try{const incoming=await listPublicDriveFolder();setDocs(x=>dedupeDocs([...x,...incoming]))}catch(e){setErr((e as Error).message)}finally{setBusy(false)}};
  const summarize=()=>{const text=ragResults.map(r=>r.document.text||r.snippet).join('\n');setSummary(extractiveSummary(text,6)||'Chưa có đủ nội dung văn bản để tóm tắt.');setAiAnswer(null)};
  const synthesize=async()=>{const query=ragQ.trim();if(!member){login();return}if(!query||!ragResults.length)return;setAiBusy(true);setErr('');setAiAnswer(null);try{const sources=ragResults.slice(0,6).map(r=>({id:r.document.id,title:r.document.name,text:(r.document.text||r.snippet).slice(0,4200),url:r.document.url||null}));setAiAnswer(await askServerAi(query,'research',sources))}catch(e){setErr((e as Error).message)}finally{setAiBusy(false)}};
  const remaining=member?'∞':String(quota.remaining),countdown=formatQuotaCountdown(quota.msUntilReset-(Date.now()-now));

  return <section className="research-center research-center-v2">
    <div className="research-hero"><div className="research-hero-copy"><span className="kicker">TRUNG TÂM NGHIÊN CỨU Y DƯỢC CỔ TRUYỀN HIU 4.0</span><h2>Research Center <Sparkles/></h2><p>A.I học thuật local-first · PubMed · OpenAlex · ClinicalTrials.gov · RAG · tạo thuyết minh nghiên cứu.</p>{member?<span className="research-access-pill member"><Bot/> Thành viên: A.I trong ứng dụng không giới hạn lượt</span>:<span className="research-access-pill guest"><LockKeyhole/> Khách: còn {remaining}/{GUEST_SEARCH_LIMIT} lượt tra cứu · reset {countdown}</span>}</div><div className="research-hero-stats"><div className="research-stat"><Database/><strong>{works.length}</strong><span>kết quả y văn</span></div><div className="research-stat"><HardDrive/><strong>{docs.length}</strong><span>tài liệu RAG</span></div></div></div>

    <section className="research-ai-hub" aria-label="Công cụ A.I nghiên cứu"><div className="research-ai-hub-copy"><span className="kicker">A.I LÀ TRỌNG TÂM</span><h3><Bot/> Trợ lý A.I học thuật</h3><p>Thành viên có A.I Mini riêng tại Trung tâm nghiên cứu: hỏi y văn có nguồn, dịch local 0đ khi Chrome hỗ trợ, gợi ý đề tài và tạo Word Mẫu 01-SV.</p></div><div className="research-ai-tools"><article><Bot/><b>Hỏi A.I có nguồn</b><small>Ưu tiên kết quả vừa tìm và kho RAG.</small></article><article><Languages/><b>Dịch tài liệu 0đ</b><small>Local Chrome Built-in AI khi thiết bị hỗ trợ.</small></article><article><Lightbulb/><b>Gợi ý đề tài</b><small>Dựa trên từ khóa và khoảng trống y văn, không bịa tính mới.</small></article><article><WandSparkles/><b>Tạo đề cương Word</b><small>Điền Mẫu 01-SV, A.I hỗ trợ nội dung và xuất DOCX.</small></article></div><div className="research-ai-hub-actions">{member?<><button onClick={()=>openProposal(topics[0]?.title||q)}><FileText/> Tạo thuyết minh nghiên cứu</button><span>Research A.I Mini nằm ở góc dưới màn hình.</span></>:<><button onClick={login}><LockKeyhole/> Đăng nhập để mở A.I</button><span>Khách vẫn có 3 lượt tra cứu y văn trong mỗi chu kỳ 24 giờ.</span></>}</div></section>

    <div className="research-grid"><section className="research-card literature"><div className="research-card-head"><div><h3><BookOpen/> Tra cứu y văn & dữ liệu nghiên cứu công khai</h3><p className="muted">Tìm song song 3 nguồn; thành viên không áp giới hạn lượt trong ứng dụng.</p></div>{!member&&<div className="guest-quota-badge"><b>{quota.remaining}</b><span>lượt còn lại</span></div>}</div><div className="research-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ví dụ: acupuncture insomnia randomized trial" onKeyDown={e=>e.key==='Enter'&&void search()}/><button onClick={()=>void search()} disabled={busy||(!member&&quota.remaining<=0)}><Search/>{busy?'Đang tìm…':'Tìm 3 nguồn'}</button></div>{!member&&quota.remaining<=0&&<button className="secondary guest-login-cta" onClick={login}><LockKeyhole/> Đăng nhập để tiếp tục tra cứu</button>}{err&&<div className="error" role="status">{err}</div>}
      {works.length>0&&<div className="research-topic-strip"><span><Lightbulb/> Đề tài gợi ý:</span>{topics.map(t=><button key={t.title} disabled={!member} title={member?'Tạo đề cương từ gợi ý này':'Đăng nhập để dùng A.I gợi ý đề tài'} onClick={()=>openProposal(t.title)}>{t.title}</button>)}</div>}
      <div className="works-list">{works.map(w=><article key={`${w.provider}-${w.id}`}><div><span className={`provider ${providerClass(w.provider)}`}>{w.provider}</span>{w.year&&<small>{w.year}</small>}{typeof w.citedBy==='number'&&<small>{w.citedBy} trích dẫn</small>}</div><h4>{w.title}</h4><p>{w.authors.slice(0,5).join(', ')||'Không rõ tác giả'} · {w.source}</p>{w.abstract&&<p className="work-abstract">{w.abstract.slice(0,650)}{w.abstract.length>650?'…':''}</p>}<a href={w.url} target="_blank" rel="noreferrer noopener"><ExternalLink size={15}/> Mở nguồn gốc</a></article>)}</div></section>

      <aside className="research-card rag"><h3><Sparkles/> Drive / Local RAG</h3><p className="muted">Tài liệu cục bộ được lập chỉ mục trên thiết bị. Kho Google Drive dùng cấu hình server-side; secret không đi vào trình duyệt.</p>{member?.role==='admin'&&<div className="drive-connect"><button onClick={()=>void importDrive()} disabled={busy}><FolderOpen/> Đồng bộ kho Drive đã cấu hình</button></div>}<label className="local-upload"><UploadCloud/><span><b>Nhập thư mục/tệp cục bộ</b><small>TXT, MD, CSV, JSON, HTML được lập chỉ mục trực tiếp trên thiết bị.</small></span><input type="file" multiple {...({webkitdirectory:''} as any)} onChange={e=>void importLocal(e.target.files)}/></label><div className="doc-list">{docs.slice(0,12).map(d=><div key={d.id}><FileText/><span><b>{d.name}</b><small>{d.source} · {d.mime||'unknown'}</small></span></div>)}</div><label>Hỏi kho tài liệu</label><textarea value={ragQ} onChange={e=>{setRagQ(e.target.value);setAiAnswer(null)}} placeholder="Ví dụ: tài liệu nào đề cập chứng Tâm tỳ lưỡng hư?"/><div className="schedule-actions"><button onClick={summarize} disabled={!ragResults.length}><Sparkles/> Tóm tắt local</button><button className="secondary" onClick={()=>void synthesize()} disabled={aiBusy||!ragQ.trim()||!ragResults.length}>{member?<><Bot/>{aiBusy?'A.I đang tổng hợp…':'A.I tổng hợp có nguồn'}</>:<><LockKeyhole/> Cần đăng nhập</>}</button></div>{!member&&ragResults.length>0&&<p className="muted">Đăng nhập thành viên để dùng A.I tổng hợp có kiểm soát nguồn.</p>}{summary&&<div className="rag-summary"><b>Tóm tắt trích xuất local</b><p>{summary}</p></div>}{aiAnswer&&<div className="rag-summary"><b>A.I tổng hợp · {aiAnswer.provider}{aiAnswer.degraded?' · fallback local':''}</b><p>{aiAnswer.answer}</p><small>Độ tin cậy: {aiAnswer.confidence} · Trạng thái: {aiAnswer.safety}</small>{aiAnswer.citations.length>0&&<div className="tags">{aiAnswer.citations.map(c=>c.url?<a key={c.id} href={c.url} target="_blank" rel="noreferrer noopener">{c.label}</a>:<span key={c.id}>{c.label}</span>)}</div>}</div>}<div className="rag-results">{ragResults.map(r=><article key={r.document.id}><b>{r.document.name}</b><small>Độ phù hợp {Math.round(r.score*100)}%</small><p>{r.snippet}</p></article>)}</div></aside></div>

    {member&&<ResearchAiMini member={member} works={works} query={q} onOpenProposal={openProposal}/>} {member&&proposalOpen&&<ResearchProposalBuilder member={member} works={works} initialTitle={proposalTitle||q} onClose={()=>setProposalOpen(false)}/>} 
  </section>;
}
