import {useEffect,useMemo,useState} from 'react';
import {Bot,Download,FileText,Sparkles,X} from 'lucide-react';
import type {Member} from '../../types';
import {supabase} from '../../services/authService';
import type {ResearchWork} from '../../services/researchService';
import {buildLocalProposalSections,suggestResearchTopics} from '../../services/researchLocalAi';
import {downloadResearchProposalDocx,type ProposalFormData} from '../../services/researchProposalDocx';

type Props={member:Member;works:ResearchWork[];initialTitle?:string;onClose:()=>void};
const clean=(v:string)=>v.replace(/\s+/g,' ').trim();
const defaultForm=(member:Member,title=''):ProposalFormData=>({title,chairName:member.fullName||'',studentCode:member.studentCode||'',className:'',studentYear:'',faculty:'Khoa Y - Trường Đại học Quốc tế Hồng Bàng',phone:member.phone||'',email:member.email||'',address:'',adviserName:'',adviserDegree:'',adviserSpecialty:'',adviserUnit:'Khoa Y - Trường Đại học Quốc tế Hồng Bàng',adviserPhone:'',adviserEmail:'',adviserAddress:'',durationMonths:'12',teamMembers:'',overview:'',significance:'',objectives:'',populationScope:'',location:'',mainContents:'',methods:'',expectedResults:'',reportOutline:'',assignments:'',totalBudget:'',progress:'',specialNeeds:'',references:''});
const DESIGNS=['Scoping review','Systematic review','Cross-sectional study','Feasibility study','Cohort study','Case-control study','Experimental study'];

export default function ResearchProposalBuilder({member,works,initialTitle='',onClose}:Props){
  const [form,setForm]=useState<ProposalFormData>(()=>defaultForm(member,initialTitle)),[design,setDesign]=useState('Cross-sectional study'),[busy,setBusy]=useState(false),[note,setNote]=useState('');
  const topics=useMemo(()=>suggestResearchTopics(form.title||initialTitle,works,4),[form.title,initialTitle,works]);
  useEffect(()=>{if(initialTitle&&!form.title)setForm(f=>({...f,title:initialTitle}))},[initialTitle,form.title]);
  const set=(key:keyof ProposalFormData,value:string)=>setForm(current=>({...current,[key]:value}));
  const localAssist=()=>{if(clean(form.title).length<5){setNote('Hãy nhập tên đề tài trước khi A.I hỗ trợ.');return}const d=buildLocalProposalSections(form.title,works,design);setForm(f=>({...f,...d}));setNote('Đã tạo bản nháp bằng thuật toán local 0đ từ tên đề tài và y văn đang có. Hãy kiểm tra, chỉnh sửa và xác nhận với GVHD trước khi nộp.');};
  const cloudAssist=async()=>{if(clean(form.title).length<5)return;setBusy(true);setNote('');try{const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Phiên đăng nhập không hợp lệ.');const evidence=works.slice(0,10).map(w=>({title:w.title,source:w.source,year:w.year,abstract:w.abstract||'',url:w.url}));const response=await fetch('/api/ai/research-proposal',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({title:form.title,studyDesign:design,context:`Mục tiêu do người dùng đã nhập: ${form.objectives||'(chưa có)'}`,evidence})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||`A.I lỗi ${response.status}`);if(payload?.draft){setForm(f=>({...f,...payload.draft}));setNote(`Đã tinh chỉnh bằng A.I cloud (${payload.provider}). Nội dung vẫn cần kiểm chứng nguồn và GVHD duyệt.`)}else{localAssist();setNote('A.I cloud chưa khả dụng; hệ thống đã dùng bản nháp local 0đ, không gửi nội dung sang nhà cung cấp.')}}catch(e){setNote((e as Error).message||'Không thể dùng A.I cloud.');}finally{setBusy(false)}};
  const exportDocx=()=>{if(clean(form.title).length<5){setNote('Tên đề tài cần ít nhất 5 ký tự để xuất Word.');return}downloadResearchProposalDocx(form);setNote('Đã tạo file Word Mẫu 01-SV trên thiết bị. Vui lòng rà soát nội dung, chữ ký và dự toán với GVHD.');};
  return <div className="research-proposal-backdrop" onMouseDown={onClose}><section className="research-proposal" role="dialog" aria-modal="true" aria-label="Tạo đề cương nghiên cứu" onMouseDown={e=>e.stopPropagation()}>
    <header><div><span className="kicker">A.I RESEARCH PROPOSAL</span><h3><FileText/> Tạo Thuyết minh đề tài Mẫu 01-SV</h3><p>Điền dữ liệu thật → A.I hỗ trợ nội dung → kiểm tra → xuất Word.</p></div><button className="icon-btn" onClick={onClose} aria-label="Đóng"><X/></button></header>
    <div className="proposal-toolbar"><label>Thiết kế nghiên cứu<select value={design} onChange={e=>setDesign(e.target.value)}>{DESIGNS.map(x=><option key={x}>{x}</option>)}</select></label><div className="proposal-actions"><button onClick={localAssist}><Sparkles/> A.I local 0đ</button><button className="secondary" disabled={busy} onClick={()=>void cloudAssist()}><Bot/>{busy?'Đang hỗ trợ…':'Tinh chỉnh A.I cloud'}</button><button className="proposal-download" onClick={exportDocx}><Download/> Xuất Word</button></div></div>
    {topics.length>0&&<div className="proposal-topics"><b>A.I gợi ý đề tài</b><div>{topics.map(t=><button type="button" key={t.title} onClick={()=>set('title',t.title)}>{t.title}</button>)}</div></div>}
    <div className="ai-note proposal-guidance"><b>Lưu ý trước khi chốt đề cương</b><ul><li>Thu hẹp câu hỏi nghiên cứu để đo được; tra PubMed/OpenAlex trước khi khẳng định khoảng trống hoặc tính mới.</li><li>Giữ mục tiêu, thiết kế, biến số, phương pháp thu thập và phân tích thống kê nhất quán với nhau.</li><li>Không để A.I tự suy đoán cỡ mẫu, địa điểm, số liệu, phê duyệt đạo đức, kinh phí hoặc kết quả dự kiến khi chưa có căn cứ.</li><li>Với thử nghiệm can thiệp YHCT/châm cứu, kiểm tra hướng dẫn báo cáo phù hợp như CONSORT extension/STRICTA và các chuẩn chuyên ngành liên quan.</li><li>Chỉ giữ tài liệu tham khảo truy ngược được về PMID, DOI hoặc URL nguồn gốc; kiểm tra thủ công trước khi nộp và xin GVHD duyệt.</li></ul></div>
    {note&&<div className="ai-note" role="status">{note}</div>}
    <div className="proposal-section"><h4>1–5. Thông tin đề tài và nhân lực</h4><label className="span-2">Tên đề tài<input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Không viết toàn bộ chữ in hoa"/></label><label>Chủ nhiệm đề tài<input value={form.chairName} onChange={e=>set('chairName',e.target.value)}/></label><label>MSSV<input value={form.studentCode} onChange={e=>set('studentCode',e.target.value)}/></label><label>Lớp<input value={form.className} onChange={e=>set('className',e.target.value)}/></label><label>Sinh viên năm thứ<input value={form.studentYear} onChange={e=>set('studentYear',e.target.value)} inputMode="numeric"/></label><label>Khoa/Viện/Bộ môn<input value={form.faculty} onChange={e=>set('faculty',e.target.value)}/></label><label>Số điện thoại<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input value={form.email} onChange={e=>set('email',e.target.value)}/></label><label>Địa chỉ liên lạc<input value={form.address} onChange={e=>set('address',e.target.value)}/></label><label>GVHD<input value={form.adviserName} onChange={e=>set('adviserName',e.target.value)}/></label><label>Học hàm, học vị<input value={form.adviserDegree} onChange={e=>set('adviserDegree',e.target.value)}/></label><label>Chuyên môn<input value={form.adviserSpecialty} onChange={e=>set('adviserSpecialty',e.target.value)}/></label><label>Đơn vị GVHD<input value={form.adviserUnit} onChange={e=>set('adviserUnit',e.target.value)}/></label><label>Điện thoại GVHD<input value={form.adviserPhone} onChange={e=>set('adviserPhone',e.target.value)}/></label><label>Email GVHD<input value={form.adviserEmail} onChange={e=>set('adviserEmail',e.target.value)}/></label><label>Địa chỉ GVHD<input value={form.adviserAddress} onChange={e=>set('adviserAddress',e.target.value)}/></label><label>Thời gian (tháng, tối đa 12)<input type="number" min="1" max="12" value={form.durationMonths} onChange={e=>set('durationMonths',e.target.value)}/></label><label className="span-2">Thành viên (mỗi dòng: Họ tên | MSSV | Lớp/Khoa | Học lực | Điện thoại | Chức danh)<textarea value={form.teamMembers} onChange={e=>set('teamMembers',e.target.value)} placeholder="Nguyễn Văn A | 123456 | YHCT... | Khá | 09... | Thành viên"/></label></div>
    <div className="proposal-section proposal-writing"><h4>6–19. Nội dung nghiên cứu</h4>{([
      ['overview','6. Tổng quan'],['significance','7. Ý nghĩa khoa học, ý nghĩa thực tiễn'],['objectives','8. Mục tiêu nghiên cứu'],['populationScope','9. Đối tượng và phạm vi nghiên cứu'],['location','10. Địa điểm nghiên cứu'],['mainContents','11. Nội dung chủ yếu của đề tài'],['methods','12. Phương pháp nghiên cứu'],['expectedResults','13. Dự kiến kết quả, sản phẩm nghiên cứu'],['reportOutline','14. Bố cục báo cáo tổng kết'],['assignments','15. Phân công công việc (mỗi dòng: Họ tên | Chức danh | Nhiệm vụ | Thời gian)'],['totalBudget','16. Tổng kinh phí'],['progress','17. Tiến độ (mỗi dòng: Công việc | Bắt đầu | Kết thúc | Thời lượng | Người phụ trách)'],['specialNeeds','18. Nhu cầu đặc biệt'],['references','19. Tài liệu tham khảo IEEE']
    ] as [keyof ProposalFormData,string][]).map(([key,label])=><label key={key}>{label}{key==='totalBudget'?<input value={form[key]} onChange={e=>set(key,e.target.value)} placeholder="Chỉ nhập khi có căn cứ/GVHD xác nhận"/>:<textarea value={form[key]} onChange={e=>set(key,e.target.value)} rows={key==='overview'||key==='methods'||key==='references'?6:4}/>}</label>)}</div>
    <footer><button className="secondary" onClick={onClose}><X/> Đóng</button><button className="proposal-download" onClick={exportDocx}><Download/> Xuất Word Mẫu 01-SV</button></footer>
  </section></div>;
}
