import {useEffect,useMemo,useRef,useState} from 'react';
import {Bell,BookOpen,ChevronDown,Database,ExternalLink,GripHorizontal,KeyRound,Lightbulb,Mic,MicOff,Search,Send,Settings,Sparkles,X} from 'lucide-react';
import type {Member} from '../../types';
import {roleAtLeast} from '../../types';
import {checkHerbConflict} from '../../services/aiService';
import {askGemini,clearGeminiKey,discoverGeminiModel,GeminiFallbackError,getGeminiStatus,saveGeminiKey} from '../../services/geminiByok';
import {buildResearchLinks,checkDrlConversation,describeKnowledge,generateDailyContent,getDrlReminders,parseDrlIntent,searchKnowledge,type DailyContentPack,type DrlReminder,type DrlSummary,type KnowledgeHit,type OmniFilter,type ResearchLink} from '../../services/miniAiEngine';

declare global{interface Window{webkitSpeechRecognition?:new()=>any;SpeechRecognition?:new()=>any}}
type Pos={x:number;y:number;edge:'left'|'right'};
type Saved={open:boolean;x:number;y:number;edge:'left'|'right'};
type AssistantCard=
  |{id:string;type:'text';title:string;body:string;status?:string}
  |{id:string;type:'knowledge';title:string;hits:KnowledgeHit[]}
  |{id:string;type:'research';title:string;links:ResearchLink[]}
  |{id:string;type:'drl';title:string;summary:DrlSummary}
  |{id:string;type:'reminders';title:string;items:DrlReminder[];target:number|null;current:number|null;gap:number|null}
  |{id:string;type:'daily';title:string;pack:DailyContentPack};

const KEY='yhct-mini-ai-widget-v3';
const NOTICE_KEY='yhct-mini-ai-notice-v1';
const YHCT_RESEARCH_DRIVE_URL='https://drive.google.com/drive/folders/1IjoX3TwCz-mp4g6tE72OnWv2rH00m1NX';
const FAB=58,margin=12;
const clamp=(v:number,min:number,max:number)=>Math.min(Math.max(v,min),Math.max(min,max));
const mobile=()=>typeof window!=='undefined'&&window.matchMedia('(max-width:980px)').matches;
const defaults=():Saved=>({open:false,x:typeof window==='undefined'?margin:Math.max(margin,window.innerWidth-FAB-margin),y:typeof window==='undefined'?180:Math.max(80,window.innerHeight-FAB-112),edge:'right'});
const read=():Saved=>{try{const parsed=JSON.parse(localStorage.getItem(KEY)||'null');return parsed&&typeof parsed==='object'?{...defaults(),...parsed}:defaults()}catch{return defaults()}};
const filters:Array<{id:OmniFilter;label:string}>=[{id:'all',label:'Tất cả'},{id:'medicine',label:'Thuốc'},{id:'acupoint',label:'Huyệt'},{id:'drl',label:'Điểm DRL'},{id:'research',label:'NCKH'}];
const uid=()=>`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;

export default function PersonalCopilotWidget({member}:{member:Member|null}){
  const initial=useMemo(read,[]),canByok=roleAtLeast(member?.role,'admin');
  const [open,setOpen]=useState(initial.open),[pos,setPos]=useState<Pos>({x:initial.x,y:initial.y,edge:initial.edge}),[isMobile,setIsMobile]=useState(mobile),[mode,setMode]=useState<'chat'|'search'>('chat'),[filter,setFilter]=useState<OmniFilter>('all'),[text,setText]=useState(''),[listening,setListening]=useState(false),[dragging,setDragging]=useState(false),[busy,setBusy]=useState(false),[cards,setCards]=useState<AssistantCard[]>([]),[reminderBadge,setReminderBadge]=useState(0),[settingsOpen,setSettingsOpen]=useState(false),[keyDraft,setKeyDraft]=useState(''),[geminiStatus,setGeminiStatus]=useState(()=>getGeminiStatus()),[status,setStatus]=useState('Offline-first · dữ liệu cục bộ sẵn sàng');
  const drag=useRef<{pointerId:number;startX:number;startY:number;originX:number;originY:number;moved:boolean}|null>(null),recognition=useRef<any>(null),textareaRef=useRef<HTMLTextAreaElement|null>(null);
  const bounds=()=>({maxX:Math.max(margin,window.innerWidth-FAB-margin),maxY:Math.max(72,window.innerHeight-FAB-(mobile()?96:margin))});
  const persist=(nextOpen=open,nextPos=pos)=>{try{localStorage.setItem(KEY,JSON.stringify({open:nextOpen,...nextPos}))}catch{}};
  const normalizePos=(p:Pos):Pos=>{const b=bounds();return{...p,x:clamp(p.x,margin,b.maxX),y:clamp(p.y,72,b.maxY)}};

  useEffect(()=>{persist(open,pos)},[open,pos]);
  useEffect(()=>()=>{try{recognition.current?.stop()}catch{}},[]);
  useEffect(()=>{if(open)return;try{recognition.current?.stop()}catch{}recognition.current=null;setListening(false);setSettingsOpen(false)},[open]);
  useEffect(()=>{
    if(!open)return;
    const onResize=()=>{setIsMobile(mobile());setPos(current=>normalizePos(current))};
    const vv=window.visualViewport;
    const updateViewport=()=>{const offset=vv?Math.max(0,window.innerHeight-vv.height-vv.offsetTop):0;document.documentElement.style.setProperty('--mini-ai-keyboard-offset',`${Math.round(offset)}px`);document.documentElement.style.setProperty('--mini-ai-vv-height',`${Math.round(vv?.height||window.innerHeight)}px`)};
    window.addEventListener('resize',onResize,{passive:true});vv?.addEventListener('resize',updateViewport,{passive:true});vv?.addEventListener('scroll',updateViewport,{passive:true});onResize();updateViewport();
    return()=>{window.removeEventListener('resize',onResize);vv?.removeEventListener('resize',updateViewport);vv?.removeEventListener('scroll',updateViewport);document.documentElement.style.removeProperty('--mini-ai-keyboard-offset');document.documentElement.style.removeProperty('--mini-ai-vv-height')};
  },[open]);
  useEffect(()=>{if(!open)return;const el=textareaRef.current;if(!el)return;el.style.height='auto';el.style.height=`${Math.min(150,Math.max(52,el.scrollHeight))}px`},[text,open]);
  useEffect(()=>{
    let active=true;
    void getDrlReminders(member,30).then(result=>{if(!active)return;setReminderBadge(result.items.filter(x=>x.daysLeft<=7).length);if(typeof Notification!=='undefined'&&Notification.permission==='granted'){const urgent=result.items.find(x=>x.daysLeft<=3);if(urgent){const stamp=`${new Date().toISOString().slice(0,10)}:${urgent.id}`;try{if(localStorage.getItem(NOTICE_KEY)!==stamp){new Notification('YHCT HIU · Nhắc hoạt động',{body:`Còn ${urgent.daysLeft} ngày: ${urgent.title}${urgent.points!==null?` · +${urgent.points} điểm`:' · điểm chưa công bố'}`});localStorage.setItem(NOTICE_KEY,stamp)}}catch{}}}}).catch(()=>{});return()=>{active=false}
  },[member?.id]);

  const onPointerDown=(e:React.PointerEvent<HTMLButtonElement>)=>{if(open&&isMobile)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,originX:pos.x,originY:pos.y,moved:false};setDragging(false)};
  const onPointerMove=(e:React.PointerEvent<HTMLButtonElement>)=>{const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(!d.moved&&Math.hypot(dx,dy)>5){d.moved=true;setDragging(true)}if(!d.moved)return;const b=bounds();setPos(current=>({...current,x:clamp(d.originX+dx,margin,b.maxX),y:clamp(d.originY+dy,72,b.maxY)}))};
  const finishPointer=(e:React.PointerEvent<HTMLButtonElement>)=>{const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;drag.current=null;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}if(d.moved){const b=bounds();setPos(current=>{const edge=current.x+FAB/2<window.innerWidth/2?'left':'right';const next={x:edge==='left'?margin:b.maxX,y:clamp(current.y,72,b.maxY),edge} as Pos;persist(open,next);return next});setDragging(false);return}setOpen(v=>!v)};
  const speak=()=>{const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){setStatus('Trình duyệt này chưa hỗ trợ Web Speech API.');return}if(recognition.current){try{recognition.current.stop()}catch{}return}const r=new C();recognition.current=r;r.lang='vi-VN';r.continuous=false;r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>{setListening(false);recognition.current=null};r.onerror=()=>{setListening(false);recognition.current=null};r.onresult=(e:any)=>setText((v:string)=>`${v} ${e.results[0][0].transcript}`.trim());r.start()};
  const addCard=(card:AssistantCard)=>setCards(x=>[card,...x].slice(0,14));

  const showReminders=async(requestPermission=false)=>{setBusy(true);try{if(requestPermission&&typeof Notification!=='undefined'&&Notification.permission==='default')await Notification.requestPermission();const result=await getDrlReminders(member,30);addCard({id:uid(),type:'reminders',title:'Nhắc hoạt động rèn luyện',...result});setReminderBadge(result.items.filter(x=>x.daysLeft<=7).length);setStatus(result.target===null?'Đã quét lịch. Mục tiêu DRL học kỳ chưa được cấu hình nên trợ lý không tự suy đoán số điểm cần đạt.':'Đã đối chiếu lịch và mục tiêu DRL cục bộ.')}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}};
  const showDaily=()=>{addCard({id:uid(),type:'daily',title:'Gợi ý viết bài hôm nay',pack:generateDailyContent()});setStatus('Đã tạo 5 cấu trúc bài viết bằng engine cục bộ.');};
  const openYhctDrive=()=>{setStatus('Đang mở Kho YHCT trên Google Drive…');window.open(YHCT_RESEARCH_DRIVE_URL,'_blank','noopener,noreferrer')};

  const runLocal=async(query:string)=>{
    const drl=filter==='drl'||parseDrlIntent(query)?await checkDrlConversation(filter==='drl'&&!parseDrlIntent(query)?`Xem điểm của ${query}`:query,member):null;
    if(drl){addCard({id:uid(),type:'drl',title:drl.mode==='mine'?'Điểm kỳ này của tôi':'Kết quả DRL',summary:drl});return true}
    if(filter==='research'){const links=buildResearchLinks(query);addCard({id:uid(),type:'research',title:'Tìm tài liệu NCKH',links});return true}
    const hits=await searchKnowledge(query,filter,8);if(hits.length){addCard({id:uid(),type:'knowledge',title:'Tra cứu YHCT offline',hits});return true}
    if(filter==='all'&&/(nghien cuu|nckh|pubmed|scholar|cochrane|tai lieu)/i.test(query.normalize('NFD').replace(/[\u0300-\u036f]/g,''))){addCard({id:uid(),type:'research',title:'Tìm tài liệu NCKH',links:buildResearchLinks(query)});return true}
    return false;
  };

  const submit=async()=>{const query=text.trim();if(!query||busy)return;setBusy(true);setText('');setStatus('Đang xử lý trên thiết bị…');try{const handled=await runLocal(query);const warnings=checkHerbConflict(query);if(warnings.length)addCard({id:uid(),type:'text',title:'Cảnh báo phối ngũ',body:warnings.join('\n'),status:'Hỗ trợ học tập · cần kiểm tra nguồn chính thức'});if(handled){setStatus('Phản hồi bằng dữ liệu/thuật toán cục bộ.');return}if(canByok&&geminiStatus.configured&&mode==='chat'){try{setStatus('Đang gọi Gemini BYOK trong hạn mức bảo vệ…');const response=await askGemini(query);addCard({id:uid(),type:'text',title:'Gemini · Trợ lý học thuật',body:response.text,status:`Model ${response.model} · BYOK`});setGeminiStatus(getGeminiStatus());setStatus('Gemini BYOK phản hồi thành công.')}catch(e){const reason=e instanceof GeminiFallbackError?e.message:(e as Error).message;addCard({id:uid(),type:'text',title:'Phản hồi offline',body:'Không có kết quả trực tiếp trong Mini Knowledge-Base. Hãy chuyển bộ lọc sang NCKH để tạo liên kết tìm nguồn, hoặc dùng từ khóa tên bài thuốc/vị thuốc/huyệt cụ thể.',status:reason});setStatus(reason)}return}addCard({id:uid(),type:'text',title:'Tra cứu cục bộ',body:'Chưa tìm thấy mục phù hợp trong Mini Knowledge-Base. Bạn có thể chọn NCKH để tạo truy vấn Scholar/PubMed/Cochrane, hoặc nhập tên bài thuốc, vị thuốc, mã/tên huyệt hay câu lệnh “Điểm kỳ này của tôi”.',status:'Không gửi dữ liệu ra dịch vụ AI bên ngoài.'});setStatus('Không tìm thấy kết quả cục bộ phù hợp.')}catch(e){addCard({id:uid(),type:'text',title:'Không thể hoàn tất',body:(e as Error).message,status:'Dữ liệu không được tự suy đoán.'});setStatus((e as Error).message)}finally{setBusy(false)}};
  const saveKey=async()=>{if(!canByok)return;try{saveGeminiKey(keyDraft);setKeyDraft('');setStatus('Đã lưu BYOK trên thiết bị. Đang dò model hỗ trợ generateContent…');const model=await discoverGeminiModel(true);setGeminiStatus(getGeminiStatus());setStatus(`BYOK sẵn sàng · ${model}`)}catch(e){setStatus((e as Error).message)} };
  const deleteKey=()=>{clearGeminiKey();setGeminiStatus(getGeminiStatus());setKeyDraft('');setStatus('Đã xóa Gemini BYOK và bộ đếm hạn mức trên thiết bị.')};
  const warnings=checkHerbConflict(text),boxStyle:React.CSSProperties=isMobile?{}:{left:clamp(pos.edge==='right'?pos.x-398:pos.x,margin,window.innerWidth-430),top:clamp(pos.y-460,72,window.innerHeight-560)};

  return <div className={`copilot copilot-v3 ${open?'is-open':''} ${isMobile?'is-mobile':''}`}>
    {open&&<section className="copilot-box copilot-panel mini-ai-panel" style={boxStyle} role="dialog" aria-modal={isMobile} aria-label="Trợ lý AI Mini Y học cổ truyền">
      <header className="mini-ai-header"><div className="row"><GripHorizontal className="copilot-grip"/><div><b><Sparkles/> A.I Mini</b><small>{status}</small></div></div><div className="row mini-ai-head-actions"><button className={mode==='search'?'active':''} aria-label="Chuyển chế độ tra cứu" title="Tra cứu nhanh" onClick={()=>setMode(x=>x==='search'?'chat':'search')}><Search/></button>{canByok&&<button aria-label="Cài đặt Gemini BYOK" title="Gemini BYOK" onClick={()=>setSettingsOpen(x=>!x)}><Settings/></button>}<button className="copilot-close" aria-label="Đóng A.I Mini" onClick={()=>setOpen(false)}><X/></button></div></header>
      <div className="mini-ai-mode"><button className={mode==='chat'?'active':''} onClick={()=>setMode('chat')}><Sparkles/>Trò chuyện A.I</button><button className={mode==='search'?'active':''} onClick={()=>setMode('search')}><Search/>Tra cứu trực tiếp</button></div>
      <div className="mini-ai-filters" aria-label="Bộ lọc tra cứu">{filters.map(f=><button key={f.id} className={filter===f.id?'active':''} onClick={()=>{setFilter(f.id);if(f.id!=='all')setMode('search')}}>{f.label}</button>)}</div>
      {canByok&&settingsOpen&&<section className="mini-ai-settings"><div className="between"><div><b><KeyRound/> Gemini BYOK</b><small>Chỉ Admin · khóa lưu cục bộ trên trình duyệt, không commit lên mã nguồn.</small></div><button className="secondary" onClick={()=>setSettingsOpen(false)}><ChevronDown/></button></div><label>Personal API Key<input type="password" value={keyDraft} onChange={e=>setKeyDraft(e.target.value)} placeholder={geminiStatus.configured?geminiStatus.maskedKey:'Nhập Gemini API key cá nhân'} autoComplete="off"/></label><div className="mini-ai-settings-actions"><button disabled={!keyDraft.trim()} onClick={()=>void saveKey()}>Lưu & kiểm tra</button>{geminiStatus.configured&&<button className="secondary" onClick={deleteKey}>Xóa khóa</button>}</div><small>Giới hạn bảo vệ cục bộ: {geminiStatus.quota.minute}/{geminiStatus.quota.minuteLimit} lượt/phút · {geminiStatus.quota.day}/{geminiStatus.quota.dayLimit} lượt/ngày. Đây là ngưỡng của ứng dụng, không phải cam kết quota của Google.</small></section>}
      <section className="mini-ai-quick"><button onClick={()=>void showReminders(false)}><Bell/><span><b>Nhắc DRL</b><small>Lịch & điểm</small></span></button><button onClick={showDaily}><Lightbulb/><span><b>Viết hôm nay</b><small>5 ý tưởng</small></span></button><button onClick={()=>{setMode('search');setFilter('research');textareaRef.current?.focus()}}><BookOpen/><span><b>NCKH</b><small>4 nguồn</small></span></button><button onClick={openYhctDrive} aria-label="Mở Kho YHCT trên Google Drive"><Database/><span><b>Kho YHCT</b><small>Google Drive</small></span></button></section>
      {reminderBadge>0&&<div className="mini-ai-reminder-banner"><Bell/><span>Có <b>{reminderBadge}</b> hoạt động trong 7 ngày tới.</span><button onClick={()=>void showReminders(true)}>Xem / bật báo</button></div>}
      <div className="mini-ai-composer"><label className="sr-only" htmlFor="mini-ai-text">Nội dung hỏi hoặc tra cứu</label><textarea ref={textareaRef} id="mini-ai-text" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void submit()}}} placeholder={filter==='drl'?'Ví dụ: Điểm kỳ này của tôi / Xem điểm của 22123456':filter==='research'?'Nhập chủ đề nghiên cứu YHCT…':filter==='acupoint'?'Nhập tên hoặc mã huyệt, ví dụ LI4…':filter==='medicine'?'Nhập tên vị thuốc hoặc bài thuốc…':'Hỏi học thuật hoặc tra cứu nhanh…'} rows={2}/><div className="mini-ai-compose-actions"><button className="secondary" onClick={speak} aria-label={listening?'Dừng nhập giọng nói':'Nhập bằng giọng nói'}>{listening?<MicOff/>:<Mic/>}</button><button className="mini-ai-send" disabled={busy||!text.trim()} onClick={()=>void submit()} aria-label="Gửi"><Send/>{busy?'Đang xử lý':'Gửi'}</button></div></div>
      {warnings.map(w=><div className="warning mini-ai-inline-warning" key={w}>{w}</div>)}
      <div className="mini-ai-results" aria-live="polite">{cards.length===0&&<div className="mini-ai-empty"><Sparkles/><b>5 công cụ + Kho tài liệu Drive</b><p>Tra DRL, nhắc hoạt động, tìm tài liệu NCKH, gợi ý nội dung theo mùa/tiết khí, tra cứu bài thuốc–vị thuốc–huyệt offline và mở kho tài liệu nghiên cứu trên Google Drive.</p></div>}{cards.map(card=><CardView key={card.id} card={card}/>)}</div>
      <p className="copilot-disclaimer">Hỗ trợ học tập YHCT, không thay thế chẩn đoán, kê đơn hoặc quyết định điều trị. Liều dược liệu và vị trí huyệt phải được kiểm tra lại bằng giáo trình/dược điển/hướng dẫn chuyên môn trước thực hành.</p>
    </section>}
    <button className={`float copilot-fab ${dragging?'dragging':''}`} style={{left:pos.x,top:pos.y}} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={finishPointer} onPointerCancel={finishPointer} aria-label={open?'Đóng A.I Mini':'Mở A.I Mini'} title="Kéo để di chuyển · thả để hít vào mép màn hình"><Sparkles/>{reminderBadge>0&&<span className="copilot-badge">{Math.min(reminderBadge,9)}</span>}</button>
  </div>
}

function CardView({card}:{card:AssistantCard}){
  if(card.type==='text')return <article className="mini-ai-card"><h3>{card.title}</h3><p className="mini-ai-prewrap">{card.body}</p>{card.status&&<small>{card.status}</small>}</article>;
  if(card.type==='knowledge')return <article className="mini-ai-card"><h3>{card.title}</h3>{card.hits.map((hit,i)=><details key={hit.record.id} open={i===0}><summary><span><b>{hit.record.name}</b><small>{hit.record.kind==='acupoint'?`Huyệt ${String(hit.record.code||'')}`:hit.record.kind==='formula'?'Bài thuốc':'Vị thuốc'} · khớp {Math.round(hit.score*100)}%</small></span></summary><dl>{describeKnowledge(hit.record).map(row=><div key={row.k}><dt>{row.k}</dt><dd>{row.v}</dd></div>)}</dl></details>)}<small>Tra cứu IndexedDB: {card.hits[0]?.elapsedMs??0} ms trên thiết bị này.</small></article>;
  if(card.type==='research')return <article className="mini-ai-card"><h3>{card.title}</h3><p>Tạo liên kết truy vấn trực tiếp, không scrape và không đi qua CORS proxy trung gian.</p><div className="mini-ai-links">{card.links.map(link=><a key={link.provider} href={link.url} target="_blank" rel="noreferrer noopener"><span><b>{link.provider}</b><small>{link.query}</small></span><ExternalLink/></a>)}</div></article>;
  if(card.type==='drl')return <article className="mini-ai-card"><h3>{card.title}</h3>{card.summary.mode==='mine'?<><div className="mini-ai-score"><span>{card.summary.semesterTitle||'Học kỳ gần nhất'}</span><strong>{card.summary.total} điểm</strong></div>{card.summary.items.length?<div className="mini-ai-list">{card.summary.items.slice(0,8).map((x,i)=><div key={`${x.label}-${i}`}><span><b>{x.label}</b><small>{x.detail}</small></span><strong>{x.points>0?'+':''}{x.points}</strong></div>)}</div>:<p>Chưa có dữ liệu điểm trong học kỳ.</p>}</>:<>{card.summary.candidates?.length?<div className="mini-ai-list">{card.summary.candidates.map((x,i)=><div key={`${x.student_code_masked}-${i}`}><span><b>{x.full_name}</b><small>{x.student_code_masked} · {x.semester_title}</small></span><strong>{x.total_points} điểm</strong></div>)}</div>:<p>Không tìm thấy ứng viên phù hợp. MSSV công khai vẫn được che theo RPC hiện hành.</p>}</>}</article>;
  if(card.type==='reminders')return <article className="mini-ai-card"><h3>{card.title}</h3>{card.target!==null&&card.current!==null?<div className="mini-ai-score"><span>Mục tiêu {card.target} · hiện có {card.current}</span><strong>{card.gap} điểm còn thiếu</strong></div>:<p className="mini-ai-note">Mục tiêu học kỳ chưa cấu hình hoặc chưa có dữ liệu điểm; trợ lý không tự đặt ngưỡng.</p>}{card.items.length?<div className="mini-ai-list">{card.items.map(x=><div key={x.id}><span><b>{x.daysLeft===0?'Hôm nay':`Còn ${x.daysLeft} ngày`} · {x.title}</b><small>{x.location||'Chưa cập nhật địa điểm'}{x.note?` · ${x.note}`:''}</small></span><strong>{x.points===null?'Điểm chưa công bố':`+${x.points}`}</strong></div>)}</div>:<p>Không có hoạt động đã lưu/đồng bộ trong 30 ngày tới.</p>}</article>;
  return <article className="mini-ai-card"><h3>{card.title}</h3><div className="mini-ai-daily-meta"><b>{card.pack.dateLabel}</b><span>{card.pack.season} · {card.pack.solarTerm}</span></div><small>{card.pack.solarTermNote}</small>{card.pack.ideas.map((idea,i)=><details key={idea.title} open={i===0}><summary><span><b>{i+1}. {idea.title}</b><small>{idea.hook}</small></span></summary><ol>{idea.outline.map(x=><li key={x}>{x}</li>)}</ol><p className="mini-ai-hashtags">{idea.hashtags.map(x=>`#${x}`).join(' ')}</p><small>Nguồn gợi ý: {idea.references.join(' · ')}</small></details>)}</article>;
}
