import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),required=['src/components/admin/SystemAdminCenter.tsx','src/components/admin/AdminControlCenter.tsx','src/components/drl/DrlCenter.tsx','src/components/research/ResearchCenter.tsx','src/components/schedule/ScheduleCenter.tsx','src/components/ai/PersonalCopilotWidget.tsx','src/components/branding/SystemBrandMark.tsx','src/mobile-audit.css','src/final-hotfix.css','src/workers/drlParseWorker.ts','src/workers/docxParseWorker.ts','api/_lib/member-access.js','api/ai/diagnostics.js','api/research/drive.js','public/service-worker.js','public/yhct-system-mark.svg'];
const errors=[];for(const f of required)if(!fs.existsSync(path.join(root,f)))errors.push(`missing ${f}`);
const packageJson=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));if(String(packageJson.dependencies?.xlsx||'').includes('0.18.5'))errors.push('vulnerable xlsx 0.18.5 is forbidden');
const scanRoots=['src','api'];const files=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p):/\.(?:ts|tsx|js|css)$/.test(e.name)&&files.push(p)}};scanRoots.forEach(x=>walk(path.join(root,x)));
const forbidden=[[/sk-proj-[A-Za-z0-9_-]{20,}/,'raw OpenAI secret'],[/dangerouslySetInnerHTML/,'dangerous raw HTML rendering'],[/\bTODO\b|\bFIXME\b|implement later|code logic here/i,'unfinished implementation marker'],[/logo-clb-yhct-hiu/i,'obsolete club logo reference']];for(const f of files){const text=fs.readFileSync(f,'utf8');for(const [re,label] of forbidden)if(re.test(text))errors.push(`${label} in ${path.relative(root,f)}`)}
for(const f of ['index.html','public/manifest.webmanifest','public/service-worker.js']){const text=fs.readFileSync(path.join(root,f),'utf8');if(/logo-clb-yhct-hiu/i.test(text))errors.push(`obsolete club logo reference in ${f}`);if(!/yhct-system-mark\.svg/i.test(text))errors.push(`system SVG mark missing from ${f}`)}
for(const old of ['public/logo-clb-yhct-hiu.jpg','public/logo-clb-yhct-hiu.svg'])if(fs.existsSync(path.join(root,old)))errors.push(`obsolete logo asset still present: ${old}`);
const widget=fs.readFileSync(path.join(root,'src/components/ai/PersonalCopilotWidget.tsx'),'utf8');for(const token of ['localStorage','onPointerDown','onPointerMove','onPointerUp',"edge:'left'|'right'"])if(!widget.includes(token))errors.push(`Mini AI persistence/drag gate missing ${token}`);
const mobile=fs.readFileSync(path.join(root,'src/mobile-audit.css'),'utf8');for(const token of ['bottom:0','min-height:48px','safe-area-inset-bottom','overflow-x:hidden'])if(!mobile.includes(token))errors.push(`mobile CSS gate missing ${token}`);
const finalHotfix=fs.readFileSync(path.join(root,'src/final-hotfix.css'),'utf8');for(const token of ['@media(max-width:980px)','grid-auto-flow:column','gap:18px','system-brand-mark','news-media-default','safe-area-inset-bottom'])if(!finalHotfix.includes(token))errors.push(`final mobile/branding gate missing ${token}`);
if(errors.length){console.error('ACCEPTANCE CHECK FAILED');errors.forEach(x=>console.error(`- ${x}`));process.exit(1)}console.log(`acceptance-ok: ${files.length} application source files scanned; scalable branding + mobile spacing + MiniAI + security gates clean`);
