import fs from 'node:fs';import path from 'node:path';
const root=process.cwd(),required=['src/components/admin/SystemAdminCenter.tsx','src/components/admin/AdminControlCenter.tsx','src/components/admin/ModerationOpsPanel.tsx','src/components/drl/DrlCenter.tsx','src/components/research/ResearchCenter.tsx','src/components/schedule/ScheduleCenter.tsx','src/components/notifications/NotificationsCenter.tsx','src/components/ai/PersonalCopilotWidget.tsx','src/components/news/TcmNewsCenter.tsx','src/components/branding/SystemBrandMark.tsx','src/components/system/ViewportModeToggle.tsx','src/services/miniAiEngine.ts','src/services/geminiByok.ts','src/data/ai-kb/formulas.ts','src/data/ai-kb/herbs.ts','src/data/ai-kb/acupoints.ts','src/mobile-audit.css','src/final-hotfix.css','src/mobile-social.css','src/mobile-social-compat.css','src/mini-ai.css','src/viewport-news-final.css','src/viewport-native-hotfix.css','src/workers/drlParseWorker.ts','src/workers/docxParseWorker.ts','api/_lib/member-access.js','api/ai/diagnostics.js','api/research/drive.js','scripts/role-ui-audit.mjs','public/service-worker.js','public/yhct-system-mark.svg'];
const errors=[];for(const f of required)if(!fs.existsSync(path.join(root,f)))errors.push(`missing ${f}`);
const packageJson=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));if(String(packageJson.dependencies?.xlsx||'').includes('0.18.5'))errors.push('vulnerable xlsx 0.18.5 is forbidden');if(!String(packageJson.scripts?.prebuild||'').includes('audit:roles'))errors.push('prebuild must run independent role audit');
const scanRoots=['src','api'];const files=[];const walk=d=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?walk(p):/\.(?:ts|tsx|js|css)$/.test(e.name)&&files.push(p)}};scanRoots.forEach(x=>walk(path.join(root,x)));
const forbidden=[[/sk-proj-[A-Za-z0-9_-]{20,}/,'raw OpenAI secret'],[/AIza[0-9A-Za-z0-9_-]{20,}/,'raw Google/Gemini secret'],[/dangerouslySetInnerHTML/,'dangerous raw HTML rendering'],[/\bTODO\b|\bFIXME\b|implement later|code logic here/i,'unfinished implementation marker'],[/logo-clb-yhct-hiu/i,'obsolete club logo reference']];for(const f of files){const text=fs.readFileSync(f,'utf8');for(const [re,label] of forbidden)if(re.test(text))errors.push(`${label} in ${path.relative(root,f)}`)}
for(const f of ['index.html','public/manifest.webmanifest','public/service-worker.js']){const text=fs.readFileSync(path.join(root,f),'utf8');if(/logo-clb-yhct-hiu/i.test(text))errors.push(`obsolete club logo reference in ${f}`);if(!/yhct-system-mark\.svg/i.test(text))errors.push(`system SVG mark missing from ${f}`)}
const boot=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const token of ['yhct-viewport-mode-v1','dataset.viewportMode','width=1280,viewport-fit=cover','width=device-width,initial-scale=1'])if(!boot.includes(token))errors.push(`early viewport bootstrap gate missing ${token}`);if(boot.includes('width=1280,initial-scale=1')||boot.includes('width=1280, initial-scale=1'))errors.push('desktop viewport must not force initial-scale=1 on narrow phones');
const widget=fs.readFileSync(path.join(root,'src/components/ai/PersonalCopilotWidget.tsx'),'utf8');for(const token of ['localStorage','onPointerDown','visualViewport','Notification.requestPermission','Điểm kỳ này của tôi','Gemini BYOK','Tra cứu trực tiếp','1IjoX3TwCz-mp4g6tE72OnWv2rH00m1NX','Kho YHCT','Google Drive'])if(!widget.includes(token))errors.push(`Mini AI gate missing ${token}`);
const viewport=fs.readFileSync(path.join(root,'src/components/system/ViewportModeToggle.tsx'),'utf8');for(const token of ["type ViewportMode='desktop'|'mobile'",'dataset.viewportMode','width=1280, viewport-fit=cover','width=device-width','localStorage.setItem(VIEWPORT_MODE_KEY','Xem bản Desktop','Xem bản Mobile','Monitor','Smartphone','data-target-mode'])if(!viewport.includes(token))errors.push(`viewport mode gate missing ${token}`);if(viewport.includes("DESKTOP_VIEWPORT='width=1280, initial-scale=1"))errors.push('runtime desktop viewport must allow browser fit-to-width scaling');
const finalCss=fs.readFileSync(path.join(root,'src/viewport-news-final.css'),'utf8');for(const token of ['data-viewport-mode="desktop"','data-viewport-mode="mobile"','overflow-x:hidden!important','overflow-x:auto!important','scroll-snap-type:x mandatory','-webkit-overflow-scrolling:touch','flex:0 0 clamp(240px,68vw,260px)','news-progress-track','72px','news-summary-clamp','moderation-grid'])if(!finalCss.includes(token))errors.push(`viewport/news final CSS gate missing ${token}`);
const nativeCss=fs.readFileSync(path.join(root,'src/viewport-native-hotfix.css'),'utf8');for(const token of ['touch-action:pan-y pinch-zoom!important','overflow-x:auto!important','scroll-snap-stop:normal!important','data-viewport-mode="desktop"'])if(!nativeCss.includes(token))errors.push(`Android gesture hotfix gate missing ${token}`);
const compat=fs.readFileSync(path.join(root,'src/mobile-social-compat.css'),'utf8');if(compat.includes('min-width:1180px'))errors.push('legacy PC min-width simulation still present');
const app=fs.readFileSync(path.join(root,'src/App.tsx'),'utf8');for(const token of ['viewport-mode-${viewportMode}','ViewportModeToggle','applyViewportMode(viewportMode)','mobile-bottom-nav','Trang chủ','Khám phá','Đăng bài','Thông báo','Cá nhân','PersonalCopilotWidget member={member}'])if(!app.includes(token))errors.push(`application shell gate missing ${token}`);if(/tab==='news'|setTab\('news'\)|\|'news'/.test(app)||app.includes("./components/news/TcmNewsCenter"))errors.push('separate YHCT News route/module is still exposed in App');if(app.includes('pc-return-mobile'))errors.push('floating PC return control must be removed to avoid AI overlap');
const news=fs.readFileSync(path.join(root,'src/components/news/TcmNewsCenter.tsx'),'utf8');for(const token of ['onScroll={updateProgress}','news-progress','news-summary-clamp','news-compact-meta','Vuốt ngang',"addEventListener('touchmove'",'passive:false','preventDefault()','touchRef'])if(!news.includes(token))errors.push(`Android compact news gesture gate missing ${token}`);for(const token of ['setPointerCapture','releasePointerCapture','onPointerMove=','onPointerDown=','dragRef'])if(news.includes(token))errors.push(`news rail must not use pointer-capture drag token ${token}`);
const feed=fs.readFileSync(path.join(root,'src/components/feed/AcademicFeed.tsx'),'utf8');for(const token of ['composeNonce','TcmNewsCenter','tích hợp trong bảng tin','set_post_mod_verified'])if(!feed.includes(token))errors.push(`academic feed/moderation gate missing ${token}`);
const admin=fs.readFileSync(path.join(root,'src/components/admin/SystemAdminCenter.tsx'),'utf8');for(const token of ['tcm_news_admin_list_v1','tcm_news_admin_update_v1','tcm_news_admin_set_pinned_v1','tcm_news_admin_delete_v1','diagnostic-output'])if(!admin.includes(token))errors.push(`admin privileged news/diagnostic gate missing ${token}`);
const moderation=fs.readFileSync(path.join(root,'src/components/admin/ModerationOpsPanel.tsx'),'utf8');for(const token of ['super_mod','tcm_news_review_v1','moderation_recent_logs_v1','drl_semester_list_v1'])if(!moderation.includes(token))errors.push(`super mod gate missing ${token}`);
const main=fs.readFileSync(path.join(root,'src/main.tsx'),'utf8');if(!main.includes("import './viewport-news-final.css';")||!main.includes("import './viewport-native-hotfix.css';"))errors.push('final viewport CSS layers are not loaded');if(main.lastIndexOf('viewport-native-hotfix.css')<main.lastIndexOf('viewport-news-final.css'))errors.push('native viewport hotfix must load last');
const sw=fs.readFileSync(path.join(root,'public/service-worker.js'),'utf8');if(!sw.includes('ui8-android-news-drive'))errors.push('service worker cache version did not advance for Android news/Drive release');
if(errors.length){console.error('ACCEPTANCE CHECK FAILED');errors.forEach(x=>console.error(`- ${x}`));process.exit(1)}console.log(`acceptance-ok: ${files.length} application source files scanned; Android touch-assisted compact news + Drive-linked Kho YHCT + viewport/RBAC/Mini AI/security gates clean`);
