import {useEffect,useMemo,useState} from 'react';
import {BookOpenCheck,CheckCircle2,CloudCog,Database,ExternalLink,FileCheck2,RefreshCw,ShieldCheck,XCircle} from 'lucide-react';
import {readCachedMember} from '../../services/authService';
import {roleAtLeast} from '../../types';
import {answerDailyPractice,getDailyPracticeConfig,getPracticeReviewQueue,getTodayDailyPractice,reviewPracticeQuestion,syncDriveQuizBank,type DailyPracticeAnswer,type DailyPracticeConfig,type DailyPracticeSession,type DriveSyncRow,type PracticeReviewQuestion} from '../../services/dailyPracticeService';
import '../../daily-drive-practice.css';

const DRIVE_FOLDER_URL='https://drive.google.com/drive/folders/1_VvupTkvHvWKLLehVQt_JNA15qfKnIvO';
const SOURCE_FOLDER='NGÂN HÀNG TRẮC NGHIỆM / 00_DOCX_MỚI_CHỜ_XỬ_LÝ';

export default function DailyDrivePractice(){
  const member=readCachedMember(),canModerate=roleAtLeast(member?.role,'mod'),canSync=member?.role==='admin';
  const [config,setConfig]=useState<DailyPracticeConfig|null>(null),[session,setSession]=useState<DailyPracticeSession|null>(null),[idx,setIdx]=useState(0),[feedback,setFeedback]=useState<Record<string,DailyPracticeAnswer>>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[syncRows,setSyncRows]=useState<DriveSyncRow[]>([]),[review,setReview]=useState<PracticeReviewQuestion[]>([]);
  const current=session?.questions?.[idx],answers=session?.answers||{},selected=current?answers[current.id]:undefined,answeredCount=Object.keys(answers).length,total=session?.questionCount||session?.questions.length||0;
  const progress=total?Math.round(answeredCount/total*100):0;
  const currentFeedback=current?feedback[current.id]:undefined;
  const syncSummary=useMemo(()=>syncRows.length?`${syncRows.length} tệp · ${syncRows.reduce((n,x)=>n+x.parsed,0)} câu nhận diện trực tiếp · ${syncRows.reduce((n,x)=>n+x.generated,0)} câu do A.I tạo`:'' ,[syncRows]);

  const refreshConfig=async()=>{const next=await getDailyPracticeConfig();setConfig(next);if(canModerate&&next.needsReviewCount>0)setReview(await getPracticeReviewQueue(5));else setReview([]);return next};
  const openToday=async(count?:number)=>{setBusy(true);setMsg('');try{const next=await getTodayDailyPractice(count||config?.defaultCount||10);setSession(next);setIdx(0);if(!next.ready)setMsg('Ngân hàng Drive chưa có câu hỏi đã xác minh. Admin cần đồng bộ DOCX hoặc duyệt câu A.I tạo.')}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  useEffect(()=>{let alive=true;void getDailyPracticeConfig().then(async next=>{if(!alive)return;setConfig(next);if(next.hasTodaySession){const s=await getTodayDailyPractice(next.defaultCount||10);if(alive)setSession(s)}if(canModerate&&next.needsReviewCount>0){const q=await getPracticeReviewQueue(5);if(alive)setReview(q)}}).catch(e=>{if(alive)setMsg((e as Error).message)});return()=>{alive=false}},[canModerate]);
  useEffect(()=>{if(!session?.sessionId||!current||selected===undefined||feedback[current.id]||busy)return;let alive=true;void answerDailyPractice(session.sessionId,current.id,selected).then(r=>{if(alive)setFeedback(x=>({...x,[current.id]:r}))}).catch(()=>{});return()=>{alive=false}},[session?.sessionId,current?.id,selected]);

  const choose=async(optionIndex:number)=>{if(!session?.sessionId||!current||selected!==undefined||busy)return;setBusy(true);setMsg('');try{const r=await answerDailyPractice(session.sessionId,current.id,optionIndex);const nextAnswers={...answers,[current.id]:r.selectedIndex};setFeedback(x=>({...x,[current.id]:r}));setSession(s=>s?{...s,answers:nextAnswers,status:Object.keys(nextAnswers).length>=(s.questionCount||s.questions.length)?'completed':s.status}:s)}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const syncDrive=async()=>{if(!canSync||busy)return;setBusy(true);setMsg('Đang đọc DOCX và chuẩn hóa ngân hàng…');try{const result=await syncDriveQuizBank(5,true);setSyncRows(result.processed||[]);if(result.degraded)throw new Error(result.reason||'Drive sync đang ở chế độ suy giảm.');const direct=(result.processed||[]).reduce((n,x)=>n+x.parsed,0),generated=(result.processed||[]).reduce((n,x)=>n+x.generated,0);setMsg(`Đồng bộ xong: ${direct} câu có đáp án trực tiếp được xác minh từ nguồn; ${generated} câu A.I tạo đang chờ duyệt.`);await refreshConfig()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};
  const reviewOne=async(q:PracticeReviewQuestion,status:'expert_approved'|'rejected')=>{if(!canModerate||busy)return;setBusy(true);setMsg('');try{await reviewPracticeQuestion(q.id,status);setReview(rows=>rows.filter(x=>x.id!==q.id));setMsg(status==='expert_approved'?'Đã duyệt: câu hỏi có thể vào bộ luyện hằng ngày.':'Đã loại câu hỏi khỏi ngân hàng sử dụng.');await refreshConfig()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}};

  return <section className="daily-drive panel" aria-label="Luyện tập hằng ngày từ Google Drive">
    <header className="daily-drive__head"><div><span className="daily-drive__kicker"><BookOpenCheck/> DAILY PRACTICE · DRIVE</span><h2>Luyện 10 câu mỗi ngày</h2><p>DOCX được chuẩn hóa thành ngân hàng câu hỏi có nguồn; bộ hôm nay ưu tiên câu chưa gặp hoặc từng làm sai.</p></div><div className="daily-drive__head-actions"><a href={DRIVE_FOLDER_URL} target="_blank" rel="noreferrer"><ExternalLink/>Mở kho Drive</a>{canSync&&<button disabled={busy} onClick={()=>void syncDrive()}><CloudCog/>{busy?'Đang đồng bộ…':'Đồng bộ DOCX'}</button>}</div></header>
    <div className="daily-drive__stats"><span><Database/><small>Sẵn sàng</small><b>{config?.eligibleCount??'…'} câu</b></span><span><ShieldCheck/><small>Chờ duyệt</small><b>{config?.needsReviewCount??'…'} câu</b></span><span><FileCheck2/><small>Nguồn đọc</small><b>DOCX</b></span></div>
    <div className="daily-drive__source"><b>{SOURCE_FOLDER}</b><span>Parser đọc câu/đáp án có sẵn trước; tài liệu bài học mới dùng A.I để sinh câu và luôn phải duyệt trước khi sinh viên nhận.</span></div>
    {msg&&<div className="daily-drive__message" role="status">{msg}</div>}
    {syncSummary&&<div className="daily-drive__sync-summary"><RefreshCw/>{syncSummary}</div>}

    {!session?<div className="daily-drive__start"><div><b>{config?.ready?'Bộ luyện hôm nay đã sẵn sàng':'Chưa có câu đã xác minh'}</b><span>{config?.ready?`Hệ thống sẽ cố định tối đa ${config.defaultCount||10} câu theo tài khoản và ngày, không đổi khi tải lại.`:'Hãy thêm DOCX vào thư mục nguồn. Không có dữ liệu thì hệ thống không tự bịa câu hỏi.'}</span></div><button disabled={busy||!config?.ready} onClick={()=>void openToday()}><BookOpenCheck/>Bắt đầu bộ hôm nay</button></div>:session.ready&&current?<div className="daily-drive__practice">
      <div className="daily-drive__progress"><span><b>Câu {idx+1}/{total}</b><small>{current.subject} · {current.topic}</small></span><div><i style={{width:`${progress}%`}}/></div><em>{answeredCount}/{total} đã làm</em></div>
      <article className="daily-drive__question"><header><span>{current.generationMethod==='parsed'?'Đọc trực tiếp từ DOCX':'A.I tạo · đã duyệt'}</span><small>Nguồn: {current.sourceFileName}</small></header><h3>{current.stem}</h3><div className="daily-drive__options">{current.options.map((option,i)=><button key={`${current.id}-${i}`} disabled={busy||selected!==undefined} className={`${selected===i?'selected':''}${currentFeedback&&i===currentFeedback.correctIndex?' correct':''}${currentFeedback&&selected===i&&!currentFeedback.correct?' wrong':''}`} onClick={()=>void choose(i)}><b>{String.fromCharCode(65+i)}</b><span>{option}</span></button>)}</div>{currentFeedback&&<div className={`daily-drive__feedback ${currentFeedback.correct?'ok':'bad'}`}><b>{currentFeedback.correct?'Chính xác':'Chưa chính xác'} · đáp án {String.fromCharCode(65+currentFeedback.correctIndex)}</b><p>{currentFeedback.explanation}</p><small>Đối chiếu: {currentFeedback.sourceFileName}</small></div>}</article>
      <div className="daily-drive__nav"><button disabled={idx===0||busy} onClick={()=>setIdx(x=>x-1)}>← Trước</button><span>{session.status==='completed'?'Đã hoàn tất bộ hôm nay':'Mỗi câu chỉ ghi nhận lần trả lời đầu tiên'}</span><button disabled={idx>=total-1||busy} onClick={()=>setIdx(x=>x+1)}>Tiếp →</button></div>
    </div>:<div className="daily-drive__start"><b>Chưa có bộ luyện khả dụng.</b></div>}

    {canModerate&&review.length>0&&<details className="daily-drive__review" open><summary>Duyệt câu A.I trước khi phát cho sinh viên ({review.length}/{config?.needsReviewCount||review.length})</summary><div>{review.map(q=><article key={q.id}><header><span><b>{q.subject}</b> · {q.topic}</span><small>{q.sourceFileName}</small></header><p>{q.stem}</p><ol>{q.options.map((x,i)=><li key={i} className={i===q.correctIndex?'answer':''}>{String.fromCharCode(65+i)}. {x}</li>)}</ol><div className="daily-drive__evidence"><b>Giải thích:</b> {q.explanation}{typeof q.provenance?.evidenceText==='string'&&<><br/><b>Căn cứ trong nguồn:</b> {String(q.provenance.evidenceText)}</>}</div><footer><button disabled={busy} className="approve" onClick={()=>void reviewOne(q,'expert_approved')}><CheckCircle2/>Duyệt</button><button disabled={busy} className="reject" onClick={()=>void reviewOne(q,'rejected')}><XCircle/>Loại</button></footer></article>)}</div></details>}
  </section>;
}
