import {useEffect,useMemo,useState} from 'react';
import {Brain,Clock3,Database,RefreshCw,RotateCcw,Send,ShieldCheck,Target} from 'lucide-react';
import {examQuestions} from '../../data/examQuestions';
import {analyzeExamGaps,localGapAnalysis} from '../../services/aiService';
import {askServerAi,renderAiAnswer} from '../../modules/ai';
import {getExamConfigV2,saveExamAnswerV2,startExamSessionV2,submitExamSessionV2,type ExamV2Config,type ExamV2PracticeAnswer,type ExamV2Question,type ExamV2Result} from '../../services/examSessionService';
import {readCachedMember} from '../../services/authService';
import {recordExamAnswer,recordExamResult} from '../../services/studentJourneyService';
import type {ExamAnswer,ExamMode,ExamQuestion} from '../../types';

const shuffle=<T,>(x:T[])=>{const a=[...x];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const mmss=(seconds:number)=>`${Math.floor(Math.max(0,seconds)/60)}:${String(Math.max(0,seconds)%60).padStart(2,'0')}`;
const legacySource=(q:ExamQuestion)=>[q.classicalCitation,q.modernReference].filter(Boolean).join(' · ');
const localTutor=(domain:string,topic:string,source:string)=>`A.I cục bộ đang hướng dẫn suy luận theo ngữ cảnh câu hỏi:\n\n1. Nhận diện dữ kiện: xác định từ khóa quyết định thuộc ${domain} và liên hệ với chủ đề ${topic}.\n2. Loại trừ: loại lựa chọn mâu thuẫn với nguyên tắc bệnh cơ, Bát cương/tạng tượng/pháp trị liên quan trước khi so sánh hai lựa chọn gần đúng.\n3. Điểm cần nhớ: đối chiếu lại với ${source||'nguồn ngân hàng đã kiểm định'} sau khi bạn đã chọn đáp án.\n\nChế độ này không tiết lộ đáp án trước khi người học lựa chọn.`;

export default function ExamCenter(){
  const [mode,setMode]=useState<ExamMode>('practice'),[legacyQs,setLegacyQs]=useState<ExamQuestion[]>(()=>examQuestions),[serverQs,setServerQs]=useState<ExamV2Question[]>([]),[idx,setIdx]=useState(0),[answers,setAnswers]=useState<Record<string,number>>({}),[feedback,setFeedback]=useState<Record<string,ExamV2PracticeAnswer>>({}),[seconds,setSeconds]=useState(60*60),[done,setDone]=useState(false),[advice,setAdvice]=useState(''),[tutor,setTutor]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[config,setConfig]=useState<ExamV2Config|null>(null),[sessionId,setSessionId]=useState(''),[serverResult,setServerResult]=useState<ExamV2Result|null>(null);
  const identity=readCachedMember()?.id||null,serverActive=Boolean(sessionId&&serverQs.length),qServer=serverQs[idx],qLegacy=legacyQs[idx],q=serverActive?qServer:qLegacy,selected=q?answers[q.id]:undefined;

  useEffect(()=>{let alive=true;void getExamConfigV2().then(x=>{if(alive)setConfig(x)}).catch(e=>{if(alive)setErr((e as Error).message)});return()=>{alive=false}},[]);
  useEffect(()=>{if(mode!=='mock'||done)return;const t=window.setInterval(()=>setSeconds(s=>{if(s<=1){window.clearInterval(t);setDone(true);if(sessionId)void finishServer();return 0}return s-1}),1000);return()=>window.clearInterval(t)},[mode,done,sessionId]);

  const legacyResult=useMemo(()=>legacyQs.map(x=>({questionId:x.id,selectedIndex:answers[x.id]??null,correct:answers[x.id]===x.correctIndex,topic:x.topic,domain:x.domain} as ExamAnswer)),[answers,legacyQs]);
  const legacyScore=Math.round((legacyResult.filter(x=>x.correct).length/Math.max(1,legacyQs.length))*100);
  const currentCount=serverActive?serverQs.length:legacyQs.length;
  const score=serverResult?.score??legacyScore;
  const resultReview=serverResult?.review??[];

  const finishServer=async()=>{if(!sessionId||busy)return;setBusy(true);setErr('');try{const result=await submitExamSessionV2(sessionId);setServerResult(result);setDone(true);recordExamResult(result.score,identity);const weak=[...new Set(result.review.filter(x=>!x.correct).map(x=>x.topic))].slice(0,4);if(!weak.length){setAdvice('Kết quả chưa cho thấy lỗ hổng nổi bật. Duy trì ôn tập xen kẽ bốn nhóm nội dung.');return}try{const sources=result.review.filter(x=>!x.correct).slice(0,8).map(x=>({id:x.id,title:`${x.domain} · ${x.topic}`,text:`Giải thích: ${x.explanation}. Nguồn: ${x.sourceRef}`,url:null}));const ai=await askServerAi(`Phân tích lỗ hổng luyện thi YHCT. Chủ đề sai: ${weak.join(', ')}. Đưa kế hoạch học ngắn gọn, không chẩn đoán và không bịa nguồn.`,'exam',sources);setAdvice(ai.degraded?`Ưu tiên ôn: ${weak.join(', ')}. Cloud A.I đang chuyển chế độ; hãy đọc lại giải thích từng câu sai, nhóm lỗi theo chủ đề rồi làm lại câu tương tự trước khi mở rộng y văn.`:renderAiAnswer(ai))}catch{setAdvice(`Ưu tiên ôn: ${weak.join(', ')}. Hãy đọc lại giải thích từng câu sai rồi làm lại theo nhóm chủ đề.`)}}catch(e){setErr((e as Error).message);setDone(false)}finally{setBusy(false)}};

  const submit=async()=>{if(serverActive){await finishServer();return}setDone(true);recordExamResult(legacyScore,identity);setAdvice(await analyzeExamGaps(legacyResult,legacyQs))};

  const restart=async(m:ExamMode)=>{setMode(m);setIdx(0);setAnswers({});setFeedback({});setServerResult(null);setSessionId('');setServerQs([]);setDone(false);setAdvice('');setTutor('');setErr('');setSeconds(60*60);if(config?.ready){setBusy(true);try{const s=await startExamSessionV2(m);setSessionId(s.sessionId);setServerQs(s.questions);setSeconds(Math.max(1,Math.round((new Date(s.deadlineAt).getTime()-Date.now())/1000))||s.durationMinutes*60)}catch(e){setErr((e as Error).message);if(m==='mock'){setMode('practice');setLegacyQs(examQuestions)}else setLegacyQs(examQuestions)}finally{setBusy(false)}}else{setLegacyQs(m==='mock'?shuffle(examQuestions):examQuestions);if(m==='mock'){setMode('practice');setErr(`Phiên thi chuẩn 50 câu chưa mở vì ngân hàng đã kiểm định hiện có ${config?.eligibleCount??0}/50 câu. Hệ thống không tự nhân bản hoặc bịa đáp án; bạn vẫn có thể luyện tập ngân hàng hiện có.`)}}};

  const choose=async(i:number)=>{if(!q||busy)return;const firstChoice=answers[q.id]===undefined;setAnswers(a=>({...a,[q.id]:i}));setTutor('');if(serverActive){setBusy(true);try{const r=await saveExamAnswerV2(sessionId,q.id,i);if(mode==='practice')setFeedback(f=>({...f,[q.id]:r}));if(firstChoice)recordExamAnswer(identity,mode==='practice'?r.correct:undefined)}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}else if(firstChoice&&qLegacy)recordExamAnswer(identity,i===qLegacy.correctIndex)};

  const askTutor=async()=>{if(!q||busy)return;setBusy(true);setTutor('');setErr('');const domain=String(q.domain),topic=String(q.topic),stem=String(q.stem),options=q.options.join(' | '),source=serverActive?(qServer.sourceRef||'Ngân hàng đã kiểm định'):legacySource(qLegacy);try{const answer=await askServerAi(`Bạn là gia sư luyện thi YHCT. Hướng dẫn cách suy luận cho câu sau nhưng KHÔNG tiết lộ đáp án trực tiếp trước khi người học chọn: ${stem}. Các lựa chọn: ${options}. Phân môn: ${domain}; chủ đề: ${topic}. Trả lời ngắn gọn theo 3 bước: nhận diện dữ kiện, loại trừ, điểm cần nhớ.`,'exam',[{id:q.id,title:`${domain} · ${topic}`,text:`${stem}. Nguồn nội bộ: ${source}`,url:null}]);setTutor(answer.degraded?localTutor(domain,topic,source):renderAiAnswer(answer))}catch{setTutor(localTutor(domain,topic,source))}finally{setBusy(false)}};

  const practiceFeedback=serverActive?feedback[qServer?.id]:selected!==undefined&&qLegacy?{accepted:true,correct:selected===qLegacy.correctIndex,correctIndex:qLegacy.correctIndex,explanation:qLegacy.explanation,sourceRef:legacySource(qLegacy)}:undefined;

  if(done)return <section className="panel exam-result"><Target/><h2>Kết quả {mode==='mock'?'Thi thử':'Luyện tập'}</h2><div className="score">{score}/100</div><b>{score>=60?'ĐẠT':'CHƯA ĐẠT'}</b>{serverResult?<p>Đúng {serverResult.correctCount}/{serverResult.total} câu · phiên thi chấm server-side.</p>:<p>Chủ đề cần ưu tiên: {localGapAnalysis(legacyResult).join(', ')||'Không có lỗ hổng nổi bật'}</p>}<div className="ai-note"><Brain/> {advice||'Đang tổng hợp khuyến nghị…'}</div>{resultReview.length>0&&<details><summary>Xem giải thích câu sai</summary><div className="exam-review-list">{resultReview.filter(x=>!x.correct).slice(0,20).map((x,n)=><article key={x.id}><b>{n+1}. {x.domain} · {x.topic}</b><p>{x.explanation}</p>{x.sourceRef&&<small>{x.sourceRef}</small>}</article>)}</div></details>}<button onClick={()=>void restart(mode)}><RotateCcw/> Làm lại</button></section>;

  return <section className="panel exam-center-v2"><div className="row between"><div><h2>National Exam Prep</h2><p>Luyện thi Đánh giá Năng lực Bác sĩ YHCT · tiến độ được đồng bộ về My HIU YHCT trên thiết bị này</p></div><div className="seg"><button className={mode==='practice'?'active':''} onClick={()=>void restart('practice')}>Luyện tập</button><button className={mode==='mock'?'active':''} disabled={!config?.ready||busy} title={!config?.ready?'Chỉ mở khi đủ 50 câu đã kiểm định':''} onClick={()=>void restart('mock')}>Thi thử 50 câu</button></div></div>
    <div className="exam-standard"><span><ShieldCheck/> Chuẩn phiên thi: <b>{config?.questionCount||50} câu · {config?.durationMinutes||60} phút</b></span><span><Database/> Ngân hàng đã kiểm định: <b>{config?.eligibleCount??'…'}/50</b>{config?.expertApprovedCount?` · chuyên gia duyệt ${config.expertApprovedCount}`:''}</span></div>
    {!config?.ready&&config&&<div className="warning">Ngân hàng chuẩn đang kiểm định. Hệ thống không dùng câu hỏi/đáp án chưa xác minh để đủ số lượng giả tạo; luyện tập hiện dùng ngân hàng nội bộ đã có.</div>}{err&&<div className="error" role="status">{err}</div>}
    {mode==='mock'&&<div className="timer"><Clock3/> {mmss(seconds)}</div>}
    {q?<><div className="exam-meta">Câu {idx+1}/{currentCount} · {String(q.domain)} · {String(q.topic)} {serverActive&&<span>· server integrity</span>}</div><h3>{q.stem}</h3><div className="options">{q.options.map((o,i)=><button key={`${q.id}-${i}`} disabled={busy||(mode==='practice'&&selected!==undefined)} className={selected===i?'chosen':''} onClick={()=>void choose(i)}>{String.fromCharCode(65+i)}. {o}</button>)}</div>
      <div className="row exam-ai-row"><button className="secondary" disabled={busy} onClick={()=>void askTutor()}><Brain/>{busy?'A.I đang xử lý…':'A.I hướng dẫn suy luận'}</button>{config&&!config.ready&&<button className="secondary" onClick={()=>void getExamConfigV2().then(setConfig)}><RefreshCw/> Kiểm tra ngân hàng</button>}</div>{tutor&&<div className="ai-note"><Brain/> {tutor}</div>}
      {mode==='practice'&&practiceFeedback?.accepted&&<div className={practiceFeedback.correct?'explain ok':'explain bad'}><b>{practiceFeedback.correct?'Chính xác':'Chưa chính xác'}{typeof practiceFeedback.correctIndex==='number'?` · Đáp án ${String.fromCharCode(65+practiceFeedback.correctIndex)}`:''}</b><p>{practiceFeedback.explanation}</p>{practiceFeedback.sourceRef&&<small>{practiceFeedback.sourceRef}</small>}</div>}
      <div className="row between"><button disabled={idx===0||busy} onClick={()=>setIdx(i=>i-1)}>← Trước</button>{idx<currentCount-1?<button disabled={busy} onClick={()=>setIdx(i=>i+1)}>Tiếp →</button>:<button disabled={busy} onClick={()=>void submit()}><Send/> {busy?'Đang nộp…':'Nộp bài'}</button>}</div></>:<div className="warning">Đang chuẩn bị ngân hàng câu hỏi…</div>}
  </section>;
}
