import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,ChevronDown,FileQuestion,LoaderCircle,RotateCcw,Send} from 'lucide-react';
import {getPracticeQuizConfig,getPracticeQuizPage,submitPracticeQuiz,type PracticeQuizConfig,type PracticeQuizQuestion,type PracticeQuizResult} from '../../services/practiceQuizService';
import '../../practice-bank-quiz.css';

const PAGE_SIZE=25;

export default function PracticeBankQuiz(){
  const [config,setConfig]=useState<PracticeQuizConfig|null>(null),[subject,setSubject]=useState(''),[questions,setQuestions]=useState<PracticeQuizQuestion[]>([]),[answers,setAnswers]=useState<Record<string,number>>({}),[result,setResult]=useState<PracticeQuizResult|null>(null),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const seed=useRef(crypto.randomUUID());
  const guest=config?.authenticated===false;
  useEffect(()=>{let alive=true;void getPracticeQuizConfig().then(x=>{if(alive)setConfig(x)}).catch(e=>{if(alive)setMessage((e as Error).message)});return()=>{alive=false}},[]);
  const load=async(reset=false)=>{if(busy)return;setBusy(true);setMessage('');try{if(reset){seed.current=crypto.randomUUID();setAnswers({});setResult(null)}const offset=reset?0:questions.length;const page=await getPracticeQuizPage(subject,offset,seed.current,PAGE_SIZE);setQuestions(old=>reset?page.questions:[...old,...page.questions]);setHasMore(page.hasMore);if(!page.questions.length)setMessage('Không có câu đã duyệt phù hợp với chủ đề này.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const submit=async()=>{if(busy||!questions.length)return;setBusy(true);setMessage('');try{setResult(await submitPracticeQuiz(questions,answers))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const reset=()=>{seed.current=crypto.randomUUID();setQuestions([]);setAnswers({});setResult(null);setHasMore(false);setMessage('')};
  const reviewById=new Map(result?.review.map(x=>[x.id,x])||[]);
  return <section className="panel practice-bank" aria-label="Luyện thi từ ngân hàng đã duyệt">
    <header className="practice-bank__head"><div><span><FileQuestion/> LUYỆN THI TỰ DO</span><h2>Google Quiz · không giới hạn 50 câu</h2><p>Dùng cùng ngân hàng đã được admin duyệt. Tải thêm theo từng nhóm, làm bao nhiêu câu tùy nhu cầu rồi nộp để chấm.</p></div><b>{guest?'Đăng nhập để mở ngân hàng':`${config?.eligibleCount??'…'} câu sẵn sàng`}</b></header>
    <div className="practice-bank__controls"><label><span>Chủ đề</span><div><select value={subject} disabled={guest||busy||questions.length>0} onChange={e=>setSubject(e.target.value)}><option value="">Tất cả chủ đề</option>{config?.subjects.map(x=><option key={x} value={x}>{x}</option>)}</select><ChevronDown/></div></label>{questions.length===0?<button className="primary" disabled={busy||!config?.ready} onClick={()=>void load(true)}>{busy?<LoaderCircle className="spin"/>:<FileQuestion/>}{guest?'Cần đăng nhập':'Bắt đầu luyện thi'}</button>:<button className="secondary" disabled={busy} onClick={reset}><RotateCcw/>Lượt mới</button>}</div>
    {guest&&!message&&<div className="practice-bank__message" role="status">Đăng nhập thành viên để dùng ngân hàng luyện thi đã duyệt và lưu tiến độ.</div>}
    {message&&<div className="practice-bank__message" role="status">{message}</div>}
    {questions.length>0&&<><div className="practice-bank__summary"><span><b>{questions.length}</b> câu đã tải</span><span><b>{Object.keys(answers).length}</b> câu đã chọn</span><span><b>{hasMore?'∞':'✓'}</b> {hasMore?'còn câu để tải':'đã tới cuối bộ lọc'}</span></div><div className="practice-bank__questions">{questions.map((q,index)=>{const review=reviewById.get(q.id);return <article key={q.id} className={review?review.correct?'is-correct':'is-wrong':''}><header><b>Câu {index+1}</b><small>{q.subject} · {q.topic}</small></header><h3>{q.stem}</h3><div className="practice-bank__options">{q.options.map((option,i)=><label key={`${q.id}-${i}`} className={`${answers[q.id]===i?'selected':''}${review&&review.correctIndex===i?' correct':''}`}><input type="radio" name={`quiz-${q.id}`} disabled={busy||!!result} checked={answers[q.id]===i} onChange={()=>setAnswers(a=>({...a,[q.id]:i}))}/><b>{String.fromCharCode(65+i)}</b><span>{option}</span></label>)}</div>{review&&<div className="practice-bank__review"><CheckCircle2/><div><b>{review.correct?'Chính xác':`Đáp án đúng: ${String.fromCharCode(65+review.correctIndex)}`}</b><p>{review.explanation}</p><small>{review.sourceFileName}{review.evidenceText?` · Dẫn chứng: ${review.evidenceText}`:''}</small></div></div>}</article>})}</div>{!result&&<div className="practice-bank__actions">{hasMore&&<button className="secondary" disabled={busy} onClick={()=>void load(false)}>{busy?<LoaderCircle className="spin"/>:<FileQuestion/>}Tải thêm {PAGE_SIZE} câu</button>}<button className="primary" disabled={busy||!Object.keys(answers).length} onClick={()=>void submit()}><Send/>Nộp bài ({questions.length} câu đã tải)</button></div>}{result&&<div className="practice-bank__result"><CheckCircle2/><div><b>{result.score}/100 · đúng {result.correctCount}/{result.total}</b><p>Đã chấm server-side. Đáp án và giải thích chỉ được mở sau khi nộp.</p></div><button onClick={reset}><RotateCcw/>Luyện lượt mới</button></div>}</>}
  </section>;
}
