import {useEffect,useRef,useState} from 'react';
import {CheckCircle2,ChevronDown,CircleHelp,FileQuestion,LoaderCircle,RotateCcw,Send} from 'lucide-react';
import {getPracticeQuizConfig,getPracticeQuizPage,submitPracticeQuiz,type PracticeQuizConfig,type PracticeQuizQuestion,type PracticeQuizResult} from '../../services/practiceQuizService';
import {requestPracticeAnswerReview} from '../../services/dailyPracticeService';
import '../../practice-bank-quiz.css';

const QUESTION_COUNTS=[10,20,30,50] as const;

export default function PracticeBankQuiz(){
  const [config,setConfig]=useState<PracticeQuizConfig|null>(null),[subject,setSubject]=useState(''),[count,setCount]=useState<number>(20),[questions,setQuestions]=useState<PracticeQuizQuestion[]>([]),[answers,setAnswers]=useState<Record<string,number>>({}),[result,setResult]=useState<PracticeQuizResult|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reviewRequested,setReviewRequested]=useState<Set<string>>(()=>new Set());
  const seed=useRef(crypto.randomUUID());
  const guest=config?.authenticated===false;
  useEffect(()=>{let alive=true;void getPracticeQuizConfig().then(x=>{if(alive)setConfig(x)}).catch(e=>{if(alive)setMessage((e as Error).message)});return()=>{alive=false}},[]);
  const start=async()=>{if(busy)return;setBusy(true);setMessage('');try{seed.current=crypto.randomUUID();setAnswers({});setResult(null);setReviewRequested(new Set());const page=await getPracticeQuizPage(subject,0,seed.current,count);setQuestions(page.questions);if(!page.questions.length)setMessage('Không có câu đã duyệt phù hợp với nội dung này.');else if(page.questions.length<count)setMessage(`Nội dung hiện có ${page.questions.length} câu đã duyệt; hệ thống đã tải toàn bộ.`)}catch(e){setQuestions([]);setMessage((e as Error).message)}finally{setBusy(false)}};
  const submit=async()=>{if(busy||!questions.length)return;setBusy(true);setMessage('');try{setResult(await submitPracticeQuiz(questions,answers))}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
  const requestReview=async(questionId:string)=>{if(reviewRequested.has(questionId))return;try{await requestPracticeAnswerReview(questionId,'Sinh viên yêu cầu Ban Quản lý Học tập kiểm tra lại đáp án sau khi hoàn thành quiz.');setReviewRequested(current=>new Set(current).add(questionId));setMessage('Đã gửi yêu cầu kiểm tra đáp án. Câu hỏi vẫn giữ nguyên cho đến khi Ban Quản lý Học tập xác minh.')}catch(e){setMessage((e as Error).message)}};
  const reset=()=>{seed.current=crypto.randomUUID();setQuestions([]);setAnswers({});setResult(null);setReviewRequested(new Set());setMessage('')};
  const reviewById=new Map(result?.review.map(x=>[x.id,x])||[]);
  return <section className="panel practice-bank" aria-label="Quiz từ ngân hàng đã duyệt">
    <header className="practice-bank__head"><div><span><FileQuestion/> QUIZ HỌC TẬP</span><h2>Chọn nội dung → số câu → bắt đầu</h2><p>Chỉ dùng câu hỏi từ ngân hàng đã duyệt. Đáp án được chấm server-side và chỉ mở sau khi nộp.</p></div><b>{guest?'Đăng nhập để làm quiz':`${config?.eligibleCount??'…'} câu đã duyệt`}</b></header>
    <div className="practice-bank__controls"><label><span>Nội dung</span><div><select value={subject} disabled={guest||busy||questions.length>0} onChange={e=>setSubject(e.target.value)}><option value="">Tất cả nội dung</option>{config?.subjects.map(x=><option key={x} value={x}>{x}</option>)}</select><ChevronDown/></div></label><label><span>Số lượng câu</span><div><select value={count} disabled={guest||busy||questions.length>0} onChange={e=>setCount(Number(e.target.value))}>{QUESTION_COUNTS.map(x=><option key={x} value={x}>{x} câu</option>)}</select><ChevronDown/></div></label>{questions.length===0?<button className="primary" disabled={busy||!config?.ready} onClick={()=>void start()}>{busy?<LoaderCircle className="spin"/>:<FileQuestion/>}{guest?'Cần đăng nhập':'Bắt đầu làm quiz'}</button>:<button className="secondary" disabled={busy} onClick={reset}><RotateCcw/>Chọn lại</button>}</div>
    {guest&&!message&&<div className="practice-bank__message" role="status">Đăng nhập thành viên để chọn nội dung và bắt đầu quiz.</div>}
    {message&&<div className="practice-bank__message" role="status">{message}</div>}
    {questions.length>0&&<><div className="practice-bank__summary"><span><b>{questions.length}</b> câu trong lượt này</span><span><b>{Object.keys(answers).length}</b> câu đã chọn</span><span><b>{subject||'Tổng hợp'}</b> nội dung</span></div><div className="practice-bank__questions">{questions.map((q,index)=>{const review=reviewById.get(q.id),requested=reviewRequested.has(q.id);return <article key={q.id} className={review?review.correct?'is-correct':'is-wrong':''}><header><b>Câu {index+1}</b><small>{q.subject} · {q.topic}</small></header><h3>{q.stem}</h3><div className="practice-bank__options">{q.options.map((option,i)=><label key={`${q.id}-${i}`} className={`${answers[q.id]===i?'selected':''}${review&&review.correctIndex===i?' correct':''}`}><input type="radio" name={`quiz-${q.id}`} disabled={busy||!!result} checked={answers[q.id]===i} onChange={()=>setAnswers(a=>({...a,[q.id]:i}))}/><b>{String.fromCharCode(65+i)}</b><span>{option}</span></label>)}</div>{review&&<div className="practice-bank__review"><CheckCircle2/><div><b>{review.correct?'Chính xác':`Đáp án đúng: ${String.fromCharCode(65+review.correctIndex)}`}</b><p>{review.explanation}</p><small>{review.sourceFileName}{review.evidenceText?` · Dẫn chứng: ${review.evidenceText}`:''}</small><button type="button" className="practice-bank__review-request" disabled={requested} onClick={()=>void requestReview(q.id)}><CircleHelp/>{requested?'Đã gửi yêu cầu kiểm tra':'Yêu cầu kiểm tra đáp án'}</button></div></div>}</article>})}</div>{!result&&<div className="practice-bank__actions"><button className="primary" disabled={busy||!Object.keys(answers).length} onClick={()=>void submit()}><Send/>Nộp bài ({questions.length} câu)</button></div>}{result&&<div className="practice-bank__result"><CheckCircle2/><div><b>{result.score}/100 · đúng {result.correctCount}/{result.total}</b><p>Đã chấm server-side. Nếu nghi ngờ đáp án, dùng “Yêu cầu kiểm tra đáp án” ngay dưới câu tương ứng.</p></div><button onClick={reset}><RotateCcw/>Làm lượt mới</button></div>}</>}
  </section>;
}
