-- QD4664 official catalog rows 15-28 of 70.

insert into private.herb_garden_species(seed_key,name,other_names,botanical_name,category,family,used_part,traditional_actions,dosage,caution,source_page,visual_variant,source_code,source_ref,seedable) values
  ('coi-xay', 'CỐI XAY', 'Giàng xay, quýnh ma, ma bản thảo, kim hoa thảo', 'Abutilon indicum (L.) Sweet', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bông (Malvaceae)', 'Bộ phận trên mặt đất', 'Giải biểu nhiệt, hoạt huyết, tiêu thũng. Chữa cảm sốt do phong nhiệt, đau đầu, tai ù, tai điếc, sốt vàng da, bí tiểu tiện, phù thũng, lở ngứa, dị ứng.', 'Ngày dùng 8 - 12g (dạng khô), 20 – 40g (cây tươi), sắc uống.', '', 15, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('cot-khi', 'CỐT KHÍ', 'Cốt khí củ', 'Reynoutria japonica Houtt.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Rau răm (Polygonaceae).', 'Rễ phơi hay sấy khô.', 'Khu phong trừ thấp, hoạt huyết, thông kinh, chỉ khái (giảm ho), hóa đờm, chỉ thống. Chữa đau nhức gân xương, ngã sưng đau ứ huyết, bế kinh, hoàng đản, ho nhiều đờm, mụn nhọt lở loét.', 'Ngày dùng 9 - 15g, sắc uống, dùng ngoài sắc lấy nước để bôi, rửa, hoặc chế thành cao, bôi.', '', 16, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('cuc-hoa', 'CÚC HOA', 'Kim cúc, hoàng cúc, dã cúc, cam cúc', 'Chrysanthemum indicum L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae)', 'Cụm hoa', 'Phát tán phong nhiệt, giải độc, minh mục. Chữa các chứng đau đầu hoa mắt, chóng mặt, đau mắt đỏ, chảy nhiều nước mắt, mờ mắt, huyết áp cao, mụn nhọt, đinh độc.', 'Ngày dùng 8 – 16g (dạng khô), sắc uống.', '', 17, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('cuc-tan', 'CÚC TẦN', 'Cây lức, từ bi, phật phà (Tày)', 'Pluchea indica (L.) Less.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae).', 'Rễ, lá, cành.', 'Phát tán phong nhiệt, tiêu độc, lợi tiểu, tiêu đàm. Chữa cảm mạo phong nhiệt, sốt không ra mồ hôi, phong thấp, tê bại, đau nhức xương khớp.', 'Ngày dùng 8 – 16g, sắc uống.', '', 18, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('danh-danh', 'DÀNH DÀNH', 'Chi tử', 'Gardenia jasminoides J. Ellis', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cà phê (Rubiaceae).', 'Quả đã phơi khô.', 'Thanh nhiệt trừ phiền, lợi tiểu, lương huyết, chỉ huyết. Chữa sốt cao, người bồn chồn khó ngủ, vàng da, tiểu tiện khó, tiểu tiện ra máu, chảy máu cam. Nôn ra máu, dùng ngoài trị sưng đau do sang chấn.', 'Ngày dùng 6 – 12g, sắc uống.', '', 19, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('dau-tam', 'DÂU TẰM', 'Dâu ta, tang', 'Morus alba L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Dâu tằm (Moraceae)', 'Rễ, thân, lá, quả.', 'Vỏ rễ dâu có tác dụng thanh phế nhiệt bình suyễn, tiêu thũng, giảm ho, trừ đờm, hạ suyễn. Chữa phế nhiệt, ho suyễn, hen, ho ra máu, trẻ con ho gà, phù thũng, bụng trướng to, tiểu tiện không thông; Lá dâu có tác dụng tán phong thanh nhiệt, thanh can, sáng mắt. Chữa cảm mạo phong nhiệt, phế nhiệt, ho, viêm họng, nhức đầu, mắt đỏ, chảy nước mắt, đậu lào, phát ban, cao huyết áp, mất ngủ; Cành dâu có tác dụng trừ phong thấp, lợi các khớp, thông kinh hoạt lạc, tiêu viêm. Chữa phong thấp đau nhức các đầu xương, cước khí, sưng lở, chân tay co quắp.', 'Vỏ rễ: ngày dùng 6 – 12g (có thể dùng tới 20 – 40g), sắc uống. Lá: ngày dùng 5 – 12g, sắc uống. Cành: ngày dùng: 9 – 15g (có thể dùng tới 40 – 60g), sắc uống.', '', 20, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('dia-hoang', 'ĐỊA HOÀNG', 'Sinh địa hoàng.', 'Rehmannia glutinosa (Gaertn.) Libosch.ex Steud.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Hoa mõm chó (Scrophulariaceae)', 'Rễ củ phơi hay sấy khô.', 'Bổ âm, thanh nhiệt lương huyết, sinh tân dịch. Chữa âm hư, sốt về chiều, khát nước, thiếu máu, suy nhược cơ thể, tân dịch khô, phiền táo mất ngủ.', 'Ngày dùng 8 – 16g, sắc uống.', '', 21, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('dia-lien', 'ĐỊA LIỀN', 'Sơn nại, tam nại, thiền liền, sa khương', 'Kaempferia galanga L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Gừng (Zingiberaceae)', 'Thân rễ (Rhizoma Kaempferiae) thái lát, phơi sấy khô, lá.', 'Ôn trung, tán hàn, trừ thấp, tiêu thực. Chữa ngực bụng lạnh đau, tiêu chảy, ăn uống khó tiêu, đau dạ dày, nôn mửa, đau nhức xương khớp.', 'Ngày dùng 4 - 8g, sắc uống. Dùng ngoài ngâm rượu để xoa bóp.', '', 22, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('diep-ha-chau', 'DIỆP HẠ CHÂU', 'Diệp hạ châu đắng, Cây chó đẻ răng cưa', 'Phyllanthus urinaria L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thầu dầu (Euphorbiaceae).', 'Phần trên mặt đất sấy hoặc phơi khô.', 'Tiêu độc, sát trùng, lợi mật, thanh can, tiêu viêm tán ứ, lợi thủy. Chữa viêm gan hoàng đảm, viêm họng, tắc sữa, kinh bế, viêm da thần kinh, viêm thận, sỏi tiết niệu, mụn nhọt, lở ngứa ngoài da.', 'Ngày dùng 8 - 20g, sắc uống.', '', 23, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('dinh-lang', 'ĐINH LĂNG', 'Cây gỏi cá, nam dương sâm', 'Polyscias fruticosa (L.) Harms', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Nhân sâm (Araliaceae)', 'Rễ, thân, cành, lá.', 'Bổ khí, tiêu thực, lợi sữa, tiêu viêm, giải độc. Rễ Đinh lăng chữa suy nhược cơ thể, gầy yếu, mệt mỏi, ngủ ít, tiêu hóa kém, phụ nữ sau đẻ ít sữa. Lá chữa cảm sốt, mụn nhọt, giã đắp sưng tấy, sưng vú. Thân, cành chữa thấp khớp, đau lưng.', 'Rễ: Ngày dùng 3 - 6g, hãm, hoặc đun sôi trong 15 phút, chia 2 - 3 lần uống; Lá tươi: ngày dùng 30 - 50g, giã đắp; Thân, cành: ngày dùng 30 - 50g, sắc uống.', '', 24, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('don-la-do', 'ĐƠN LÁ ĐỎ', 'Đơn đỏ, Đơn tía, Đơn mặt trời.', 'Excoecaria cochichinensis Lour.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thầu dầu (Euphorbiaceae). Cây được trồng làm thuốc, làm cảnh ở nhiều địa phương nước ta.', 'Rễ, vỏ thân, lá.', 'Thanh nhiệt giải độc, hoạt huyết, giảm đau, lợi tiểu. Chữa cảm sốt, đau nhức xương khớp, kinh nguyệt không đều, áp xe vú, dị ứng, mụn nhọt, lở ngứa, ỉa chảy lâu ngày.', 'Ngày dùng 6 - 12g, sắc uống.', '', 25, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('dua-can', 'DỪA CẠN', 'Hải Đằng, Dương giác, trường xuân hoa', 'Catharanthus roseus (L.) G. Don', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Trúc đào (Apocynaceae).', 'Thân, lá, rễ', 'Hoạt huyết, bình can, tiêu thũng, giải độc, an thần. Chữa tăng huyết áp, kinh nguyệt không đều, lỵ, bí tiểu.', 'Ngày dùng 8 - 12g, sắc uống.', 'Phụ nữ có thai không được dùng.', 26, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('gai', 'GAI', 'Gai làm bánh, gai tuyết, trư ma.', 'Boehmeria nivea (L.) Gaudich.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Gai (Urticaceae)', 'Rễ, lá', 'Rễ có tác dụng chỉ huyết, an thai, thanh nhiệt, giải độc. Chữa động thai, chảy máu dọa sẩy, đái đục, đái ra máu. Lá có tác dụng lương huyết, chỉ huyết, dùng trị chảy máu, làm lành vết thương.', 'Rễ: Ngày dùng 6 - 20g (tươi) hay 8 - 12g (khô), đun sôi với 400ml nước đến khi còn lại 100 ml, uống 1 lần trong ngày. Lá: dùng ngoài lượng vừa đủ, giã đắp vào vết thương.', '', 27, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('gung', 'GỪNG', 'Khương', 'Zingiber officinale Rosc.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Gừng (Zingiberaceae)', 'Thân rễ (củ)', 'Gừng khô (Can khương) Ôn trung, trục hàn, hồi dương, thông mạch. Gừng tươi chữa cảm mạo phong hàn, nhức đầu, ngạt mũi, ho có đờm, nôn mửa, bụng đầy trướng, kích thích tiêu hóa, sát trùng, hành thủy, giải độc ngứa do bán hạ, cua, cá. Bào khương chữa đau bụng, lạnh bụng, đi ngoài. Gừng khô và tiêu khương (gừng nướng) chữa đau bụng do lạnh, bụng đầy trướng không tiêu, thổ tả, chân tay giá lạnh, mạch nhỏ, đàm ẩm, ho suyễn và thấp khớp. Thán khương thường dùng chỉ huyết.', 'Gừng tươi, Bào khương: Ngày dùng 4 – 8g, sắc uống; Gừng khô và Tiêu khương: Ngày dùng 4 – 20g, dùng dạng thuốc sắc hoặc hoàn tán; Thán khương: Ngày dùng 4 – 8g, sắc uống.', '', 28, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true)
on conflict(seed_key) do update set
  name=excluded.name,other_names=excluded.other_names,botanical_name=excluded.botanical_name,category=excluded.category,
  family=excluded.family,used_part=excluded.used_part,traditional_actions=excluded.traditional_actions,dosage=excluded.dosage,
  caution=excluded.caution,source_page=excluded.source_page,visual_variant=excluded.visual_variant,source_code=excluded.source_code,
  source_ref=excluded.source_ref,seedable=excluded.seedable;
