-- Social Gia Vien: visit/help, independent spendable garden credits, market and decor.
create table if not exists public.herb_garden_profiles(member_id uuid primary key references public.club_members(id) on delete cascade,theme text not null default 'bamboo' check(theme in('bamboo','lotus','stone','lantern','herbal-paper')),decor jsonb not null default '[]'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.herb_garden_wallets(member_id uuid primary key references public.club_members(id) on delete cascade,balance integer not null default 0 check(balance>=0),initialized_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.herb_garden_trade_listings(id uuid primary key default gen_random_uuid(),seller_member_id uuid not null references public.club_members(id) on delete cascade,buyer_member_id uuid references public.club_members(id) on delete set null,seed_key text not null,quantity integer not null check(quantity between 1 and 20),price_credits integer not null check(price_credits between 1 and 10000),status text not null default 'active' check(status in('active','sold','cancelled')),created_at timestamptz not null default now(),sold_at timestamptz,cancelled_at timestamptz);
create index if not exists herb_garden_trade_active_idx on public.herb_garden_trade_listings(status,created_at desc);
alter table public.herb_garden_profiles enable row level security;alter table public.herb_garden_wallets enable row level security;alter table public.herb_garden_trade_listings enable row level security;
revoke all on public.herb_garden_profiles,public.herb_garden_wallets,public.herb_garden_trade_listings from anon,authenticated;

create or replace function private.ensure_herb_garden_wallet(p_member_id uuid) returns integer language plpgsql security definer set search_path='' as $$
declare bal integer;begin insert into public.herb_garden_wallets(member_id,balance) select p_member_id,greatest(0,least(100000,coalesce(sum(e.credits) filter(where e.revoked_at is null),0)::integer)) from public.community_credit_events e where e.member_id=p_member_id on conflict(member_id) do nothing;select balance into bal from public.herb_garden_wallets where member_id=p_member_id;return coalesce(bal,0);end $$;

create or replace function public.herb_garden_directory_v1(p_query text default '',p_limit integer default 30)
returns table(member_id uuid,display_name text,full_name text,avatar_url text,theme text,decor jsonb,plant_status text,plant_progress integer)
language sql security definer set search_path='' as $$
with me as(select private.current_member_id() mid),candidates as(select m.id,m.full_name,coalesce(m.herbal_alias,private.herbal_alias_for_name(m.full_name,m.id)) alias,m.avatar_url,coalesce(g.theme,'bamboo') theme,coalesce(g.decor,'[]'::jsonb) decor from public.club_members m left join public.herb_garden_profiles g on g.member_id=m.id cross join me where me.mid is not null and private.is_approved() and m.status='approved' and m.login_enabled and not m.data_conflict and m.id<>me.mid and(btrim(coalesce(p_query,''))='' or m.full_name ilike'%'||btrim(p_query)||'%' or coalesce(m.herbal_alias,'') ilike'%'||btrim(p_query)||'%') order by m.full_name limit least(greatest(coalesce(p_limit,30),1),50))
select c.id,c.alias,c.full_name,c.avatar_url,c.theme,c.decor,p.status,case when p.id is null then 0 when p.status in('mature','harvested','dead') then 100 else greatest(0,least(100,round((extract(epoch from(now()-p.planted_at))/greatest(1,extract(epoch from(p.matures_at-p.planted_at))))*100)::integer)) end from candidates c left join lateral(select x.* from public.herb_garden_plants x where x.member_id=c.id order by case when x.status in('growing','mature') and x.harvested_at is null and x.died_at is null then 0 else 1 end,x.planted_at desc limit 1)p on true;
$$;

create or replace function public.herb_garden_visit_v1(p_member_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare visitor uuid:=private.current_member_id();result jsonb;begin if visitor is null or not private.is_approved() then raise exception 'Approved member required';end if;if not exists(select 1 from public.club_members where id=p_member_id and status='approved' and login_enabled and not data_conflict) then raise exception 'Garden owner unavailable';end if;perform private.herb_garden_sync_member_v2(p_member_id);select jsonb_build_object('owner',jsonb_build_object('id',m.id,'display_name',coalesce(m.herbal_alias,private.herbal_alias_for_name(m.full_name,m.id)),'full_name',m.full_name,'avatar_url',m.avatar_url),'theme',coalesce(g.theme,'bamboo'),'decor',coalesce(g.decor,'[]'::jsonb),'plant',case when p.id is null then null else jsonb_build_object('id',p.id,'status',p.status,'planted_at',p.planted_at,'matures_at',p.matures_at,'water_count',p.water_count,'fertilizer_count',p.fertilizer_count,'can_water',p.status='growing' and now()<p.matures_at and p.last_water_slot<floor(extract(epoch from(now()-p.planted_at))/21600)::integer,'can_fertilize',p.status='growing' and now()<p.matures_at and p.last_fertilizer_day<floor(extract(epoch from(now()-p.planted_at))/86400)::integer,'name',case when now()>=p.matures_at or p.status in('mature','dead','harvested') then s.name end,'visual_variant',case when now()>=p.matures_at or p.status in('mature','dead','harvested') then s.visual_variant end)end)into result from public.club_members m left join public.herb_garden_profiles g on g.member_id=m.id left join lateral(select x.* from public.herb_garden_plants x where x.member_id=m.id order by case when x.status in('growing','mature') and x.harvested_at is null and x.died_at is null then 0 else 1 end,x.planted_at desc limit 1)p on true left join private.herb_garden_species s on s.seed_key=p.seed_key where m.id=p_member_id;return result;end $$;

create or replace function public.herb_garden_help_v1(p_owner_id uuid,p_kind text) returns jsonb language plpgsql security definer set search_path='' as $$
declare helper uuid:=private.current_member_id();pid uuid;planted timestamptz;mature timestamptz;last_slot int;last_day int;slot_no int;day_no int;helper_name text;
begin if helper is null or not private.is_approved() then raise exception 'Approved member required';end if;if p_owner_id is null or p_owner_id=helper then raise exception 'Hãy dùng nút chăm sóc ở vườn của bạn';end if;if p_kind not in('water','fertilize') then raise exception 'Invalid care action';end if;if(select count(*) from public.herb_garden_events e where e.member_id=helper and e.event_type like'assist_%' and e.created_at>now()-interval'1 day')>=8 then raise exception 'Bạn đã đạt giới hạn 8 lượt hỗ trợ trong 24 giờ.';end if;perform private.herb_garden_sync_member_v2(p_owner_id);select p.id,p.planted_at,p.matures_at,p.last_water_slot,p.last_fertilizer_day into pid,planted,mature,last_slot,last_day from public.herb_garden_plants p where p.member_id=p_owner_id and p.status='growing' and p.harvested_at is null and p.died_at is null order by p.planted_at desc limit 1 for update;if pid is null or now()>=mature then raise exception 'Vườn này hiện không có cây cần chăm sóc.';end if;if p_kind='water' then slot_no:=floor(extract(epoch from(now()-planted))/21600)::integer;if slot_no<0 or slot_no>11 or last_slot>=slot_no then raise exception 'Cây chưa đến lượt tưới.';end if;update public.herb_garden_plants set last_watered_at=now(),last_water_slot=slot_no,water_count=least(12,water_count+1),last_cared_at=now(),care_count=care_count+1 where id=pid;insert into public.herb_garden_events(plant_id,member_id,event_type,slot_no,metadata) values(pid,helper,'assist_water',slot_no,jsonb_build_object('owner_id',p_owner_id));else day_no:=floor(extract(epoch from(now()-planted))/86400)::integer;if day_no<0 or day_no>2 or last_day>=day_no then raise exception 'Cây chưa đến lượt bón phân.';end if;update public.herb_garden_plants set last_fertilized_at=now(),last_fertilizer_day=day_no,fertilizer_count=least(3,fertilizer_count+1),last_cared_at=now(),care_count=care_count+1 where id=pid;insert into public.herb_garden_events(plant_id,member_id,event_type,slot_no,metadata) values(pid,helper,'assist_fertilize',day_no,jsonb_build_object('owner_id',p_owner_id));end if;select full_name into helper_name from public.club_members where id=helper;insert into public.notifications(member_id,actor_member_id,kind,title,body) values(p_owner_id,helper,'garden_help','Có bạn ghé Gia Viên',coalesce(helper_name,'Một thành viên')||case when p_kind='water' then' đã giúp tưới cây.' else' đã giúp bón phân.' end);perform private.audit_event('herb_garden.assist_'||p_kind,'herb_garden_plant',pid::text,'info',jsonb_build_object('owner_id',p_owner_id));return public.herb_garden_visit_v1(p_owner_id);end $$;

create or replace function public.herb_garden_profile_update_v1(p_theme text,p_decor jsonb default '[]'::jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare mid uuid:=private.current_member_id();clean jsonb;begin if mid is null or not private.is_approved() then raise exception 'Approved member required';end if;if p_theme not in('bamboo','lotus','stone','lantern','herbal-paper') then raise exception 'Invalid garden theme';end if;select coalesce(jsonb_agg(v),'[]'::jsonb) into clean from(select jsonb_array_elements_text(coalesce(p_decor,'[]'::jsonb))v where v in('pond','lantern','stone-path','bamboo-gate','lotus-pot','herb-sign') limit 6)q;insert into public.herb_garden_profiles(member_id,theme,decor,updated_at) values(mid,p_theme,clean,now()) on conflict(member_id) do update set theme=excluded.theme,decor=excluded.decor,updated_at=now();return jsonb_build_object('theme',p_theme,'decor',clean);end $$;

create or replace function public.herb_garden_market_v1(p_limit integer default 30) returns table(id uuid,seller_member_id uuid,seller_name text,herb_name text,botanical_name text,seed_key text,quantity integer,price_credits integer,created_at timestamptz) language sql security definer set search_path='' as $$ select l.id,l.seller_member_id,coalesce(m.herbal_alias,private.herbal_alias_for_name(m.full_name,m.id)),s.name,s.botanical_name,l.seed_key,l.quantity,l.price_credits,l.created_at from public.herb_garden_trade_listings l join public.club_members m on m.id=l.seller_member_id join private.herb_garden_species s on s.seed_key=l.seed_key where private.current_member_id() is not null and private.is_approved() and l.status='active' order by l.created_at desc limit least(greatest(coalesce(p_limit,30),1),60) $$;

create or replace function public.herb_garden_market_create_v1(p_seed_key text,p_quantity integer,p_price_credits integer) returns uuid language plpgsql security definer set search_path='' as $$
declare mid uuid:=private.current_member_id();rid uuid;qty int;begin if mid is null or not private.is_approved() then raise exception 'Approved member required';end if;if p_quantity not between 1 and 20 or p_price_credits not between 1 and 10000 then raise exception 'Số lượng hoặc giá không hợp lệ';end if;select quantity into qty from public.herb_garden_inventory where member_id=mid and seed_key=p_seed_key for update;if coalesce(qty,0)<p_quantity then raise exception 'Kho dược thảo không đủ số lượng';end if;update public.herb_garden_inventory set quantity=quantity-p_quantity,updated_at=now() where member_id=mid and seed_key=p_seed_key;insert into public.herb_garden_trade_listings(seller_member_id,seed_key,quantity,price_credits) values(mid,p_seed_key,p_quantity,p_price_credits) returning id into rid;perform private.ensure_herb_garden_wallet(mid);perform private.audit_event('herb_garden.market.create','garden_listing',rid::text,'info',jsonb_build_object('quantity',p_quantity,'price',p_price_credits));return rid;end $$;
create or replace function public.herb_garden_market_buy_v1(p_listing_id uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare buyer uuid:=private.current_member_id();seller uuid;sk text;qty int;price int;bal int;begin if buyer is null or not private.is_approved() then raise exception 'Approved member required';end if;select seller_member_id,seed_key,quantity,price_credits into seller,sk,qty,price from public.herb_garden_trade_listings where id=p_listing_id and status='active' for update;if seller is null then raise exception 'Tin giao dịch không còn khả dụng';end if;if seller=buyer then raise exception 'Không thể mua tin của chính bạn';end if;perform private.ensure_herb_garden_wallet(buyer);perform private.ensure_herb_garden_wallet(seller);select balance into bal from public.herb_garden_wallets where member_id=buyer for update;perform 1 from public.herb_garden_wallets where member_id=seller for update;if bal<price then raise exception 'Không đủ tín dụng vườn';end if;update public.herb_garden_wallets set balance=balance-price,updated_at=now() where member_id=buyer;update public.herb_garden_wallets set balance=balance+price,updated_at=now() where member_id=seller;insert into public.herb_garden_inventory(member_id,seed_key,quantity,updated_at) values(buyer,sk,qty,now()) on conflict(member_id,seed_key) do update set quantity=public.herb_garden_inventory.quantity+excluded.quantity,updated_at=now();update public.herb_garden_trade_listings set status='sold',buyer_member_id=buyer,sold_at=now() where id=p_listing_id;insert into public.notifications(member_id,actor_member_id,kind,title,body) values(seller,buyer,'garden_trade_sold','Dược liệu đã được mua',qty||' đơn vị dược liệu đã bán với '||price||' tín dụng vườn.');perform private.audit_event('herb_garden.market.buy','garden_listing',p_listing_id::text,'info',jsonb_build_object('seller_id',seller,'price',price));return true;end $$;
create or replace function public.herb_garden_market_cancel_v1(p_listing_id uuid) returns boolean language plpgsql security definer set search_path='' as $$
declare mid uuid:=private.current_member_id();sk text;qty int;begin if mid is null or not private.is_approved() then raise exception 'Approved member required';end if;select seed_key,quantity into sk,qty from public.herb_garden_trade_listings where id=p_listing_id and seller_member_id=mid and status='active' for update;if sk is null then return false;end if;update public.herb_garden_trade_listings set status='cancelled',cancelled_at=now() where id=p_listing_id;insert into public.herb_garden_inventory(member_id,seed_key,quantity,updated_at) values(mid,sk,qty,now()) on conflict(member_id,seed_key) do update set quantity=public.herb_garden_inventory.quantity+excluded.quantity,updated_at=now();return true;end $$;
create or replace function public.herb_garden_wallet_v1() returns integer language plpgsql security definer set search_path='' as $$declare mid uuid:=private.current_member_id();begin if mid is null or not private.is_approved() then raise exception 'Approved member required';end if;return private.ensure_herb_garden_wallet(mid);end $$;

revoke all on function public.herb_garden_directory_v1(text,integer),public.herb_garden_visit_v1(uuid),public.herb_garden_help_v1(uuid,text),public.herb_garden_profile_update_v1(text,jsonb),public.herb_garden_market_v1(integer),public.herb_garden_market_create_v1(text,integer,integer),public.herb_garden_market_buy_v1(uuid),public.herb_garden_market_cancel_v1(uuid),public.herb_garden_wallet_v1() from public,anon;
grant execute on function public.herb_garden_directory_v1(text,integer),public.herb_garden_visit_v1(uuid),public.herb_garden_help_v1(uuid,text),public.herb_garden_profile_update_v1(text,jsonb),public.herb_garden_market_v1(integer),public.herb_garden_market_create_v1(text,integer,integer),public.herb_garden_market_buy_v1(uuid),public.herb_garden_market_cancel_v1(uuid),public.herb_garden_wallet_v1() to authenticated;
