-- YHCT HIU 4.0 - official medicinal plant catalog from user-provided QD 4664/QD-BYT source
-- Facts are transcribed as printed; missing fields stay empty.

alter table private.herb_garden_species add column if not exists other_names text not null default '';
alter table private.herb_garden_species add column if not exists family text not null default '';
alter table private.herb_garden_species add column if not exists used_part text not null default '';
alter table private.herb_garden_species add column if not exists dosage text not null default '';
alter table private.herb_garden_species add column if not exists source_page integer;
alter table private.herb_garden_species add column if not exists visual_variant smallint not null default 1;
alter table private.herb_garden_species add column if not exists source_code text not null default 'legacy';
alter table private.herb_garden_species add column if not exists source_ref text not null default '';
alter table private.herb_garden_species add column if not exists seedable boolean not null default false;

do $$ begin
  if not exists(select 1 from pg_constraint where conname='herb_garden_species_visual_variant_chk') then
    alter table private.herb_garden_species add constraint herb_garden_species_visual_variant_chk check(visual_variant between 1 and 8);
  end if;
end $$;

update private.herb_garden_species set seedable=false where source_code='legacy';

insert into private.herb_garden_species(seed_key,name,other_names,botanical_name,category,family,used_part,traditional_actions,dosage,caution,source_page,visual_variant,source_code,source_ref,seedable) values
  ('bac-ha', 'BẠC HÀ', 'Bạc hà nam, nạt nặm, chạ phiéc hom (Tày)', 'Mentha arvensis L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae)', 'Bộ phận trên mặt đất', 'Sơ phong, thanh nhiệt, thấu chẩn, sơ can, giải uất, giải độc. Chữa cảm mạo phong nhiệt, cảm cúm, ngạt mũi, nhức đầu, đau mắt đỏ, thúc đẩy sởi mọc, ngực sườn đầy tức.', 'Ngày dùng 12 - 20g, hãm vào nước sôi 200 ml, cách 3 giờ uống một lần.', '', 1, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('bach-bo', 'BÁCH BỘ', 'Củ ba mươi, dây đẹt ác, hơ linh (Ba Na)', 'Stemona tuberosa Lour.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bách bộ (Stemonaceae)', 'Rễ', 'Nhuận phế, chỉ ho, sát trùng. Chữa các chứng ho mới hoặc ho lâu ngày, viêm phế quản mạn tính, trị giun kim, ngứa, ghẻ lở.', 'Ngày dùng 8 - 12g, sắc uống, thụt hậu môn điều trị giun kim, dùng 30 - 40g sắc lấy nước rửa điều trị ngứa, lở.', '', 2, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('bach-dong-nu', 'BẠCH ĐỒNG NỮ', 'Mò trắng, Mò mâm xôi, Bấn trắng', 'Clerodendrum chinense (Osbeck.) Mabb var. simplex (Mold.) S. L. Chen', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cỏ roi ngựa (Verbenaceae)', 'Rễ, lá, hoa', 'Thanh nhiệt, giải độc, khu phong trừ thấp, tiêu viêm. Rễ cây chữa gân xương đau nhức, mỏi lưng, mỏi gối, kinh nguyệt không đều, viêm túi mật, vàng da, vàng mắt. Dùng ngoài ngâm rửa trĩ, lòi dom. Lá cây chữa tăng huyết áp, khí hư bạch đới, Lá dùng ngoài trị vết thương, tắm ghẻ, chốc đầu. Hoa dùng trị ngứa.', 'Rễ ngày dùng 12 - 16g, sắc uống. Dùng 1 kg cành lá, rửa sạch, đun sôi với nước 30 phút, lọc lấy nước, nhỏ giọt liên tục lên vết thương hoặc ngâm vết thương ngày 2 lần, mỗi lần 1 giờ.', '', 3, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('bach-hoa-xa-thiet-thao', 'BẠCH HOA XÀ THIỆT THẢO', 'Cỏ lưỡi rắn hoa trắng', 'Hedyotis diffusa Willd.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cà phê (Rubiaceae)', 'Toàn cây', 'Thanh nhiệt giải độc, lợi niệu thông lâm, tiêu ung tán kết. Chữa phế nhiệt, hen suyễn, viêm họng, viêm Amydal, viêm đường tiết niệu, viêm đại tràng (trường ung). Dùng ngoài chữa vết thương, rắn cắn, côn trùng đốt.', 'Ngày dùng 15 - 60g (khô) sắc uống. Dùng ngoài, giã nát đắp tại chỗ.', '', 4, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ban-ha-nam', 'BÁN HẠ NAM', 'Cây chóc, chóc chuột, nam tinh, bán hạ ba thùy', 'Typhonium trilobatum (L.) Schott.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Ráy (Araceae).', 'Thân rễ. Khi dùng phải qua chế biến cẩn thận.', 'Hóa đàm táo thấp, giáng nghịch chỉ nôn, giáng khí chỉ ho. Chữa nôn, buồn nôn, đầy trướng bụng, ho có đờm, ho lâu ngày. Dùng ngoài chữa ong đốt, rắn rết cắn.', 'Ngày dùng 3 – 10g, sắc uống. Thường phối hợp với các vị thuốc khác.', 'Phụ nữ có thai dùng thận trọng.', 5, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('bo-chinh-sam', 'BỐ CHÍNH SÂM', 'Nhân sâm Phú yên, Thổ hào sâm', 'Abelmoschus moschatus Medik. ssp. tuberosus (Span) Borss.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bông (Malvaceae).', 'Rễ. Rửa sạch, ngâm nước gạo một đêm, đồ chín. Phơi khô, hoặc sấy khô.', 'Bổ khí, ích huyết, sinh tân dịch, chỉ khát (giảm ho), trừ đờm. Chữa cơ thể suy nhược, kém ăn, kém ngủ, thần kinh suy nhược, hoa mắt chóng mặt, đau dạ dầy, tiêu chảy, ho viêm họng, viêm phế quản, người háo khát, táo bón.', 'Ngày dùng 10 - 12g, sắc uống.', 'Nếu thể tạng hàn phải chích với gừng. Không dùng chung với Lê lô.', 6, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('bo-cong-anh', 'BỒ CÔNG ANH', 'Diếp dại, diếp trời, rau bồ cóc, rau mét, cây mũi mác', 'Lactuca indica L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae)', 'Phần trên mặt đất', 'Thanh nhiệt giải độc, tiêu viêm tán kết. Chữa mụn nhọt sang lở, tắc tia sữa, viêm tuyến vú, nhiễm trùng đường tiết niệu.', 'Ngày dùng 8 - 30 g (khô), 20 - 40g (cây tươi), ép lấy nước uống hoặc sắc uống. Đắp ngoài trị mụn nhọt, sưng vú, tắc tia sữa.', '', 7, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ca-gai-leo', 'CÀ GAI LEO', 'Cà vạnh, Cà cườm, Cà quánh, Cà quýnh.', 'Solanum procumbens Lour.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cà (Solanaceae).', 'Rễ (Thích gia căn), dây (Thích gia đằng).', 'Tán phong trừ thấp, tiêu độc, giảm đau. Chữa đau nhức gân xương, ho, ho gà, xơ gan, rắn cắn.', 'Ngày 16 - 20g, sắc uống.', '', 8, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('cam-thao-dat', 'CAM THẢO ĐẤT', 'Cam thảo nam, thổ cam thảo, dã cam thảo, r’gờm, t’rôm lạy (K’Ho)', 'Scoparia dulcis L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Hoa mõm chó (Scrophulariaceae)', 'Cả cây', 'Bổ tỳ, sinh tân, nhuận phế, thanh nhiệt, giải độc, lợi niệu. Chữa sốt, ho, viêm họng, ban chẩn, phế nhiệt gây ho, rong kinh, đái tháo đường.', 'Ngày dùng 16 - 20g (dạng khô); 20 - 40g (cây tươi), sắc hoặc hãm uống.', '', 9, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('co-man-trau', 'CỎ MẦN TRẦU', 'Cỏ chỉ tía, thanh tâm thảo, cao dag (Ba Na), hất t’rớ lạy (K’Ho)', 'Eleusine indica (L.) Geartn.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Lúa (Poaceae)', 'Cả cây', 'Lương huyết, thanh nhiệt, hạ sốt, giải độc, làm mát gan, làm ra mồ hôi, lợi tiểu. Chữa cảm nắng, sốt nóng, cao huyết áp, viêm gan hoàng đảm, dị ứng mẩn ngứa, đái khó, nước tiểu đỏ.', 'Ngày dùng 12 – 16g (khô), 80 – 120g (cây tươi), đun sôi trong 15-20 phút, để nguội chắt lấy nước uống.', '', 10, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('co-nho-noi', 'CỎ NHỌ NỒI', 'Cỏ mực, Hạn liên thảo, lệ trường, phong trường, mạy mỏ lắc nà (Tày), nhả cha chát (Thái)', 'Eclipta prostrata (L.) L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae)', 'Phần trên mặt đất', 'Lương huyết, chỉ huyết, bổ can thận, chữa các chứng huyết nhiệt, ho ra máu, nôn ra máu, đại tiện ra máu, tiểu tiện ra máu, chảy máu cam, chảy máu dưới da, băng huyết, rong huyết, râu tóc sớm bạc, răng lợi sưng đau.', 'Ngày dùng 12 - 20g (khô), sắc uống; 30 – 50g (tươi), giã vắt lấy nước uống, bã đắp vết thương. Có thể dùng phối hợp với các cây thuốc khác chữa chứng xuất huyết.', '', 11, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('co-sua-la-nho', 'CỎ SỮA LÁ NHỎ', 'Vú sữa đất, thiên căn thảo, cẩm địa', 'Euphorbia thymifolia L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thầu dầu (Euphorbiaceae)', 'Cả cây', 'Cầm máu, giảm đau, tiêu độc, chỉ lỵ, thông sữa, lợi tiểu. Chữa lỵ trực khuẩn và lỵ amip nhất là cho trẻ em, chữa mụn nhọt, phụ nữ băng huyết, phụ nữ sau đẻ ít sữa hoặc tắc tia sữa.', 'Người lớn: ngày dùng 40 – 100g; trẻ em: ngày dùng 10 – 20g, sắc uống, dùng 5 -7 ngày.', '', 12, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('co-tranh', 'CỎ TRANH', 'Cỏ tranh răng, bạch mao căn, dia (K’Dong), nhất địa (Gia Rai)', 'Imperata cylindrica (L.) Beauv.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Lúa (Poaceae)', 'Thân rễ', 'Lương huyết, chỉ huyết, thanh nhiệt, lợi tiểu, giảm đau. Chữa phiền khát, tiểu tiện khó, tiểu ít, tiểu buốt, tiểu ra máu, ho ra máu, chảy máu cam do huyết nhiệt, phù thũng do viêm cầu thận cấp, hoàng đản.', 'Ngày dùng 9 - 30g (khô), 30 – 60g (tươi) thái nhỏ, sắc với 600 ml nước đến khi còn 200 ml chia 2 – 3 lần uống trong ngày.', '', 13, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('co-xuoc', 'CỎ XƯỚC', 'Hoài ngưu tất.', 'Achyranthes aspera L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Rau dền (Amaranthaceae)', 'Rễ đã phơi khô hoặc sấy khô.', 'Hoạt huyết, khứ ứ, bổ can thận mạnh gân xương, lợi thủy thông lâm. Chữa đau nhức xương khớp, đau lưng, mỏi gối, chân tay co quắp, tê bại, kinh nguyệt không đều, tiểu tiện không thông, đái buốt, đái rắt.', 'Ngày dùng 6 - 15g; 12 – 40g, sắc uống.', 'Phụ nữ có thai, ỉa lỏng, di tinh.', 14, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true)
on conflict(seed_key) do update set
  name=excluded.name,other_names=excluded.other_names,botanical_name=excluded.botanical_name,category=excluded.category,
  family=excluded.family,used_part=excluded.used_part,traditional_actions=excluded.traditional_actions,dosage=excluded.dosage,
  caution=excluded.caution,source_page=excluded.source_page,visual_variant=excluded.visual_variant,source_code=excluded.source_code,
  source_ref=excluded.source_ref,seedable=excluded.seedable;
