-- QD4664 official catalog rows 43-56 of 70.

insert into private.herb_garden_species(seed_key,name,other_names,botanical_name,category,family,used_part,traditional_actions,dosage,caution,source_page,visual_variant,source_code,source_ref,seedable) values
  ('mach-mon', 'MẠCH MÔN', 'Mạch môn đông, mạch đông, tóc tiên, cỏ lan', 'Ophiopogon japonicus (L.f) Ker-Gawl.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Mạch môn (Haemodoraceae)', 'Rễ củ phơi hay sấy khô.', 'Dưỡng vị, sinh tân, nhuận phế thanh tâm. Chữa phế nhiệt do âm hư, kho khan, ho lao, tân dịch hư tổn, tâm phiền mất ngủ, tiêu khát, táo bón.', 'Ngày dùng 6 – 12g, sắc uống.', '', 43, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('man-tuoi', 'MẦN TƯỚI', 'Lan thảo, hương thảo.', 'Eupatorium fortunei Turcz.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae)', 'Phần trên mặt đất phơi hay sấy khô.', 'Hoạt huyết, tán ứ, lợi thủy, tiêu thũng, sát trùng. Chữa kinh nguyệt không đều, phụ nữ sau sinh huyết ứ, phù thũng, mụn nhọt, lở ngứa ngoài da.', 'Ngày dùng 6 – 12g, sắc uống. Dùng ngoài cả cây, giã nát đắp vào mụn nhọt, lở ngứa.', '', 44, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('mo-qua', 'MỎ QUẠ', 'Hoàng lồ, Vàng lồ, Xuyên phá thạch.', 'Maclura cochinchinensis (Lour.) Corn.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Dâu tằm (Moraceae).', 'Lá, rễ', 'Sát trùng, chỉ thống, chỉ ho. Chữa vết thương phần mềm, ho ra máu.', 'Lá tươi 100 – 200g, tùy theo vết thương, bỏ gân lá, giã nhỏ đắp vết thương.', '', 45, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('mo-tam-the', 'MƠ TAM THỂ', 'Mơ lông', 'Paederia lanuginosa Wall.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cà phê (Rubiaceae).', 'Lá', 'Thanh nhiệt, giải độc. Chữa lỵ trực khuẩn.', 'Lá tươi 30 - 50g, lau sạch, thái nhỏ trộn với trứng gà, bọc vào lá chuối đem nướng hoặc áp chảo cho chín. Ngày ăn 2 – 3 lần, trong 5 - 8 ngày.', '', 46, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('nang', 'NÁNG', 'Lá náng, Náng hoa trắng', 'Crinum asiaticum L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thuỷ tiên (Amaryllidaceae).', 'Lá, thân hành.', 'Hoạt huyết, giảm đau. Chữa sưng, tụ máu, bong gân, sai khớp do ngã, chữa thấp khớp, nhức mỏi.', 'Lá náng hơ nóng đắp vào chỗ tụ máu, bong gân, sưng tấy.', '', 47, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ngai-cuu', 'NGẢI CỨU', 'Thuốc cứu, ngải diệp, nhả ngải (Tày), quá sú (H’mông), co linh li (Thái)', 'Artemisia vulgaris L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae).', 'Bộ phận trên mặt đất', 'Chỉ huyết, trừ hàn thấp, điều kinh, an thai. Chữa phong thấp, kinh nguyệt không đều, băng kinh, rong huyết, khí hư, bạch đới.', 'Ngày dùng: 6 – 12g, sắc hoặc hãm uống. Ngoài ra, còn dùng làm ngải nhung để làm thuốc cứu.', '', 48, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('nghe', 'NGHỆ', 'Nghệ vàng, Khương hoàng, Co hem, Co khản mỉn (Thái)', 'Curcuma longa L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Gừng (Zingiberaceae)', 'Thân rễ (củ)', 'Khương hoàng (củ cái) có tác dụng hành khí, phá huyết, thông kinh, chỉ thống, sinh cơ. Chữa kinh nguyệt không đều, bế kinh, ứ máu, vùng ngực bụng trướng đau tức, đau mạng sườn, sau khi đẻ máu xấu không ra, kết hòn đau bụng, viêm loét dạ dày, vết thương lâu liền miệng; Uất kim (củ nhánh) có tác dụng hành khí giải uất, hành huyết phá ứ, chỉ huyết, lợi mật. Chữa thổ huyết, ra máu cam, đái ra máu, huyết ứ, mạng sườn đau, viêm gan, hoàng đảm, xơ gan.', 'Khương hoàng ngày dùng 6 – 12g (dạng thuốc sắc hoặc bột), chia 2 – 3 lần; Uất kim ngày dùng 2 – 10g (dạng thuốc bột), chia 2 – 3 lần. Nghệ tươi giã nhỏ vắt lấy nước bôi vào mụn nhọt, viêm tấy lở loét ngoài da, bôi lên các mụn mới khỏi giúp chóng lên da non làm mờ sẹo.', '', 49, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ngu-gia-bi-chan-chim', 'NGŨ GIA BÌ CHÂN CHIM', 'Cây chân chim, Cây đáng, Cây lằng, Sâm non', 'Schefflera heptaphylla (L.) Frodin', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Ngũ gia (Araliaceae).', 'Vỏ thân', 'Khu phong, trừ thấp, mạnh gân cốt. Chữa đau lưng, đau xương do hàn thấp.', 'Ngày dùng 10 – 20g, sắc uống.', '', 50, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('nhan-tran', 'NHÂN TRẦN', 'Chè cát, chè nội, tuyến hương', 'Adenosma caeruleum R. Br.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Hoa mõm chó (Scrophulariaceae)', 'Bộ phận trên mặt đất', 'Thanh nhiệt, lợi thấp, thoái hoàng. Chữa viêm gan, viêm gan virus, viêm túi mật, vàng da, sốt nóng, tiểu tiện không thông, phụ nữ sau đẻ kém ăn.', 'Ngày dùng 10 – 15g, sắc uống.', '', 51, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('nhot', 'NHÓT', 'Cây lót, hồi đồi tử', 'Elaeagnus latifolia L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Nhót Eleaegnceae.', 'Lá, quả, rễ', 'Chỉ khát, bình suyễn, chỉ tả. Chữa hen suyễn, lỵ trực khuẩn và tiêu chảy.', 'Lá tươi 20 – 30g hoặc lá khô 6 – 12g, thái nhỏ sao vàng, sắc với 400ml nước còn 100ml chia 2 lần uống trong ngày. Rễ nấu nước tắm mụn nhọt.', '', 52, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('cay-oi', 'CÂY ỔI', 'Ủi, phan thạch lựu.', 'Psidium guajava L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Sim Myrtaceae.', 'Lá, quả', 'Sáp trường, chỉ tả. Chữa tiêu chảy.', 'Dùng quả xanh nhai, nuốt nước nhả bã, ngày dùng 15 - 20g búp non hay lá non, sắc uống.', '', 53, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('phen-den', 'PHÈN ĐEN', 'Nỗ, Tạo phan diệp.', 'Phyllanthus reticulatus Poir.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thầu dầu – Euphorbiaceae', 'Lá, vỏ thân cây', 'Sáp trường, chỉ tả. Chữa tiêu chảy.', 'Ngày dùng 15 - 20g búp non hay lá non, sắc uống.', '', 54, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('quyt', 'QUÝT', 'Quýt xiêm, quất thực', 'Citrus reticulata Blanco', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cam (Rutaceae)', 'Lá, vỏ, quả, hạt', 'Trần bì có tác dụng hành khí, táo thấp, hóa đờm. Chữa ăn không tiêu, đau bụng, nôn mửa, ho tức ngực, nhiều đờm. Thanh bì (vỏ quả còn xanh) có tác dụng sơ can, phá khí, tán kết, tiêu đờm. Chữa ngực sườn đau tức. Hạt quýt (quất hạch) có tác dụng hành khí, tán kết, chỉ thống. Chữa sa ruột, bìu sưng đau, đau lưng, viêm tuyến vú. Lá quýt (quất diệp) có tác dụng sơ can, hành khí, hóa đờm. Chữa ngực đau tức, ho, sưng vú.', 'Trần bì ngày dùng 4 – 12g, dạng sắc hoặc tán; Thanh bì ngày dùng 3 – 9g. Hạt quýt ngày dùng: 3 – 9g; lá quýt ngày dùng 10 – 20 lá, sắc uống.', '', 55, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('rau-ma', 'RAU MÁ', 'Liên tiền thảo', 'Centella asiatica (L.) Urban', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Hoa tán (Apiaceae)', 'Cả cây', 'Thanh nhiệt trừ thấp, giải độc, tiêu viêm. Chữa sốt, mụn nhọt, vàng da, thổ huyết, chảy máu cam, táo bón, ho, tiểu tiện rắt buốt.', 'Ngày dùng: 30 – 40g (tươi), vò nát, vắt lấy nước hoặc dạng khô sắc uống. Có thể dùng phối hợp với cỏ nhọ nồi có tác dụng cầm máu.', '', 56, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true)
on conflict(seed_key) do update set
  name=excluded.name,other_names=excluded.other_names,botanical_name=excluded.botanical_name,category=excluded.category,
  family=excluded.family,used_part=excluded.used_part,traditional_actions=excluded.traditional_actions,dosage=excluded.dosage,
  caution=excluded.caution,source_page=excluded.source_page,visual_variant=excluded.visual_variant,source_code=excluded.source_code,
  source_ref=excluded.source_ref,seedable=excluded.seedable;
