-- Chuyển 20 câu trắc nghiệm của bài học 'Dược liệu & Phương tễ' (Learning Hub) vào ngân hàng câu hỏi.
-- Bài học bị gỡ khỏi giao diện; tiến độ học của thành viên (study_lesson_progress_v1, lesson_id
-- tcm-herbs-formulas-v1) được GIỮ NGUYÊN. Migration thuần bổ sung, chạy lại an toàn.

insert into public.practice_source_documents(drive_file_id,file_name,mime_type,source_modified_time,source_hash,subject_hint,sync_status,sync_message,question_count,last_synced_at)
values('legacy-lesson:tcm-herbs-formulas-v1','Bài học: Dược liệu & Phương tễ trong Y học cổ truyền (ThS.BS Nhan Hồng Tâm)','text/plain',null,'legacy-lesson-tcm-herbs-formulas-v1','Dược liệu & Phương tễ','ready','Chuyển từ bài học Learning Hub đã gỡ',20,now())
on conflict(drive_file_id) do nothing;

insert into public.practice_questions(external_key,content_hash,subject,topic,stem,options,correct_index,explanation,source_file_id,source_file_name,source_modified_time,source_hash,generation_method,review_status,provenance)
select v.external_key, md5(v.stem), 'Dược liệu & Phương tễ', v.topic, v.stem, v.options, v.correct_index::smallint, v.explanation,
       'legacy-lesson:tcm-herbs-formulas-v1', 'Bài học: Dược liệu & Phương tễ trong Y học cổ truyền (ThS.BS Nhan Hồng Tâm)', null,
       'legacy-lesson-tcm-herbs-formulas-v1', 'parsed', 'source_verified',
       jsonb_build_object('origin','learning-hub-lesson','lesson_id','tcm-herbs-formulas-v1','position',v.pos)
from (values
  ('legacy-lesson:tcm-herbs-formulas-v1:Q01', $q$Dược liệu$q$, $q$Theo tài liệu, Nhân Sâm có công dụng nổi bật nào?$q$, ARRAY[$q$Thanh nhiệt táo thấp$q$, $q$Đại bổ nguyên khí$q$, $q$Hoạt huyết thư cân$q$, $q$Giải biểu khu phong$q$]::text[], 1, $q$Nhân Sâm: đại bổ nguyên khí, tăng cường sức khỏe, tăng cường miễn dịch.$q$, 1),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q02', $q$Dược liệu$q$, $q$Dược liệu nào được mô tả “bổ huyết, điều kinh, dưỡng huyết”?$q$, ARRAY[$q$Đương Quy$q$, $q$Hoàng Cầm$q$, $q$Đỗ Trọng$q$, $q$Ngưu Tất$q$]::text[], 0, $q$Đương Quy được tài liệu mô tả với công dụng bổ huyết, điều kinh, dưỡng huyết.$q$, 2),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q03', $q$Dược liệu$q$, $q$Xuyên Khung được nêu với nhóm công dụng nào?$q$, ARRAY[$q$Bổ can thận, an thai$q$, $q$Hoạt huyết, hành khí, giảm đau đầu$q$, $q$Thanh nhiệt, chỉ tả$q$, $q$Dưỡng huyết, minh mục$q$]::text[], 1, $q$Xuyên Khung: hoạt huyết, hành khí, giảm đau đầu.$q$, 3),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q04', $q$Dược liệu$q$, $q$Hoàng Kỳ theo tài liệu có công dụng nào?$q$, ARRAY[$q$Bổ khí, tăng sức đề kháng, lợi tiểu$q$, $q$Thanh nhiệt, giải độc, tiêu đàm$q$, $q$Bổ huyết, thư cân$q$, $q$Bổ thận âm$q$]::text[], 0, $q$Hoàng Kỳ: bổ khí, tăng cường sức đề kháng, lợi tiểu.$q$, 4),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q05', $q$Dược liệu$q$, $q$Bạch Chỉ thuộc mô tả nào?$q$, ARRAY[$q$Giải biểu, khu phong, chỉ thống$q$, $q$Bổ huyết, điều kinh$q$, $q$Thanh nhiệt, táo thấp, chỉ ho$q$, $q$Bổ can thận, cường gân cốt$q$]::text[], 0, $q$Bạch Chỉ: giải biểu, khu phong, chỉ thống.$q$, 5),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q06', $q$Dược liệu$q$, $q$Hoàng Liên được tài liệu xếp công dụng chính là gì?$q$, ARRAY[$q$Bổ khí$q$, $q$Thanh nhiệt, giải độc, chỉ tả$q$, $q$Dưỡng huyết$q$, $q$Lợi niệu, thư cân$q$]::text[], 1, $q$Hoàng Liên: thanh nhiệt, giải độc, chỉ tả.$q$, 6),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q07', $q$Dược liệu$q$, $q$Hoàng Cầm thường được nêu cho ho do đâu?$q$, ARRAY[$q$Phế nhiệt$q$, $q$Khí hư$q$, $q$Huyết hư$q$, $q$Thận dương hư$q$]::text[], 0, $q$Ví dụ trong tài liệu: Hoàng cầm dùng cho ho do phế nhiệt và tiêu chảy do thấp nhiệt.$q$, 7),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q08', $q$Dược liệu$q$, $q$Dược liệu nào có mô tả “bổ Can thận, dưỡng huyết, minh mục”?$q$, ARRAY[$q$Xạ Can$q$, $q$Câu Kỷ Tử$q$, $q$Kê Huyết Đằng$q$, $q$Bạch Chỉ$q$]::text[], 1, $q$Câu Kỷ Tử: bổ Can thận, dưỡng huyết, minh mục.$q$, 8),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q09', $q$Dược liệu$q$, $q$Đỗ Trọng được nêu với công dụng nào?$q$, ARRAY[$q$Bổ can thận, cường gân cốt, an thai$q$, $q$Bổ thận âm, minh mục$q$, $q$Thanh nhiệt, giải độc, chỉ tả$q$, $q$Hoạt huyết, hành khí$q$]::text[], 0, $q$Đỗ Trọng: bổ can thận, cường gân cốt, an thai.$q$, 9),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q10', $q$Dược liệu$q$, $q$Ngưu Tất được mô tả với nhóm tác dụng nào?$q$, ARRAY[$q$Hoạt huyết, lợi niệu, thư cân$q$, $q$Bổ khí, kiện tỳ$q$, $q$Bổ huyết, điều kinh$q$, $q$Giải biểu, khu phong$q$]::text[], 0, $q$Ngưu Tất: hoạt huyết, lợi niệu, thư cân.$q$, 10),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q11', $q$Phương tễ$q$, $q$Tứ Quân Tử Thang gồm nhóm nào?$q$, ARRAY[$q$Nhân Sâm, Bạch Truật, Phục Linh, Cam Thảo$q$, $q$Đương Quy, Xuyên Khung, Thục Địa, Bạch Thược$q$, $q$Thục Địa, Sơn Thù, Hoài Sơn, Trạch Tả$q$, $q$Hoàng Kỳ, Nhân Sâm, Trần Bì, Sài hồ$q$]::text[], 0, $q$Bốn vị được nêu là Nhân Sâm, Bạch Truật, Phục Linh, Cam Thảo.$q$, 11),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q12', $q$Phương tễ$q$, $q$Tứ Vật Thang gồm thành phần nào?$q$, ARRAY[$q$Nhân Sâm, Bạch Truật, Phục Linh, Cam Thảo$q$, $q$Đương Quy, Xuyên Khung, Thục Địa, Bạch Thược$q$, $q$Hoàng Kỳ, Nhục Quế, Phụ Tử, Cam Thảo$q$, $q$Sơn Thù, Hoài Sơn, Trạch Tả, Phục Linh$q$]::text[], 1, $q$Tứ Vật Thang: Đương Quy, Xuyên Khung, Thục Địa, Bạch Thược.$q$, 12),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q13', $q$Phương tễ$q$, $q$Bát Trân Thang trong tài liệu được cấu tạo như thế nào?$q$, ARRAY[$q$Lục Vị + Quế Nhục + Phụ Tử$q$, $q$Tứ Quân Tử + Tứ Vật$q$, $q$Tứ Vật + Hoàng Kỳ$q$, $q$Quy Tỳ + Nhục Quế$q$]::text[], 1, $q$Bát Trân Thang = Tứ Quân Tử Thang kết hợp Tứ Vật Thang.$q$, 13),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q14', $q$Phương tễ$q$, $q$Thập Toàn Đại Bổ Hoàn được mô tả là Bát Trân Thang cộng thêm gì?$q$, ARRAY[$q$Hoàng Kỳ và Nhục Quế$q$, $q$Quế Nhục và Phụ Tử$q$, $q$Trần Bì và Sài hồ$q$, $q$Sơn Thù và Trạch Tả$q$]::text[], 0, $q$Thập Toàn Đại Bổ Hoàn = Bát Trân Thang + Hoàng Kỳ + Nhục Quế.$q$, 14),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q15', $q$Phương tễ$q$, $q$Lục Vị Địa Hoàng Hoàn được nêu với công dụng chính nào?$q$, ARRAY[$q$Bổ thận âm$q$, $q$Bổ thận dương$q$, $q$Bổ khí kiện tỳ$q$, $q$Thanh nhiệt giải độc$q$]::text[], 0, $q$Tài liệu nêu Lục Vị Địa Hoàng Hoàn có công dụng bổ thận âm.$q$, 15),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q16', $q$Phương tễ$q$, $q$Bát Vị Quế Phụ Hoàn được tạo từ Lục Vị Địa Hoàng Hoàn cộng thêm gì?$q$, ARRAY[$q$Hoàng Kỳ, Nhục Quế$q$, $q$Quế Nhục, Phụ Tử$q$, $q$Đương Quy, Xuyên Khung$q$, $q$Nhân Sâm, Cam Thảo$q$]::text[], 1, $q$Bát Vị Quế Phụ Hoàn = Lục Vị Địa Hoàng Hoàn + Quế Nhục + Phụ Tử.$q$, 16),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q17', $q$Bào chế & sắc thuốc$q$, $q$“Sao” trong phần bào chế được mô tả như thế nào?$q$, ARRAY[$q$Nấu dược liệu trong nước$q$, $q$Rang trên lửa nhỏ để làm khô và tăng tính ấm$q$, $q$Ngâm trong nước hoặc dung dịch khác$q$, $q$Chỉ phơi dưới nắng$q$]::text[], 1, $q$Tài liệu mô tả sao là rang dược liệu trên lửa nhỏ để làm khô và tăng tính ấm.$q$, 17),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q18', $q$Bào chế & sắc thuốc$q$, $q$“Tẩm” được tài liệu mô tả là gì?$q$, ARRAY[$q$Ngâm dược liệu trong nước hoặc dung dịch khác$q$, $q$Rang khô trên lửa nhỏ$q$, $q$Sắc 30–45 phút$q$, $q$Nghiền thành bột$q$]::text[], 0, $q$Tẩm là ngâm dược liệu trong nước hoặc dung dịch khác để loại tạp chất hoặc tăng tính chất của thuốc.$q$, 18),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q19', $q$Bào chế & sắc thuốc$q$, $q$Theo phần “Phương pháp sắc thuốc”, thời gian sắc thuốc thường được nêu là bao lâu?$q$, ARRAY[$q$5–10 phút$q$, $q$15–20 phút$q$, $q$30–45 phút$q$, $q$90–120 phút$q$]::text[], 2, $q$Tài liệu nêu thuốc thường được sắc 30–45 phút, đầu tiên lửa to cho sôi rồi hạ nhỏ lửa.$q$, 19),
  ('legacy-lesson:tcm-herbs-formulas-v1:Q20', $q$An toàn dùng thuốc$q$, $q$Lưu ý an toàn nào được tài liệu nhấn mạnh?$q$, ARRAY[$q$Mọi dược liệu đều dùng được cùng thuốc Tây$q$, $q$Phụ nữ có thai, trẻ em, người già không cần tư vấn$q$, $q$Một số dược liệu có thể tương tác với thuốc Tây$q$, $q$Có thể tự tăng liều nếu triệu chứng nặng$q$]::text[], 2, $q$Tài liệu nhấn mạnh một số dược liệu có thể tương tác với thuốc Tây và cần đặc biệt chú ý.$q$, 20)
) as v(external_key,topic,stem,options,correct_index,explanation,pos)
on conflict(external_key) do nothing;
