-- QD4664 official catalog rows 29-42 of 70.

insert into private.herb_garden_species(seed_key,name,other_names,botanical_name,category,family,used_part,traditional_actions,dosage,caution,source_page,visual_variant,source_code,source_ref,seedable) values
  ('ha-kho-thao', 'HẠ KHÔ THẢO', '', 'Prunella vulgaris L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae).', 'Cụm quả đã phơi hay sấy khô.', 'Thanh nhiệt giáng hỏa, minh mục, tán kết, tiêu sưng. Chữa lao hạch, bướu cổ, áp xe vú, đau mắt, viêm tử cung, viêm gan, cao huyết áp, ngứa, hắc lào, vẩy nến.', 'Ngày 9 - 15 g, dạng thuốc sắc.', '', 29, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('hoac-huong', 'HOẮC HƯƠNG', 'Thổ Hoắc hương, Quảng Hoắc hương', 'Pogostemon cablin (Blanco) Benth.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae).', 'Lá phơi hay sấy khô', 'Giải thử, hóa thấp, chỉ nôn. Chữa cảm mạo, nhức đầu, đau mình mẩy, sổ mũi, đau bụng tiêu chảy, ăn uống không tiêu vào mùa hè.', '', '', 30, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('hung-chanh', 'HÚNG CHANH', 'Dương tử tô, Rau thơm lông.', 'Plectranthus amboinicus (Lour.) Spreng.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae).', 'Lá tươi hoặc dùng phần trên mặt đất cất lấy tinh dầu.', 'Ổn phế, trừ đàm, tân ôn giải biểu, giải độc. Chữa cảm cúm, sốt nóng về chiều, chữa ho, viêm họng, khản tiếng, chữa thổ huyết, chảy máu cam, táo bón. Dùng ngoài giã đắp lên những vết do rết và bọ cạp cắn.', '', '', 31, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('huong-nhu-tia', 'HƯƠNG NHU TÍA', 'É tía', 'Ocimum tenuiflorum L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae)', 'Bộ phận trên mặt đất', 'Phát hãn, thanh thử, tán thấp, hành thủy, giảm đau. Chữa sốt cao, say nắng, nhức đầu, đau bụng, đi ngoài, nôn mửa, phù thũng.', 'Ngày dùng: 6 – 12g, sắc hoặc hãm uống. Có thể dùng Hương nhu trắng để thay thế.', '', 32, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('huyet-du', 'HUYẾT DỤ', '', 'Cordyline fruticosa (L.) Goepp.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'họ Huyết giác (Dracaenaceae)', 'Lá tươi hoặc khô.', 'Thanh nhiệt, cầm máu, tan huyết, giảm đau. Chữa rong huyết, băng huyết, đái ra máu, sốt xuất huyết. Lá chữa vết thương.', 'Ngày dùng: 8 – 16g, sắc uống.', '', 33, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('hy-thiem', 'HY THIÊM', 'Cỏ đĩ, Cây cứt lợn, Hy tiên.', 'Siegesbeckia orientalis L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae).', 'Phần trên mặt đất', 'Trừ phong thấp, thanh nhiệt, giải độc. Chữa đau lưng, mỏi gối, đau xương khớp, chân tay tê buốt, mụn nhọt.', 'Ngày dùng: 9 – 12g, sắc uống.', '', 34, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ich-mau', 'ÍCH MẪU', 'Cây chói đèn, sung uý', 'Leonurus japonicus Houtt', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae)', 'Bộ phận trên mặt đất', 'Hoạt huyết, điều kinh, khứ ứ, tiêu thũng. Chữa rối loạn kinh nguyệt, kinh bế, đau bụng kinh, khí hư bạch đới, rong kinh, rong huyết, phụ nữ sau đẻ huyết hôi không ra hết.', 'Ngày dùng: thân lá 6 – 12g, hạt: 4 – 9g, sắc uống.', '', 35, 3, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ke-dau-ngua', 'KÉ ĐẦU NGỰA', 'Thương nhĩ', 'Xanthium strumarium L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Cúc (Asteraceae)', 'Quả già', 'Tiêu độc, sát trùng, tán phong thông khiếu, trừ thấp. Chữa phong hàn, đau đầu, chân tay co rút, đau khớp, mũi chảy nước hôi, mày đay, lở ngứa, tràng nhạc, mụn nhọt, mẩn ngứa.', 'Ngày dùng 6 – 12g, sắc uống.', '', 36, 4, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('kho-sam-cho-la', 'KHỔ SÂM CHO LÁ', 'Khổ sâm Bắc bộ, cù đèn, co chạy đón (Thái)', 'Croton tonkinensis Gagnep.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Thầu dầu (Euphorbiaceae).', 'Lá và cành thu hái khi cây đang có hoa, phơi khô.', 'Thanh nhiệt, giải độc, sát trùng. Chữa viêm loét dạ dày, tiêu hóa kém, mụn nhọt, lở loét ngoài da, viêm mũi.', 'Ngày dùng 15 – 20g, sắc uống. Dùng ngoài lấy nước sắc để rửa, chữa mụn nhọt, lở ngứa.', '', 37, 5, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('kim-ngan', 'KIM NGÂN', 'Dây nhẫn đông, chừa giang khằn (Thái), boóc kim ngằn (Tày)', 'Lonicera japonica Thunb.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Kim ngân (Caprifoliaceae)', 'Thân, lá, hoa', 'Thanh nhiệt giải độc, tán phong nhiệt. Chữa mụn nhọt, mề đay, lở ngứa, nhiệt độc ban sởi, dị ứng, lỵ, cảm mạo phong nhiệt, ho do phế nhiệt, viêm mũi dị ứng.', 'Kim ngân được dùng riêng hay phối hợp với nhiều vị thuốc khác. Ngày dùng 4 – 6g (hoa) hay 15 – 30g (cành, lá), dùng dưới dạng thuốc sắc uống, thuốc hãm hoặc hoàn tán.', '', 38, 6, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('kim-tien-thao', 'KIM TIỀN THẢO', 'Đồng tiền lông, mắt trâu, vảy rồng', 'Desmodium styracifolium (Osbeck) Merr.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Đậu (Fabaceae)', 'Bộ phận trên mặt đất', 'Thanh nhiệt, trừ thấp, lợi tiểu, thông lâm. Chữa sỏi đường tiết niệu, đái buốt, viêm gan vàng da, phù thũng.', 'Ngày dùng 15 – 30g, sắc uống.', '', 39, 7, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('kinh-gioi', 'KINH GIỚI', 'Khương giới, giả tô, nhả nát hom (Thái)', 'Elsholtzia ciliata (Thunb.) Hyland.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Bạc hà (Lamiaceae)', 'Bộ phận trên mặt đất (ngọn mang hoa)', 'Giải biểu, khu phong, chỉ ngứa. Chữa cảm mạo, sốt, nhức đầu, hoa mắt, viêm họng, ngứa, phong trúng kinh lạc.', 'Ngày dùng 6 – 12g (dạng khô), sắc hoặc hãm uống. Khi sao đen được dùng chữa băng huyết, rong kinh, thổ huyết, chảy máu cam, đại tiện ra máu, ngày dùng: 6 – 12g, sắc hoặc hãm uống.', '', 40, 8, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('la-lot', 'LÁ LỐT', 'Tất bát', 'Piper lolot C. DC.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Hồ tiêu (Piperaceae)', 'Dùng toàn cây', 'Ôn trung, tán hàn, hạ khí, chỉ thống, trừ phong thấp, kiện vị, tiêu thực, chỉ ẩu. Chữa chứng phong thấp, thấp khớp mạn, đau lưng, đau khớp, đau nhức xương, tay chân tê bại, rối loạn tiêu hóa, nôn mửa đầy hơi, trướng bụng, tiêu chảy, đau đầu, đau nhức răng, chảy nước mũi hôi, ra mồ hôi chân tay.', 'Ngày dùng 8 – 12g (khô) hay 15 – 30g (tươi), sắc uống, chia 2 -3 lần.', '', 41, 1, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true),
  ('ma-de', 'MÃ ĐỀ', 'Xa tiền, bông mã đề', 'Plantago major L.', 'Danh mục cây thuốc mẫu Bộ Y tế', 'Mã đề (Plantaginaceae)', 'lá, hạt', 'Thanh thấp nhiệt, lợi tiểu, thông lâm, chỉ huyết. Chữa ho lâu ngày, viêm khí quản, viêm thận và bàng quang, đau dạ dầy, bí tiểu tiện, tiểu tiện ra máu hoặc ra sỏi tiết niệu, phù thũng, chảy máu cam. Dùng ngoài lá mã đề có tác dụng làm mụn nhọt chóng vỡ, mau lành.', 'Ngày dùng 10 – 20g (toàn cây) hay 6 – 12g (hạt), sắc uống. Dùng ngoài lấy lá mã đề lượng vừa đủ, giã nát đắp vào nơi có mụn.', '', 42, 2, 'QD4664-2014', 'Bộ tranh cây thuốc mẫu - Quyết định 4664/QĐ-BYT ngày 07/11/2014, Bộ Y tế', true)
on conflict(seed_key) do update set
  name=excluded.name,other_names=excluded.other_names,botanical_name=excluded.botanical_name,category=excluded.category,
  family=excluded.family,used_part=excluded.used_part,traditional_actions=excluded.traditional_actions,dosage=excluded.dosage,
  caution=excluded.caution,source_page=excluded.source_page,visual_variant=excluded.visual_variant,source_code=excluded.source_code,
  source_ref=excluded.source_ref,seedable=excluded.seedable;
