import {useEffect,useState} from 'react';
import {CheckCircle2,Download,MonitorSmartphone,Settings,Share2,X} from 'lucide-react';
import ViewportModeToggle,{type ViewportMode} from './ViewportModeToggle';
import {getPwaInstallStatus,requestPwaInstall,subscribePwaInstall,type PwaInstallStatus} from '../../services/pwaInstallService';
import {getPerformancePreference,setPerformancePreference,type PerformancePreference} from '../../services/deviceCapability';

export default function AppSettingsDialog({open,onClose,viewportMode,onViewportChange}:{open:boolean;onClose:()=>void;viewportMode:ViewportMode;onViewportChange:(mode:ViewportMode)=>void}){
  const [status,setStatus]=useState<PwaInstallStatus>(()=>getPwaInstallStatus()),[message,setMessage]=useState(''),[performance,setPerformance]=useState<PerformancePreference>(getPerformancePreference);
  useEffect(()=>subscribePwaInstall(()=>setStatus(getPwaInstallStatus())),[]);
  useEffect(()=>{if(open){setStatus(getPwaInstallStatus());setPerformance(getPerformancePreference());setMessage('')}},[open]);
  if(!open)return null;
  const install=async()=>{setMessage('');const result=await requestPwaInstall();setStatus(getPwaInstallStatus());if(result.status==='accepted')setMessage('Chrome đã chấp nhận yêu cầu cài đặt ứng dụng.');else if(result.status==='dismissed')setMessage('Bạn đã đóng hộp thoại cài đặt. Có thể thử lại sau.');else if(result.status==='installed')setMessage('Ứng dụng đã được cài trên thiết bị.');else setMessage('Chrome chưa phát tín hiệu cài đặt. Hãy mở bản production bằng Chrome và dùng mục “Cài đặt ứng dụng” của trình duyệt nếu nút này chưa sẵn sàng.')};
  const share=async()=>{const data={title:'HIU YHCT 4.0',text:'Ứng dụng all-in-one học thuật Y học cổ truyền dành cho sinh viên HIU.',url:window.location.origin};try{const nav=navigator as Navigator&{share?:(value:ShareData)=>Promise<void>};if(nav.share){await nav.share(data);setMessage('Đã mở chức năng chia sẻ của thiết bị.')}else{await navigator.clipboard.writeText(data.url);setMessage('Đã sao chép liên kết HIU YHCT 4.0.')}}catch{setMessage('Chưa thể chia sẻ trên trình duyệt này.')}};
  const changePerformance=(value:PerformancePreference)=>{setPerformance(value);setPerformancePreference(value)};
  return <div className="app-settings-backdrop" onMouseDown={onClose}><section className="app-settings-dialog" role="dialog" aria-modal="true" aria-label="Cài đặt ứng dụng" onMouseDown={e=>e.stopPropagation()}>
    <header><div><Settings/><span><b>Cài đặt</b><small>Ứng dụng YHCT HIU 4.0</small></span></div><button className="icon-btn" onClick={onClose} aria-label="Đóng cài đặt"><X/></button></header>
    <article className="app-install-card"><div className="row"><MonitorSmartphone/><div><h3>Cài ứng dụng mạng xã hội</h3><p>Cài dưới dạng PWA độc lập của Chrome, chạy ở chế độ <b>standalone</b>; đây không phải lối tắt web thông thường.</p></div></div>{status==='installed'?<div className="install-ready"><CheckCircle2/> Đã cài đặt trên thiết bị</div>:status==='available'?<button className="install-primary" onClick={()=>void install()}><Download/>Cài ứng dụng</button>:<><button className="install-primary" onClick={()=>void install()}><Download/>Kiểm tra khả năng cài đặt</button><small>Chrome chỉ phát lời mời cài khi ứng dụng đáp ứng HTTPS + manifest + service worker và chưa được cài trước đó.</small></>}<button className="secondary" onClick={()=>void share()}><Share2/>Chia sẻ ứng dụng</button>{message&&<div className="ai-note" role="status">{message}</div>}</article>
    <article className="app-display-card"><div><h3>Chế độ hiển thị</h3><p>Chọn bố cục phù hợp thiết bị; theme màu sắc vẫn đồng bộ toàn hệ thống.</p></div><ViewportModeToggle mode={viewportMode} onChange={onViewportChange} className="viewport-toggle--settings"/></article>
    <article className="app-display-card"><div><h3>Hiệu ứng & hiệu năng</h3><p>Để hệ thống tự cân bằng theo thiết bị hoặc dùng chế độ nhẹ khi cần giảm hiệu ứng.</p></div><label htmlFor="performance-mode-settings">Hiệu năng<select id="performance-mode-settings" value={performance} onChange={e=>changePerformance(e.target.value as PerformancePreference)}><option value="auto">Tự động theo thiết bị</option><option value="low">Chế độ nhẹ</option></select></label></article>
  </section></div>;
}